// This file is generated by rust-protobuf 3.7.2. Do not edit
// .proto file is parsed by pure
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_results)]
#![allow(unused_mut)]

//! Generated file from `grSim_Packet.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_3_7_2;

// @@protoc_insertion_point(message:grSim_Packet)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct GrSim_Packet {
    // message fields
    // @@protoc_insertion_point(field:grSim_Packet.commands)
    pub commands: ::protobuf::MessageField<super::grSim_Commands::GrSim_Commands>,
    // @@protoc_insertion_point(field:grSim_Packet.replacement)
    pub replacement: ::protobuf::MessageField<super::grSim_Replacement::GrSim_Replacement>,
    // special fields
    // @@protoc_insertion_point(special_field:grSim_Packet.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a GrSim_Packet {
    fn default() -> &'a GrSim_Packet {
        <GrSim_Packet as ::protobuf::Message>::default_instance()
    }
}

impl GrSim_Packet {
    pub fn new() -> GrSim_Packet {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(2);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_message_field_accessor::<_, super::grSim_Commands::GrSim_Commands>(
            "commands",
            |m: &GrSim_Packet| { &m.commands },
            |m: &mut GrSim_Packet| { &mut m.commands },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_message_field_accessor::<_, super::grSim_Replacement::GrSim_Replacement>(
            "replacement",
            |m: &GrSim_Packet| { &m.replacement },
            |m: &mut GrSim_Packet| { &mut m.replacement },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<GrSim_Packet>(
            "grSim_Packet",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for GrSim_Packet {
    const NAME: &'static str = "grSim_Packet";

    fn is_initialized(&self) -> bool {
        for v in &self.commands {
            if !v.is_initialized() {
                return false;
            }
        };
        for v in &self.replacement {
            if !v.is_initialized() {
                return false;
            }
        };
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                10 => {
                    ::protobuf::rt::read_singular_message_into_field(is, &mut self.commands)?;
                },
                18 => {
                    ::protobuf::rt::read_singular_message_into_field(is, &mut self.replacement)?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if let Some(v) = self.commands.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        }
        if let Some(v) = self.replacement.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if let Some(v) = self.commands.as_ref() {
            ::protobuf::rt::write_message_field_with_cached_size(1, v, os)?;
        }
        if let Some(v) = self.replacement.as_ref() {
            ::protobuf::rt::write_message_field_with_cached_size(2, v, os)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> GrSim_Packet {
        GrSim_Packet::new()
    }

    fn clear(&mut self) {
        self.commands.clear();
        self.replacement.clear();
        self.special_fields.clear();
    }

    fn default_instance() -> &'static GrSim_Packet {
        static instance: GrSim_Packet = GrSim_Packet {
            commands: ::protobuf::MessageField::none(),
            replacement: ::protobuf::MessageField::none(),
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for GrSim_Packet {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("grSim_Packet").unwrap()).clone()
    }
}

impl ::std::fmt::Display for GrSim_Packet {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for GrSim_Packet {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\x12grSim_Packet.proto\x1a\x14grSim_Commands.proto\x1a\x17grSim_Replac\
    ement.proto\"q\n\x0cgrSim_Packet\x12+\n\x08commands\x18\x01\x20\x01(\x0b\
    2\x0f.grSim_CommandsR\x08commands\x124\n\x0breplacement\x18\x02\x20\x01(\
    \x0b2\x12.grSim_ReplacementR\x0breplacementb\x06proto2\
";

/// `FileDescriptorProto` object which was a source for this generated file
fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    static file_descriptor_proto_lazy: ::protobuf::rt::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::Lazy::new();
    file_descriptor_proto_lazy.get(|| {
        ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
    })
}

/// `FileDescriptor` object which allows dynamic access to files
pub fn file_descriptor() -> &'static ::protobuf::reflect::FileDescriptor {
    static generated_file_descriptor_lazy: ::protobuf::rt::Lazy<::protobuf::reflect::GeneratedFileDescriptor> = ::protobuf::rt::Lazy::new();
    static file_descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::FileDescriptor> = ::protobuf::rt::Lazy::new();
    file_descriptor.get(|| {
        let generated_file_descriptor = generated_file_descriptor_lazy.get(|| {
            let mut deps = ::std::vec::Vec::with_capacity(2);
            deps.push(super::grSim_Commands::file_descriptor().clone());
            deps.push(super::grSim_Replacement::file_descriptor().clone());
            let mut messages = ::std::vec::Vec::with_capacity(1);
            messages.push(GrSim_Packet::generated_message_descriptor_data());
            let mut enums = ::std::vec::Vec::with_capacity(0);
            ::protobuf::reflect::GeneratedFileDescriptor::new_generated(
                file_descriptor_proto(),
                deps,
                messages,
                enums,
            )
        });
        ::protobuf::reflect::FileDescriptor::new_generated_2(generated_file_descriptor)
    })
}
