// This file is generated by rust-protobuf 3.7.2. Do not edit
// .proto file is parsed by pure
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_results)]
#![allow(unused_mut)]

//! Generated file from `grSim_Robotstatus.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_3_7_2;

// @@protoc_insertion_point(message:Robots_Status)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct Robots_Status {
    // message fields
    // @@protoc_insertion_point(field:Robots_Status.robots_status)
    pub robots_status: ::std::vec::Vec<Robot_Status>,
    // special fields
    // @@protoc_insertion_point(special_field:Robots_Status.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a Robots_Status {
    fn default() -> &'a Robots_Status {
        <Robots_Status as ::protobuf::Message>::default_instance()
    }
}

impl Robots_Status {
    pub fn new() -> Robots_Status {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(1);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_vec_simpler_accessor::<_, _>(
            "robots_status",
            |m: &Robots_Status| { &m.robots_status },
            |m: &mut Robots_Status| { &mut m.robots_status },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<Robots_Status>(
            "Robots_Status",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for Robots_Status {
    const NAME: &'static str = "Robots_Status";

    fn is_initialized(&self) -> bool {
        for v in &self.robots_status {
            if !v.is_initialized() {
                return false;
            }
        };
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                10 => {
                    self.robots_status.push(is.read_message()?);
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        for value in &self.robots_status {
            let len = value.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        };
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        for v in &self.robots_status {
            ::protobuf::rt::write_message_field_with_cached_size(1, v, os)?;
        };
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> Robots_Status {
        Robots_Status::new()
    }

    fn clear(&mut self) {
        self.robots_status.clear();
        self.special_fields.clear();
    }

    fn default_instance() -> &'static Robots_Status {
        static instance: Robots_Status = Robots_Status {
            robots_status: ::std::vec::Vec::new(),
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for Robots_Status {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("Robots_Status").unwrap()).clone()
    }
}

impl ::std::fmt::Display for Robots_Status {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for Robots_Status {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

// @@protoc_insertion_point(message:Robot_Status)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct Robot_Status {
    // message fields
    // @@protoc_insertion_point(field:Robot_Status.robot_id)
    pub robot_id: ::std::option::Option<i32>,
    // @@protoc_insertion_point(field:Robot_Status.infrared)
    pub infrared: ::std::option::Option<bool>,
    // @@protoc_insertion_point(field:Robot_Status.flat_kick)
    pub flat_kick: ::std::option::Option<bool>,
    // @@protoc_insertion_point(field:Robot_Status.chip_kick)
    pub chip_kick: ::std::option::Option<bool>,
    // special fields
    // @@protoc_insertion_point(special_field:Robot_Status.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a Robot_Status {
    fn default() -> &'a Robot_Status {
        <Robot_Status as ::protobuf::Message>::default_instance()
    }
}

impl Robot_Status {
    pub fn new() -> Robot_Status {
        ::std::default::Default::default()
    }

    // required int32 robot_id = 1;

    pub fn robot_id(&self) -> i32 {
        self.robot_id.unwrap_or(0)
    }

    pub fn clear_robot_id(&mut self) {
        self.robot_id = ::std::option::Option::None;
    }

    pub fn has_robot_id(&self) -> bool {
        self.robot_id.is_some()
    }

    // Param is passed by value, moved
    pub fn set_robot_id(&mut self, v: i32) {
        self.robot_id = ::std::option::Option::Some(v);
    }

    // required bool infrared = 2;

    pub fn infrared(&self) -> bool {
        self.infrared.unwrap_or(false)
    }

    pub fn clear_infrared(&mut self) {
        self.infrared = ::std::option::Option::None;
    }

    pub fn has_infrared(&self) -> bool {
        self.infrared.is_some()
    }

    // Param is passed by value, moved
    pub fn set_infrared(&mut self, v: bool) {
        self.infrared = ::std::option::Option::Some(v);
    }

    // required bool flat_kick = 3;

    pub fn flat_kick(&self) -> bool {
        self.flat_kick.unwrap_or(false)
    }

    pub fn clear_flat_kick(&mut self) {
        self.flat_kick = ::std::option::Option::None;
    }

    pub fn has_flat_kick(&self) -> bool {
        self.flat_kick.is_some()
    }

    // Param is passed by value, moved
    pub fn set_flat_kick(&mut self, v: bool) {
        self.flat_kick = ::std::option::Option::Some(v);
    }

    // required bool chip_kick = 4;

    pub fn chip_kick(&self) -> bool {
        self.chip_kick.unwrap_or(false)
    }

    pub fn clear_chip_kick(&mut self) {
        self.chip_kick = ::std::option::Option::None;
    }

    pub fn has_chip_kick(&self) -> bool {
        self.chip_kick.is_some()
    }

    // Param is passed by value, moved
    pub fn set_chip_kick(&mut self, v: bool) {
        self.chip_kick = ::std::option::Option::Some(v);
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(4);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_option_accessor::<_, _>(
            "robot_id",
            |m: &Robot_Status| { &m.robot_id },
            |m: &mut Robot_Status| { &mut m.robot_id },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_option_accessor::<_, _>(
            "infrared",
            |m: &Robot_Status| { &m.infrared },
            |m: &mut Robot_Status| { &mut m.infrared },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_option_accessor::<_, _>(
            "flat_kick",
            |m: &Robot_Status| { &m.flat_kick },
            |m: &mut Robot_Status| { &mut m.flat_kick },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_option_accessor::<_, _>(
            "chip_kick",
            |m: &Robot_Status| { &m.chip_kick },
            |m: &mut Robot_Status| { &mut m.chip_kick },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<Robot_Status>(
            "Robot_Status",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for Robot_Status {
    const NAME: &'static str = "Robot_Status";

    fn is_initialized(&self) -> bool {
        if self.robot_id.is_none() {
            return false;
        }
        if self.infrared.is_none() {
            return false;
        }
        if self.flat_kick.is_none() {
            return false;
        }
        if self.chip_kick.is_none() {
            return false;
        }
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                8 => {
                    self.robot_id = ::std::option::Option::Some(is.read_int32()?);
                },
                16 => {
                    self.infrared = ::std::option::Option::Some(is.read_bool()?);
                },
                24 => {
                    self.flat_kick = ::std::option::Option::Some(is.read_bool()?);
                },
                32 => {
                    self.chip_kick = ::std::option::Option::Some(is.read_bool()?);
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if let Some(v) = self.robot_id {
            my_size += ::protobuf::rt::int32_size(1, v);
        }
        if let Some(v) = self.infrared {
            my_size += 1 + 1;
        }
        if let Some(v) = self.flat_kick {
            my_size += 1 + 1;
        }
        if let Some(v) = self.chip_kick {
            my_size += 1 + 1;
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if let Some(v) = self.robot_id {
            os.write_int32(1, v)?;
        }
        if let Some(v) = self.infrared {
            os.write_bool(2, v)?;
        }
        if let Some(v) = self.flat_kick {
            os.write_bool(3, v)?;
        }
        if let Some(v) = self.chip_kick {
            os.write_bool(4, v)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> Robot_Status {
        Robot_Status::new()
    }

    fn clear(&mut self) {
        self.robot_id = ::std::option::Option::None;
        self.infrared = ::std::option::Option::None;
        self.flat_kick = ::std::option::Option::None;
        self.chip_kick = ::std::option::Option::None;
        self.special_fields.clear();
    }

    fn default_instance() -> &'static Robot_Status {
        static instance: Robot_Status = Robot_Status {
            robot_id: ::std::option::Option::None,
            infrared: ::std::option::Option::None,
            flat_kick: ::std::option::Option::None,
            chip_kick: ::std::option::Option::None,
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for Robot_Status {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("Robot_Status").unwrap()).clone()
    }
}

impl ::std::fmt::Display for Robot_Status {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for Robot_Status {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\x17grSim_Robotstatus.proto\"C\n\rRobots_Status\x122\n\rrobots_status\
    \x18\x01\x20\x03(\x0b2\r.Robot_StatusR\x0crobotsStatus\"\x7f\n\x0cRobot_\
    Status\x12\x19\n\x08robot_id\x18\x01\x20\x02(\x05R\x07robotId\x12\x1a\n\
    \x08infrared\x18\x02\x20\x02(\x08R\x08infrared\x12\x1b\n\tflat_kick\x18\
    \x03\x20\x02(\x08R\x08flatKick\x12\x1b\n\tchip_kick\x18\x04\x20\x02(\x08\
    R\x08chipKickb\x06proto2\
";

/// `FileDescriptorProto` object which was a source for this generated file
fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    static file_descriptor_proto_lazy: ::protobuf::rt::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::Lazy::new();
    file_descriptor_proto_lazy.get(|| {
        ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
    })
}

/// `FileDescriptor` object which allows dynamic access to files
pub fn file_descriptor() -> &'static ::protobuf::reflect::FileDescriptor {
    static generated_file_descriptor_lazy: ::protobuf::rt::Lazy<::protobuf::reflect::GeneratedFileDescriptor> = ::protobuf::rt::Lazy::new();
    static file_descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::FileDescriptor> = ::protobuf::rt::Lazy::new();
    file_descriptor.get(|| {
        let generated_file_descriptor = generated_file_descriptor_lazy.get(|| {
            let mut deps = ::std::vec::Vec::with_capacity(0);
            let mut messages = ::std::vec::Vec::with_capacity(2);
            messages.push(Robots_Status::generated_message_descriptor_data());
            messages.push(Robot_Status::generated_message_descriptor_data());
            let mut enums = ::std::vec::Vec::with_capacity(0);
            ::protobuf::reflect::GeneratedFileDescriptor::new_generated(
                file_descriptor_proto(),
                deps,
                messages,
                enums,
            )
        });
        ::protobuf::reflect::FileDescriptor::new_generated_2(generated_file_descriptor)
    })
}
