// This file is generated by rust-protobuf 3.7.2. Do not edit
// .proto file is parsed by pure
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_results)]
#![allow(unused_mut)]

//! Generated file from `ssl_simulation_robot_control.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_3_7_2;

// @@protoc_insertion_point(message:RobotCommand)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct RobotCommand {
    // message fields
    // @@protoc_insertion_point(field:RobotCommand.id)
    pub id: ::std::option::Option<u32>,
    // @@protoc_insertion_point(field:RobotCommand.move_command)
    pub move_command: ::protobuf::MessageField<RobotMoveCommand>,
    // @@protoc_insertion_point(field:RobotCommand.kick_speed)
    pub kick_speed: ::std::option::Option<f32>,
    // @@protoc_insertion_point(field:RobotCommand.kick_angle)
    pub kick_angle: ::std::option::Option<f32>,
    // @@protoc_insertion_point(field:RobotCommand.dribbler_speed)
    pub dribbler_speed: ::std::option::Option<f32>,
    // special fields
    // @@protoc_insertion_point(special_field:RobotCommand.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a RobotCommand {
    fn default() -> &'a RobotCommand {
        <RobotCommand as ::protobuf::Message>::default_instance()
    }
}

impl RobotCommand {
    pub fn new() -> RobotCommand {
        ::std::default::Default::default()
    }

    // required uint32 id = 1;

    pub fn id(&self) -> u32 {
        self.id.unwrap_or(0)
    }

    pub fn clear_id(&mut self) {
        self.id = ::std::option::Option::None;
    }

    pub fn has_id(&self) -> bool {
        self.id.is_some()
    }

    // Param is passed by value, moved
    pub fn set_id(&mut self, v: u32) {
        self.id = ::std::option::Option::Some(v);
    }

    // optional float kick_speed = 3;

    pub fn kick_speed(&self) -> f32 {
        self.kick_speed.unwrap_or(0.)
    }

    pub fn clear_kick_speed(&mut self) {
        self.kick_speed = ::std::option::Option::None;
    }

    pub fn has_kick_speed(&self) -> bool {
        self.kick_speed.is_some()
    }

    // Param is passed by value, moved
    pub fn set_kick_speed(&mut self, v: f32) {
        self.kick_speed = ::std::option::Option::Some(v);
    }

    // optional float kick_angle = 4;

    pub fn kick_angle(&self) -> f32 {
        self.kick_angle.unwrap_or(0.0f32)
    }

    pub fn clear_kick_angle(&mut self) {
        self.kick_angle = ::std::option::Option::None;
    }

    pub fn has_kick_angle(&self) -> bool {
        self.kick_angle.is_some()
    }

    // Param is passed by value, moved
    pub fn set_kick_angle(&mut self, v: f32) {
        self.kick_angle = ::std::option::Option::Some(v);
    }

    // optional float dribbler_speed = 5;

    pub fn dribbler_speed(&self) -> f32 {
        self.dribbler_speed.unwrap_or(0.)
    }

    pub fn clear_dribbler_speed(&mut self) {
        self.dribbler_speed = ::std::option::Option::None;
    }

    pub fn has_dribbler_speed(&self) -> bool {
        self.dribbler_speed.is_some()
    }

    // Param is passed by value, moved
    pub fn set_dribbler_speed(&mut self, v: f32) {
        self.dribbler_speed = ::std::option::Option::Some(v);
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(5);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_option_accessor::<_, _>(
            "id",
            |m: &RobotCommand| { &m.id },
            |m: &mut RobotCommand| { &mut m.id },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_message_field_accessor::<_, RobotMoveCommand>(
            "move_command",
            |m: &RobotCommand| { &m.move_command },
            |m: &mut RobotCommand| { &mut m.move_command },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_option_accessor::<_, _>(
            "kick_speed",
            |m: &RobotCommand| { &m.kick_speed },
            |m: &mut RobotCommand| { &mut m.kick_speed },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_option_accessor::<_, _>(
            "kick_angle",
            |m: &RobotCommand| { &m.kick_angle },
            |m: &mut RobotCommand| { &mut m.kick_angle },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_option_accessor::<_, _>(
            "dribbler_speed",
            |m: &RobotCommand| { &m.dribbler_speed },
            |m: &mut RobotCommand| { &mut m.dribbler_speed },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<RobotCommand>(
            "RobotCommand",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for RobotCommand {
    const NAME: &'static str = "RobotCommand";

    fn is_initialized(&self) -> bool {
        if self.id.is_none() {
            return false;
        }
        for v in &self.move_command {
            if !v.is_initialized() {
                return false;
            }
        };
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                8 => {
                    self.id = ::std::option::Option::Some(is.read_uint32()?);
                },
                18 => {
                    ::protobuf::rt::read_singular_message_into_field(is, &mut self.move_command)?;
                },
                29 => {
                    self.kick_speed = ::std::option::Option::Some(is.read_float()?);
                },
                37 => {
                    self.kick_angle = ::std::option::Option::Some(is.read_float()?);
                },
                45 => {
                    self.dribbler_speed = ::std::option::Option::Some(is.read_float()?);
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if let Some(v) = self.id {
            my_size += ::protobuf::rt::uint32_size(1, v);
        }
        if let Some(v) = self.move_command.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        }
        if let Some(v) = self.kick_speed {
            my_size += 1 + 4;
        }
        if let Some(v) = self.kick_angle {
            my_size += 1 + 4;
        }
        if let Some(v) = self.dribbler_speed {
            my_size += 1 + 4;
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if let Some(v) = self.id {
            os.write_uint32(1, v)?;
        }
        if let Some(v) = self.move_command.as_ref() {
            ::protobuf::rt::write_message_field_with_cached_size(2, v, os)?;
        }
        if let Some(v) = self.kick_speed {
            os.write_float(3, v)?;
        }
        if let Some(v) = self.kick_angle {
            os.write_float(4, v)?;
        }
        if let Some(v) = self.dribbler_speed {
            os.write_float(5, v)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> RobotCommand {
        RobotCommand::new()
    }

    fn clear(&mut self) {
        self.id = ::std::option::Option::None;
        self.move_command.clear();
        self.kick_speed = ::std::option::Option::None;
        self.kick_angle = ::std::option::Option::None;
        self.dribbler_speed = ::std::option::Option::None;
        self.special_fields.clear();
    }

    fn default_instance() -> &'static RobotCommand {
        static instance: RobotCommand = RobotCommand {
            id: ::std::option::Option::None,
            move_command: ::protobuf::MessageField::none(),
            kick_speed: ::std::option::Option::None,
            kick_angle: ::std::option::Option::None,
            dribbler_speed: ::std::option::Option::None,
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for RobotCommand {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("RobotCommand").unwrap()).clone()
    }
}

impl ::std::fmt::Display for RobotCommand {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for RobotCommand {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

// @@protoc_insertion_point(message:RobotMoveCommand)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct RobotMoveCommand {
    // message oneof groups
    pub command: ::std::option::Option<robot_move_command::Command>,
    // special fields
    // @@protoc_insertion_point(special_field:RobotMoveCommand.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a RobotMoveCommand {
    fn default() -> &'a RobotMoveCommand {
        <RobotMoveCommand as ::protobuf::Message>::default_instance()
    }
}

impl RobotMoveCommand {
    pub fn new() -> RobotMoveCommand {
        ::std::default::Default::default()
    }

    // optional .MoveWheelVelocity wheel_velocity = 1;

    pub fn wheel_velocity(&self) -> &MoveWheelVelocity {
        match self.command {
            ::std::option::Option::Some(robot_move_command::Command::WheelVelocity(ref v)) => v,
            _ => <MoveWheelVelocity as ::protobuf::Message>::default_instance(),
        }
    }

    pub fn clear_wheel_velocity(&mut self) {
        self.command = ::std::option::Option::None;
    }

    pub fn has_wheel_velocity(&self) -> bool {
        match self.command {
            ::std::option::Option::Some(robot_move_command::Command::WheelVelocity(..)) => true,
            _ => false,
        }
    }

    // Param is passed by value, moved
    pub fn set_wheel_velocity(&mut self, v: MoveWheelVelocity) {
        self.command = ::std::option::Option::Some(robot_move_command::Command::WheelVelocity(v))
    }

    // Mutable pointer to the field.
    pub fn mut_wheel_velocity(&mut self) -> &mut MoveWheelVelocity {
        if let ::std::option::Option::Some(robot_move_command::Command::WheelVelocity(_)) = self.command {
        } else {
            self.command = ::std::option::Option::Some(robot_move_command::Command::WheelVelocity(MoveWheelVelocity::new()));
        }
        match self.command {
            ::std::option::Option::Some(robot_move_command::Command::WheelVelocity(ref mut v)) => v,
            _ => panic!(),
        }
    }

    // Take field
    pub fn take_wheel_velocity(&mut self) -> MoveWheelVelocity {
        if self.has_wheel_velocity() {
            match self.command.take() {
                ::std::option::Option::Some(robot_move_command::Command::WheelVelocity(v)) => v,
                _ => panic!(),
            }
        } else {
            MoveWheelVelocity::new()
        }
    }

    // optional .MoveLocalVelocity local_velocity = 2;

    pub fn local_velocity(&self) -> &MoveLocalVelocity {
        match self.command {
            ::std::option::Option::Some(robot_move_command::Command::LocalVelocity(ref v)) => v,
            _ => <MoveLocalVelocity as ::protobuf::Message>::default_instance(),
        }
    }

    pub fn clear_local_velocity(&mut self) {
        self.command = ::std::option::Option::None;
    }

    pub fn has_local_velocity(&self) -> bool {
        match self.command {
            ::std::option::Option::Some(robot_move_command::Command::LocalVelocity(..)) => true,
            _ => false,
        }
    }

    // Param is passed by value, moved
    pub fn set_local_velocity(&mut self, v: MoveLocalVelocity) {
        self.command = ::std::option::Option::Some(robot_move_command::Command::LocalVelocity(v))
    }

    // Mutable pointer to the field.
    pub fn mut_local_velocity(&mut self) -> &mut MoveLocalVelocity {
        if let ::std::option::Option::Some(robot_move_command::Command::LocalVelocity(_)) = self.command {
        } else {
            self.command = ::std::option::Option::Some(robot_move_command::Command::LocalVelocity(MoveLocalVelocity::new()));
        }
        match self.command {
            ::std::option::Option::Some(robot_move_command::Command::LocalVelocity(ref mut v)) => v,
            _ => panic!(),
        }
    }

    // Take field
    pub fn take_local_velocity(&mut self) -> MoveLocalVelocity {
        if self.has_local_velocity() {
            match self.command.take() {
                ::std::option::Option::Some(robot_move_command::Command::LocalVelocity(v)) => v,
                _ => panic!(),
            }
        } else {
            MoveLocalVelocity::new()
        }
    }

    // optional .MoveGlobalVelocity global_velocity = 3;

    pub fn global_velocity(&self) -> &MoveGlobalVelocity {
        match self.command {
            ::std::option::Option::Some(robot_move_command::Command::GlobalVelocity(ref v)) => v,
            _ => <MoveGlobalVelocity as ::protobuf::Message>::default_instance(),
        }
    }

    pub fn clear_global_velocity(&mut self) {
        self.command = ::std::option::Option::None;
    }

    pub fn has_global_velocity(&self) -> bool {
        match self.command {
            ::std::option::Option::Some(robot_move_command::Command::GlobalVelocity(..)) => true,
            _ => false,
        }
    }

    // Param is passed by value, moved
    pub fn set_global_velocity(&mut self, v: MoveGlobalVelocity) {
        self.command = ::std::option::Option::Some(robot_move_command::Command::GlobalVelocity(v))
    }

    // Mutable pointer to the field.
    pub fn mut_global_velocity(&mut self) -> &mut MoveGlobalVelocity {
        if let ::std::option::Option::Some(robot_move_command::Command::GlobalVelocity(_)) = self.command {
        } else {
            self.command = ::std::option::Option::Some(robot_move_command::Command::GlobalVelocity(MoveGlobalVelocity::new()));
        }
        match self.command {
            ::std::option::Option::Some(robot_move_command::Command::GlobalVelocity(ref mut v)) => v,
            _ => panic!(),
        }
    }

    // Take field
    pub fn take_global_velocity(&mut self) -> MoveGlobalVelocity {
        if self.has_global_velocity() {
            match self.command.take() {
                ::std::option::Option::Some(robot_move_command::Command::GlobalVelocity(v)) => v,
                _ => panic!(),
            }
        } else {
            MoveGlobalVelocity::new()
        }
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(3);
        let mut oneofs = ::std::vec::Vec::with_capacity(1);
        fields.push(::protobuf::reflect::rt::v2::make_oneof_message_has_get_mut_set_accessor::<_, MoveWheelVelocity>(
            "wheel_velocity",
            RobotMoveCommand::has_wheel_velocity,
            RobotMoveCommand::wheel_velocity,
            RobotMoveCommand::mut_wheel_velocity,
            RobotMoveCommand::set_wheel_velocity,
        ));
        fields.push(::protobuf::reflect::rt::v2::make_oneof_message_has_get_mut_set_accessor::<_, MoveLocalVelocity>(
            "local_velocity",
            RobotMoveCommand::has_local_velocity,
            RobotMoveCommand::local_velocity,
            RobotMoveCommand::mut_local_velocity,
            RobotMoveCommand::set_local_velocity,
        ));
        fields.push(::protobuf::reflect::rt::v2::make_oneof_message_has_get_mut_set_accessor::<_, MoveGlobalVelocity>(
            "global_velocity",
            RobotMoveCommand::has_global_velocity,
            RobotMoveCommand::global_velocity,
            RobotMoveCommand::mut_global_velocity,
            RobotMoveCommand::set_global_velocity,
        ));
        oneofs.push(robot_move_command::Command::generated_oneof_descriptor_data());
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<RobotMoveCommand>(
            "RobotMoveCommand",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for RobotMoveCommand {
    const NAME: &'static str = "RobotMoveCommand";

    fn is_initialized(&self) -> bool {
        if let Some(robot_move_command::Command::WheelVelocity(ref v)) = self.command {
            if !v.is_initialized() {
                return false;
            }
        }
        if let Some(robot_move_command::Command::LocalVelocity(ref v)) = self.command {
            if !v.is_initialized() {
                return false;
            }
        }
        if let Some(robot_move_command::Command::GlobalVelocity(ref v)) = self.command {
            if !v.is_initialized() {
                return false;
            }
        }
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                10 => {
                    self.command = ::std::option::Option::Some(robot_move_command::Command::WheelVelocity(is.read_message()?));
                },
                18 => {
                    self.command = ::std::option::Option::Some(robot_move_command::Command::LocalVelocity(is.read_message()?));
                },
                26 => {
                    self.command = ::std::option::Option::Some(robot_move_command::Command::GlobalVelocity(is.read_message()?));
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if let ::std::option::Option::Some(ref v) = self.command {
            match v {
                &robot_move_command::Command::WheelVelocity(ref v) => {
                    let len = v.compute_size();
                    my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
                },
                &robot_move_command::Command::LocalVelocity(ref v) => {
                    let len = v.compute_size();
                    my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
                },
                &robot_move_command::Command::GlobalVelocity(ref v) => {
                    let len = v.compute_size();
                    my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
                },
            };
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if let ::std::option::Option::Some(ref v) = self.command {
            match v {
                &robot_move_command::Command::WheelVelocity(ref v) => {
                    ::protobuf::rt::write_message_field_with_cached_size(1, v, os)?;
                },
                &robot_move_command::Command::LocalVelocity(ref v) => {
                    ::protobuf::rt::write_message_field_with_cached_size(2, v, os)?;
                },
                &robot_move_command::Command::GlobalVelocity(ref v) => {
                    ::protobuf::rt::write_message_field_with_cached_size(3, v, os)?;
                },
            };
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> RobotMoveCommand {
        RobotMoveCommand::new()
    }

    fn clear(&mut self) {
        self.command = ::std::option::Option::None;
        self.command = ::std::option::Option::None;
        self.command = ::std::option::Option::None;
        self.special_fields.clear();
    }

    fn default_instance() -> &'static RobotMoveCommand {
        static instance: RobotMoveCommand = RobotMoveCommand {
            command: ::std::option::Option::None,
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for RobotMoveCommand {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("RobotMoveCommand").unwrap()).clone()
    }
}

impl ::std::fmt::Display for RobotMoveCommand {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for RobotMoveCommand {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

/// Nested message and enums of message `RobotMoveCommand`
pub mod robot_move_command {

    #[derive(Clone,PartialEq,Debug)]
    #[non_exhaustive]
    // @@protoc_insertion_point(oneof:RobotMoveCommand.command)
    pub enum Command {
        // @@protoc_insertion_point(oneof_field:RobotMoveCommand.wheel_velocity)
        WheelVelocity(super::MoveWheelVelocity),
        // @@protoc_insertion_point(oneof_field:RobotMoveCommand.local_velocity)
        LocalVelocity(super::MoveLocalVelocity),
        // @@protoc_insertion_point(oneof_field:RobotMoveCommand.global_velocity)
        GlobalVelocity(super::MoveGlobalVelocity),
    }

    impl ::protobuf::Oneof for Command {
    }

    impl ::protobuf::OneofFull for Command {
        fn descriptor() -> ::protobuf::reflect::OneofDescriptor {
            static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::OneofDescriptor> = ::protobuf::rt::Lazy::new();
            descriptor.get(|| <super::RobotMoveCommand as ::protobuf::MessageFull>::descriptor().oneof_by_name("command").unwrap()).clone()
        }
    }

    impl Command {
        pub(in super) fn generated_oneof_descriptor_data() -> ::protobuf::reflect::GeneratedOneofDescriptorData {
            ::protobuf::reflect::GeneratedOneofDescriptorData::new::<Command>("command")
        }
    }
}

// @@protoc_insertion_point(message:MoveWheelVelocity)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct MoveWheelVelocity {
    // message fields
    // @@protoc_insertion_point(field:MoveWheelVelocity.front_right)
    pub front_right: ::std::option::Option<f32>,
    // @@protoc_insertion_point(field:MoveWheelVelocity.back_right)
    pub back_right: ::std::option::Option<f32>,
    // @@protoc_insertion_point(field:MoveWheelVelocity.back_left)
    pub back_left: ::std::option::Option<f32>,
    // @@protoc_insertion_point(field:MoveWheelVelocity.front_left)
    pub front_left: ::std::option::Option<f32>,
    // special fields
    // @@protoc_insertion_point(special_field:MoveWheelVelocity.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a MoveWheelVelocity {
    fn default() -> &'a MoveWheelVelocity {
        <MoveWheelVelocity as ::protobuf::Message>::default_instance()
    }
}

impl MoveWheelVelocity {
    pub fn new() -> MoveWheelVelocity {
        ::std::default::Default::default()
    }

    // required float front_right = 1;

    pub fn front_right(&self) -> f32 {
        self.front_right.unwrap_or(0.)
    }

    pub fn clear_front_right(&mut self) {
        self.front_right = ::std::option::Option::None;
    }

    pub fn has_front_right(&self) -> bool {
        self.front_right.is_some()
    }

    // Param is passed by value, moved
    pub fn set_front_right(&mut self, v: f32) {
        self.front_right = ::std::option::Option::Some(v);
    }

    // required float back_right = 2;

    pub fn back_right(&self) -> f32 {
        self.back_right.unwrap_or(0.)
    }

    pub fn clear_back_right(&mut self) {
        self.back_right = ::std::option::Option::None;
    }

    pub fn has_back_right(&self) -> bool {
        self.back_right.is_some()
    }

    // Param is passed by value, moved
    pub fn set_back_right(&mut self, v: f32) {
        self.back_right = ::std::option::Option::Some(v);
    }

    // required float back_left = 3;

    pub fn back_left(&self) -> f32 {
        self.back_left.unwrap_or(0.)
    }

    pub fn clear_back_left(&mut self) {
        self.back_left = ::std::option::Option::None;
    }

    pub fn has_back_left(&self) -> bool {
        self.back_left.is_some()
    }

    // Param is passed by value, moved
    pub fn set_back_left(&mut self, v: f32) {
        self.back_left = ::std::option::Option::Some(v);
    }

    // required float front_left = 4;

    pub fn front_left(&self) -> f32 {
        self.front_left.unwrap_or(0.)
    }

    pub fn clear_front_left(&mut self) {
        self.front_left = ::std::option::Option::None;
    }

    pub fn has_front_left(&self) -> bool {
        self.front_left.is_some()
    }

    // Param is passed by value, moved
    pub fn set_front_left(&mut self, v: f32) {
        self.front_left = ::std::option::Option::Some(v);
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(4);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_option_accessor::<_, _>(
            "front_right",
            |m: &MoveWheelVelocity| { &m.front_right },
            |m: &mut MoveWheelVelocity| { &mut m.front_right },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_option_accessor::<_, _>(
            "back_right",
            |m: &MoveWheelVelocity| { &m.back_right },
            |m: &mut MoveWheelVelocity| { &mut m.back_right },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_option_accessor::<_, _>(
            "back_left",
            |m: &MoveWheelVelocity| { &m.back_left },
            |m: &mut MoveWheelVelocity| { &mut m.back_left },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_option_accessor::<_, _>(
            "front_left",
            |m: &MoveWheelVelocity| { &m.front_left },
            |m: &mut MoveWheelVelocity| { &mut m.front_left },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<MoveWheelVelocity>(
            "MoveWheelVelocity",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for MoveWheelVelocity {
    const NAME: &'static str = "MoveWheelVelocity";

    fn is_initialized(&self) -> bool {
        if self.front_right.is_none() {
            return false;
        }
        if self.back_right.is_none() {
            return false;
        }
        if self.back_left.is_none() {
            return false;
        }
        if self.front_left.is_none() {
            return false;
        }
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                13 => {
                    self.front_right = ::std::option::Option::Some(is.read_float()?);
                },
                21 => {
                    self.back_right = ::std::option::Option::Some(is.read_float()?);
                },
                29 => {
                    self.back_left = ::std::option::Option::Some(is.read_float()?);
                },
                37 => {
                    self.front_left = ::std::option::Option::Some(is.read_float()?);
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if let Some(v) = self.front_right {
            my_size += 1 + 4;
        }
        if let Some(v) = self.back_right {
            my_size += 1 + 4;
        }
        if let Some(v) = self.back_left {
            my_size += 1 + 4;
        }
        if let Some(v) = self.front_left {
            my_size += 1 + 4;
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if let Some(v) = self.front_right {
            os.write_float(1, v)?;
        }
        if let Some(v) = self.back_right {
            os.write_float(2, v)?;
        }
        if let Some(v) = self.back_left {
            os.write_float(3, v)?;
        }
        if let Some(v) = self.front_left {
            os.write_float(4, v)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> MoveWheelVelocity {
        MoveWheelVelocity::new()
    }

    fn clear(&mut self) {
        self.front_right = ::std::option::Option::None;
        self.back_right = ::std::option::Option::None;
        self.back_left = ::std::option::Option::None;
        self.front_left = ::std::option::Option::None;
        self.special_fields.clear();
    }

    fn default_instance() -> &'static MoveWheelVelocity {
        static instance: MoveWheelVelocity = MoveWheelVelocity {
            front_right: ::std::option::Option::None,
            back_right: ::std::option::Option::None,
            back_left: ::std::option::Option::None,
            front_left: ::std::option::Option::None,
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for MoveWheelVelocity {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("MoveWheelVelocity").unwrap()).clone()
    }
}

impl ::std::fmt::Display for MoveWheelVelocity {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for MoveWheelVelocity {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

// @@protoc_insertion_point(message:MoveLocalVelocity)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct MoveLocalVelocity {
    // message fields
    // @@protoc_insertion_point(field:MoveLocalVelocity.forward)
    pub forward: ::std::option::Option<f32>,
    // @@protoc_insertion_point(field:MoveLocalVelocity.left)
    pub left: ::std::option::Option<f32>,
    // @@protoc_insertion_point(field:MoveLocalVelocity.angular)
    pub angular: ::std::option::Option<f32>,
    // special fields
    // @@protoc_insertion_point(special_field:MoveLocalVelocity.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a MoveLocalVelocity {
    fn default() -> &'a MoveLocalVelocity {
        <MoveLocalVelocity as ::protobuf::Message>::default_instance()
    }
}

impl MoveLocalVelocity {
    pub fn new() -> MoveLocalVelocity {
        ::std::default::Default::default()
    }

    // required float forward = 1;

    pub fn forward(&self) -> f32 {
        self.forward.unwrap_or(0.)
    }

    pub fn clear_forward(&mut self) {
        self.forward = ::std::option::Option::None;
    }

    pub fn has_forward(&self) -> bool {
        self.forward.is_some()
    }

    // Param is passed by value, moved
    pub fn set_forward(&mut self, v: f32) {
        self.forward = ::std::option::Option::Some(v);
    }

    // required float left = 2;

    pub fn left(&self) -> f32 {
        self.left.unwrap_or(0.)
    }

    pub fn clear_left(&mut self) {
        self.left = ::std::option::Option::None;
    }

    pub fn has_left(&self) -> bool {
        self.left.is_some()
    }

    // Param is passed by value, moved
    pub fn set_left(&mut self, v: f32) {
        self.left = ::std::option::Option::Some(v);
    }

    // required float angular = 3;

    pub fn angular(&self) -> f32 {
        self.angular.unwrap_or(0.)
    }

    pub fn clear_angular(&mut self) {
        self.angular = ::std::option::Option::None;
    }

    pub fn has_angular(&self) -> bool {
        self.angular.is_some()
    }

    // Param is passed by value, moved
    pub fn set_angular(&mut self, v: f32) {
        self.angular = ::std::option::Option::Some(v);
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(3);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_option_accessor::<_, _>(
            "forward",
            |m: &MoveLocalVelocity| { &m.forward },
            |m: &mut MoveLocalVelocity| { &mut m.forward },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_option_accessor::<_, _>(
            "left",
            |m: &MoveLocalVelocity| { &m.left },
            |m: &mut MoveLocalVelocity| { &mut m.left },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_option_accessor::<_, _>(
            "angular",
            |m: &MoveLocalVelocity| { &m.angular },
            |m: &mut MoveLocalVelocity| { &mut m.angular },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<MoveLocalVelocity>(
            "MoveLocalVelocity",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for MoveLocalVelocity {
    const NAME: &'static str = "MoveLocalVelocity";

    fn is_initialized(&self) -> bool {
        if self.forward.is_none() {
            return false;
        }
        if self.left.is_none() {
            return false;
        }
        if self.angular.is_none() {
            return false;
        }
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                13 => {
                    self.forward = ::std::option::Option::Some(is.read_float()?);
                },
                21 => {
                    self.left = ::std::option::Option::Some(is.read_float()?);
                },
                29 => {
                    self.angular = ::std::option::Option::Some(is.read_float()?);
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if let Some(v) = self.forward {
            my_size += 1 + 4;
        }
        if let Some(v) = self.left {
            my_size += 1 + 4;
        }
        if let Some(v) = self.angular {
            my_size += 1 + 4;
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if let Some(v) = self.forward {
            os.write_float(1, v)?;
        }
        if let Some(v) = self.left {
            os.write_float(2, v)?;
        }
        if let Some(v) = self.angular {
            os.write_float(3, v)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> MoveLocalVelocity {
        MoveLocalVelocity::new()
    }

    fn clear(&mut self) {
        self.forward = ::std::option::Option::None;
        self.left = ::std::option::Option::None;
        self.angular = ::std::option::Option::None;
        self.special_fields.clear();
    }

    fn default_instance() -> &'static MoveLocalVelocity {
        static instance: MoveLocalVelocity = MoveLocalVelocity {
            forward: ::std::option::Option::None,
            left: ::std::option::Option::None,
            angular: ::std::option::Option::None,
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for MoveLocalVelocity {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("MoveLocalVelocity").unwrap()).clone()
    }
}

impl ::std::fmt::Display for MoveLocalVelocity {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for MoveLocalVelocity {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

// @@protoc_insertion_point(message:MoveGlobalVelocity)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct MoveGlobalVelocity {
    // message fields
    // @@protoc_insertion_point(field:MoveGlobalVelocity.x)
    pub x: ::std::option::Option<f32>,
    // @@protoc_insertion_point(field:MoveGlobalVelocity.y)
    pub y: ::std::option::Option<f32>,
    // @@protoc_insertion_point(field:MoveGlobalVelocity.angular)
    pub angular: ::std::option::Option<f32>,
    // special fields
    // @@protoc_insertion_point(special_field:MoveGlobalVelocity.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a MoveGlobalVelocity {
    fn default() -> &'a MoveGlobalVelocity {
        <MoveGlobalVelocity as ::protobuf::Message>::default_instance()
    }
}

impl MoveGlobalVelocity {
    pub fn new() -> MoveGlobalVelocity {
        ::std::default::Default::default()
    }

    // required float x = 1;

    pub fn x(&self) -> f32 {
        self.x.unwrap_or(0.)
    }

    pub fn clear_x(&mut self) {
        self.x = ::std::option::Option::None;
    }

    pub fn has_x(&self) -> bool {
        self.x.is_some()
    }

    // Param is passed by value, moved
    pub fn set_x(&mut self, v: f32) {
        self.x = ::std::option::Option::Some(v);
    }

    // required float y = 2;

    pub fn y(&self) -> f32 {
        self.y.unwrap_or(0.)
    }

    pub fn clear_y(&mut self) {
        self.y = ::std::option::Option::None;
    }

    pub fn has_y(&self) -> bool {
        self.y.is_some()
    }

    // Param is passed by value, moved
    pub fn set_y(&mut self, v: f32) {
        self.y = ::std::option::Option::Some(v);
    }

    // required float angular = 3;

    pub fn angular(&self) -> f32 {
        self.angular.unwrap_or(0.)
    }

    pub fn clear_angular(&mut self) {
        self.angular = ::std::option::Option::None;
    }

    pub fn has_angular(&self) -> bool {
        self.angular.is_some()
    }

    // Param is passed by value, moved
    pub fn set_angular(&mut self, v: f32) {
        self.angular = ::std::option::Option::Some(v);
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(3);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_option_accessor::<_, _>(
            "x",
            |m: &MoveGlobalVelocity| { &m.x },
            |m: &mut MoveGlobalVelocity| { &mut m.x },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_option_accessor::<_, _>(
            "y",
            |m: &MoveGlobalVelocity| { &m.y },
            |m: &mut MoveGlobalVelocity| { &mut m.y },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_option_accessor::<_, _>(
            "angular",
            |m: &MoveGlobalVelocity| { &m.angular },
            |m: &mut MoveGlobalVelocity| { &mut m.angular },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<MoveGlobalVelocity>(
            "MoveGlobalVelocity",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for MoveGlobalVelocity {
    const NAME: &'static str = "MoveGlobalVelocity";

    fn is_initialized(&self) -> bool {
        if self.x.is_none() {
            return false;
        }
        if self.y.is_none() {
            return false;
        }
        if self.angular.is_none() {
            return false;
        }
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                13 => {
                    self.x = ::std::option::Option::Some(is.read_float()?);
                },
                21 => {
                    self.y = ::std::option::Option::Some(is.read_float()?);
                },
                29 => {
                    self.angular = ::std::option::Option::Some(is.read_float()?);
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if let Some(v) = self.x {
            my_size += 1 + 4;
        }
        if let Some(v) = self.y {
            my_size += 1 + 4;
        }
        if let Some(v) = self.angular {
            my_size += 1 + 4;
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if let Some(v) = self.x {
            os.write_float(1, v)?;
        }
        if let Some(v) = self.y {
            os.write_float(2, v)?;
        }
        if let Some(v) = self.angular {
            os.write_float(3, v)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> MoveGlobalVelocity {
        MoveGlobalVelocity::new()
    }

    fn clear(&mut self) {
        self.x = ::std::option::Option::None;
        self.y = ::std::option::Option::None;
        self.angular = ::std::option::Option::None;
        self.special_fields.clear();
    }

    fn default_instance() -> &'static MoveGlobalVelocity {
        static instance: MoveGlobalVelocity = MoveGlobalVelocity {
            x: ::std::option::Option::None,
            y: ::std::option::Option::None,
            angular: ::std::option::Option::None,
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for MoveGlobalVelocity {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("MoveGlobalVelocity").unwrap()).clone()
    }
}

impl ::std::fmt::Display for MoveGlobalVelocity {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for MoveGlobalVelocity {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

// @@protoc_insertion_point(message:RobotControl)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct RobotControl {
    // message fields
    // @@protoc_insertion_point(field:RobotControl.robot_commands)
    pub robot_commands: ::std::vec::Vec<RobotCommand>,
    // special fields
    // @@protoc_insertion_point(special_field:RobotControl.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a RobotControl {
    fn default() -> &'a RobotControl {
        <RobotControl as ::protobuf::Message>::default_instance()
    }
}

impl RobotControl {
    pub fn new() -> RobotControl {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(1);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_vec_simpler_accessor::<_, _>(
            "robot_commands",
            |m: &RobotControl| { &m.robot_commands },
            |m: &mut RobotControl| { &mut m.robot_commands },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<RobotControl>(
            "RobotControl",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for RobotControl {
    const NAME: &'static str = "RobotControl";

    fn is_initialized(&self) -> bool {
        for v in &self.robot_commands {
            if !v.is_initialized() {
                return false;
            }
        };
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                10 => {
                    self.robot_commands.push(is.read_message()?);
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        for value in &self.robot_commands {
            let len = value.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        };
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        for v in &self.robot_commands {
            ::protobuf::rt::write_message_field_with_cached_size(1, v, os)?;
        };
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> RobotControl {
        RobotControl::new()
    }

    fn clear(&mut self) {
        self.robot_commands.clear();
        self.special_fields.clear();
    }

    fn default_instance() -> &'static RobotControl {
        static instance: RobotControl = RobotControl {
            robot_commands: ::std::vec::Vec::new(),
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for RobotControl {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("RobotControl").unwrap()).clone()
    }
}

impl ::std::fmt::Display for RobotControl {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for RobotControl {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\"ssl_simulation_robot_control.proto\"\xbe\x01\n\x0cRobotCommand\x12\
    \x0e\n\x02id\x18\x01\x20\x02(\rR\x02id\x124\n\x0cmove_command\x18\x02\
    \x20\x01(\x0b2\x11.RobotMoveCommandR\x0bmoveCommand\x12\x1d\n\nkick_spee\
    d\x18\x03\x20\x01(\x02R\tkickSpeed\x12\"\n\nkick_angle\x18\x04\x20\x01(\
    \x02:\x010R\tkickAngleB\0\x12%\n\x0edribbler_speed\x18\x05\x20\x01(\x02R\
    \rdribblerSpeed\"\xd7\x01\n\x10RobotMoveCommand\x12;\n\x0ewheel_velocity\
    \x18\x01\x20\x01(\x0b2\x12.MoveWheelVelocityH\0R\rwheelVelocity\x12;\n\
    \x0elocal_velocity\x18\x02\x20\x01(\x0b2\x12.MoveLocalVelocityH\0R\rloca\
    lVelocity\x12>\n\x0fglobal_velocity\x18\x03\x20\x01(\x0b2\x13.MoveGlobal\
    VelocityH\0R\x0eglobalVelocityB\t\n\x07command\"\x8f\x01\n\x11MoveWheelV\
    elocity\x12\x1f\n\x0bfront_right\x18\x01\x20\x02(\x02R\nfrontRight\x12\
    \x1d\n\nback_right\x18\x02\x20\x02(\x02R\tbackRight\x12\x1b\n\tback_left\
    \x18\x03\x20\x02(\x02R\x08backLeft\x12\x1d\n\nfront_left\x18\x04\x20\x02\
    (\x02R\tfrontLeft\"[\n\x11MoveLocalVelocity\x12\x18\n\x07forward\x18\x01\
    \x20\x02(\x02R\x07forward\x12\x12\n\x04left\x18\x02\x20\x02(\x02R\x04lef\
    t\x12\x18\n\x07angular\x18\x03\x20\x02(\x02R\x07angular\"J\n\x12MoveGlob\
    alVelocity\x12\x0c\n\x01x\x18\x01\x20\x02(\x02R\x01x\x12\x0c\n\x01y\x18\
    \x02\x20\x02(\x02R\x01y\x12\x18\n\x07angular\x18\x03\x20\x02(\x02R\x07an\
    gular\"D\n\x0cRobotControl\x124\n\x0erobot_commands\x18\x01\x20\x03(\x0b\
    2\r.RobotCommandR\rrobotCommandsB8Z6github.com/RoboCup-SSL/ssl-simulatio\
    n-protocol/pkg/simb\x06proto2\
";

/// `FileDescriptorProto` object which was a source for this generated file
fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    static file_descriptor_proto_lazy: ::protobuf::rt::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::Lazy::new();
    file_descriptor_proto_lazy.get(|| {
        ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
    })
}

/// `FileDescriptor` object which allows dynamic access to files
pub fn file_descriptor() -> &'static ::protobuf::reflect::FileDescriptor {
    static generated_file_descriptor_lazy: ::protobuf::rt::Lazy<::protobuf::reflect::GeneratedFileDescriptor> = ::protobuf::rt::Lazy::new();
    static file_descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::FileDescriptor> = ::protobuf::rt::Lazy::new();
    file_descriptor.get(|| {
        let generated_file_descriptor = generated_file_descriptor_lazy.get(|| {
            let mut deps = ::std::vec::Vec::with_capacity(0);
            let mut messages = ::std::vec::Vec::with_capacity(6);
            messages.push(RobotCommand::generated_message_descriptor_data());
            messages.push(RobotMoveCommand::generated_message_descriptor_data());
            messages.push(MoveWheelVelocity::generated_message_descriptor_data());
            messages.push(MoveLocalVelocity::generated_message_descriptor_data());
            messages.push(MoveGlobalVelocity::generated_message_descriptor_data());
            messages.push(RobotControl::generated_message_descriptor_data());
            let mut enums = ::std::vec::Vec::with_capacity(0);
            ::protobuf::reflect::GeneratedFileDescriptor::new_generated(
                file_descriptor_proto(),
                deps,
                messages,
                enums,
            )
        });
        ::protobuf::reflect::FileDescriptor::new_generated_2(generated_file_descriptor)
    })
}
