// This file is generated by rust-protobuf 3.7.2. Do not edit
// .proto file is parsed by pure
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_results)]
#![allow(unused_mut)]

//! Generated file from `ssl_gc_api.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_3_7_2;

// @@protoc_insertion_point(message:Output)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct Output {
    // message fields
    // @@protoc_insertion_point(field:Output.match_state)
    pub match_state: ::protobuf::MessageField<super::ssl_gc_state::State>,
    // @@protoc_insertion_point(field:Output.gc_state)
    pub gc_state: ::protobuf::MessageField<super::ssl_gc_engine::GcState>,
    // @@protoc_insertion_point(field:Output.protocol)
    pub protocol: ::protobuf::MessageField<Protocol>,
    // @@protoc_insertion_point(field:Output.config)
    pub config: ::protobuf::MessageField<super::ssl_gc_engine_config::Config>,
    // special fields
    // @@protoc_insertion_point(special_field:Output.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a Output {
    fn default() -> &'a Output {
        <Output as ::protobuf::Message>::default_instance()
    }
}

impl Output {
    pub fn new() -> Output {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(4);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_message_field_accessor::<_, super::ssl_gc_state::State>(
            "match_state",
            |m: &Output| { &m.match_state },
            |m: &mut Output| { &mut m.match_state },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_message_field_accessor::<_, super::ssl_gc_engine::GcState>(
            "gc_state",
            |m: &Output| { &m.gc_state },
            |m: &mut Output| { &mut m.gc_state },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_message_field_accessor::<_, Protocol>(
            "protocol",
            |m: &Output| { &m.protocol },
            |m: &mut Output| { &mut m.protocol },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_message_field_accessor::<_, super::ssl_gc_engine_config::Config>(
            "config",
            |m: &Output| { &m.config },
            |m: &mut Output| { &mut m.config },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<Output>(
            "Output",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for Output {
    const NAME: &'static str = "Output";

    fn is_initialized(&self) -> bool {
        for v in &self.match_state {
            if !v.is_initialized() {
                return false;
            }
        };
        for v in &self.gc_state {
            if !v.is_initialized() {
                return false;
            }
        };
        for v in &self.protocol {
            if !v.is_initialized() {
                return false;
            }
        };
        for v in &self.config {
            if !v.is_initialized() {
                return false;
            }
        };
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                10 => {
                    ::protobuf::rt::read_singular_message_into_field(is, &mut self.match_state)?;
                },
                18 => {
                    ::protobuf::rt::read_singular_message_into_field(is, &mut self.gc_state)?;
                },
                26 => {
                    ::protobuf::rt::read_singular_message_into_field(is, &mut self.protocol)?;
                },
                34 => {
                    ::protobuf::rt::read_singular_message_into_field(is, &mut self.config)?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if let Some(v) = self.match_state.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        }
        if let Some(v) = self.gc_state.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        }
        if let Some(v) = self.protocol.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        }
        if let Some(v) = self.config.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if let Some(v) = self.match_state.as_ref() {
            ::protobuf::rt::write_message_field_with_cached_size(1, v, os)?;
        }
        if let Some(v) = self.gc_state.as_ref() {
            ::protobuf::rt::write_message_field_with_cached_size(2, v, os)?;
        }
        if let Some(v) = self.protocol.as_ref() {
            ::protobuf::rt::write_message_field_with_cached_size(3, v, os)?;
        }
        if let Some(v) = self.config.as_ref() {
            ::protobuf::rt::write_message_field_with_cached_size(4, v, os)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> Output {
        Output::new()
    }

    fn clear(&mut self) {
        self.match_state.clear();
        self.gc_state.clear();
        self.protocol.clear();
        self.config.clear();
        self.special_fields.clear();
    }

    fn default_instance() -> &'static Output {
        static instance: Output = Output {
            match_state: ::protobuf::MessageField::none(),
            gc_state: ::protobuf::MessageField::none(),
            protocol: ::protobuf::MessageField::none(),
            config: ::protobuf::MessageField::none(),
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for Output {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("Output").unwrap()).clone()
    }
}

impl ::std::fmt::Display for Output {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for Output {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

// @@protoc_insertion_point(message:Protocol)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct Protocol {
    // message fields
    // @@protoc_insertion_point(field:Protocol.delta)
    pub delta: ::std::option::Option<bool>,
    // @@protoc_insertion_point(field:Protocol.entry)
    pub entry: ::std::vec::Vec<ProtocolEntry>,
    // special fields
    // @@protoc_insertion_point(special_field:Protocol.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a Protocol {
    fn default() -> &'a Protocol {
        <Protocol as ::protobuf::Message>::default_instance()
    }
}

impl Protocol {
    pub fn new() -> Protocol {
        ::std::default::Default::default()
    }

    // optional bool delta = 1;

    pub fn delta(&self) -> bool {
        self.delta.unwrap_or(false)
    }

    pub fn clear_delta(&mut self) {
        self.delta = ::std::option::Option::None;
    }

    pub fn has_delta(&self) -> bool {
        self.delta.is_some()
    }

    // Param is passed by value, moved
    pub fn set_delta(&mut self, v: bool) {
        self.delta = ::std::option::Option::Some(v);
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(2);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_option_accessor::<_, _>(
            "delta",
            |m: &Protocol| { &m.delta },
            |m: &mut Protocol| { &mut m.delta },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_vec_simpler_accessor::<_, _>(
            "entry",
            |m: &Protocol| { &m.entry },
            |m: &mut Protocol| { &mut m.entry },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<Protocol>(
            "Protocol",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for Protocol {
    const NAME: &'static str = "Protocol";

    fn is_initialized(&self) -> bool {
        for v in &self.entry {
            if !v.is_initialized() {
                return false;
            }
        };
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                8 => {
                    self.delta = ::std::option::Option::Some(is.read_bool()?);
                },
                18 => {
                    self.entry.push(is.read_message()?);
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if let Some(v) = self.delta {
            my_size += 1 + 1;
        }
        for value in &self.entry {
            let len = value.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        };
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if let Some(v) = self.delta {
            os.write_bool(1, v)?;
        }
        for v in &self.entry {
            ::protobuf::rt::write_message_field_with_cached_size(2, v, os)?;
        };
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> Protocol {
        Protocol::new()
    }

    fn clear(&mut self) {
        self.delta = ::std::option::Option::None;
        self.entry.clear();
        self.special_fields.clear();
    }

    fn default_instance() -> &'static Protocol {
        static instance: Protocol = Protocol {
            delta: ::std::option::Option::None,
            entry: ::std::vec::Vec::new(),
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for Protocol {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("Protocol").unwrap()).clone()
    }
}

impl ::std::fmt::Display for Protocol {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for Protocol {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

// @@protoc_insertion_point(message:ProtocolEntry)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct ProtocolEntry {
    // message fields
    // @@protoc_insertion_point(field:ProtocolEntry.id)
    pub id: ::std::option::Option<i32>,
    // @@protoc_insertion_point(field:ProtocolEntry.change)
    pub change: ::protobuf::MessageField<super::ssl_gc_change::Change>,
    // @@protoc_insertion_point(field:ProtocolEntry.match_time_elapsed)
    pub match_time_elapsed: ::protobuf::MessageField<::protobuf::well_known_types::duration::Duration>,
    // @@protoc_insertion_point(field:ProtocolEntry.stage_time_elapsed)
    pub stage_time_elapsed: ::protobuf::MessageField<::protobuf::well_known_types::duration::Duration>,
    // special fields
    // @@protoc_insertion_point(special_field:ProtocolEntry.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a ProtocolEntry {
    fn default() -> &'a ProtocolEntry {
        <ProtocolEntry as ::protobuf::Message>::default_instance()
    }
}

impl ProtocolEntry {
    pub fn new() -> ProtocolEntry {
        ::std::default::Default::default()
    }

    // optional int32 id = 1;

    pub fn id(&self) -> i32 {
        self.id.unwrap_or(0)
    }

    pub fn clear_id(&mut self) {
        self.id = ::std::option::Option::None;
    }

    pub fn has_id(&self) -> bool {
        self.id.is_some()
    }

    // Param is passed by value, moved
    pub fn set_id(&mut self, v: i32) {
        self.id = ::std::option::Option::Some(v);
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(4);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_option_accessor::<_, _>(
            "id",
            |m: &ProtocolEntry| { &m.id },
            |m: &mut ProtocolEntry| { &mut m.id },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_message_field_accessor::<_, super::ssl_gc_change::Change>(
            "change",
            |m: &ProtocolEntry| { &m.change },
            |m: &mut ProtocolEntry| { &mut m.change },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_message_field_accessor::<_, ::protobuf::well_known_types::duration::Duration>(
            "match_time_elapsed",
            |m: &ProtocolEntry| { &m.match_time_elapsed },
            |m: &mut ProtocolEntry| { &mut m.match_time_elapsed },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_message_field_accessor::<_, ::protobuf::well_known_types::duration::Duration>(
            "stage_time_elapsed",
            |m: &ProtocolEntry| { &m.stage_time_elapsed },
            |m: &mut ProtocolEntry| { &mut m.stage_time_elapsed },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<ProtocolEntry>(
            "ProtocolEntry",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for ProtocolEntry {
    const NAME: &'static str = "ProtocolEntry";

    fn is_initialized(&self) -> bool {
        for v in &self.change {
            if !v.is_initialized() {
                return false;
            }
        };
        for v in &self.match_time_elapsed {
            if !v.is_initialized() {
                return false;
            }
        };
        for v in &self.stage_time_elapsed {
            if !v.is_initialized() {
                return false;
            }
        };
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                8 => {
                    self.id = ::std::option::Option::Some(is.read_int32()?);
                },
                18 => {
                    ::protobuf::rt::read_singular_message_into_field(is, &mut self.change)?;
                },
                26 => {
                    ::protobuf::rt::read_singular_message_into_field(is, &mut self.match_time_elapsed)?;
                },
                34 => {
                    ::protobuf::rt::read_singular_message_into_field(is, &mut self.stage_time_elapsed)?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if let Some(v) = self.id {
            my_size += ::protobuf::rt::int32_size(1, v);
        }
        if let Some(v) = self.change.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        }
        if let Some(v) = self.match_time_elapsed.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        }
        if let Some(v) = self.stage_time_elapsed.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if let Some(v) = self.id {
            os.write_int32(1, v)?;
        }
        if let Some(v) = self.change.as_ref() {
            ::protobuf::rt::write_message_field_with_cached_size(2, v, os)?;
        }
        if let Some(v) = self.match_time_elapsed.as_ref() {
            ::protobuf::rt::write_message_field_with_cached_size(3, v, os)?;
        }
        if let Some(v) = self.stage_time_elapsed.as_ref() {
            ::protobuf::rt::write_message_field_with_cached_size(4, v, os)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> ProtocolEntry {
        ProtocolEntry::new()
    }

    fn clear(&mut self) {
        self.id = ::std::option::Option::None;
        self.change.clear();
        self.match_time_elapsed.clear();
        self.stage_time_elapsed.clear();
        self.special_fields.clear();
    }

    fn default_instance() -> &'static ProtocolEntry {
        static instance: ProtocolEntry = ProtocolEntry {
            id: ::std::option::Option::None,
            change: ::protobuf::MessageField::none(),
            match_time_elapsed: ::protobuf::MessageField::none(),
            stage_time_elapsed: ::protobuf::MessageField::none(),
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for ProtocolEntry {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("ProtocolEntry").unwrap()).clone()
    }
}

impl ::std::fmt::Display for ProtocolEntry {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for ProtocolEntry {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

// @@protoc_insertion_point(message:Input)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct Input {
    // message fields
    // @@protoc_insertion_point(field:Input.change)
    pub change: ::protobuf::MessageField<super::ssl_gc_change::Change>,
    // @@protoc_insertion_point(field:Input.reset_match)
    pub reset_match: ::std::option::Option<bool>,
    // @@protoc_insertion_point(field:Input.config_delta)
    pub config_delta: ::protobuf::MessageField<super::ssl_gc_engine_config::Config>,
    // @@protoc_insertion_point(field:Input.continue_action)
    pub continue_action: ::protobuf::MessageField<super::ssl_gc_engine::ContinueAction>,
    // special fields
    // @@protoc_insertion_point(special_field:Input.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a Input {
    fn default() -> &'a Input {
        <Input as ::protobuf::Message>::default_instance()
    }
}

impl Input {
    pub fn new() -> Input {
        ::std::default::Default::default()
    }

    // optional bool reset_match = 2;

    pub fn reset_match(&self) -> bool {
        self.reset_match.unwrap_or(false)
    }

    pub fn clear_reset_match(&mut self) {
        self.reset_match = ::std::option::Option::None;
    }

    pub fn has_reset_match(&self) -> bool {
        self.reset_match.is_some()
    }

    // Param is passed by value, moved
    pub fn set_reset_match(&mut self, v: bool) {
        self.reset_match = ::std::option::Option::Some(v);
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(4);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_message_field_accessor::<_, super::ssl_gc_change::Change>(
            "change",
            |m: &Input| { &m.change },
            |m: &mut Input| { &mut m.change },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_option_accessor::<_, _>(
            "reset_match",
            |m: &Input| { &m.reset_match },
            |m: &mut Input| { &mut m.reset_match },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_message_field_accessor::<_, super::ssl_gc_engine_config::Config>(
            "config_delta",
            |m: &Input| { &m.config_delta },
            |m: &mut Input| { &mut m.config_delta },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_message_field_accessor::<_, super::ssl_gc_engine::ContinueAction>(
            "continue_action",
            |m: &Input| { &m.continue_action },
            |m: &mut Input| { &mut m.continue_action },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<Input>(
            "Input",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for Input {
    const NAME: &'static str = "Input";

    fn is_initialized(&self) -> bool {
        for v in &self.change {
            if !v.is_initialized() {
                return false;
            }
        };
        for v in &self.config_delta {
            if !v.is_initialized() {
                return false;
            }
        };
        for v in &self.continue_action {
            if !v.is_initialized() {
                return false;
            }
        };
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                10 => {
                    ::protobuf::rt::read_singular_message_into_field(is, &mut self.change)?;
                },
                16 => {
                    self.reset_match = ::std::option::Option::Some(is.read_bool()?);
                },
                26 => {
                    ::protobuf::rt::read_singular_message_into_field(is, &mut self.config_delta)?;
                },
                34 => {
                    ::protobuf::rt::read_singular_message_into_field(is, &mut self.continue_action)?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if let Some(v) = self.change.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        }
        if let Some(v) = self.reset_match {
            my_size += 1 + 1;
        }
        if let Some(v) = self.config_delta.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        }
        if let Some(v) = self.continue_action.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if let Some(v) = self.change.as_ref() {
            ::protobuf::rt::write_message_field_with_cached_size(1, v, os)?;
        }
        if let Some(v) = self.reset_match {
            os.write_bool(2, v)?;
        }
        if let Some(v) = self.config_delta.as_ref() {
            ::protobuf::rt::write_message_field_with_cached_size(3, v, os)?;
        }
        if let Some(v) = self.continue_action.as_ref() {
            ::protobuf::rt::write_message_field_with_cached_size(4, v, os)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> Input {
        Input::new()
    }

    fn clear(&mut self) {
        self.change.clear();
        self.reset_match = ::std::option::Option::None;
        self.config_delta.clear();
        self.continue_action.clear();
        self.special_fields.clear();
    }

    fn default_instance() -> &'static Input {
        static instance: Input = Input {
            change: ::protobuf::MessageField::none(),
            reset_match: ::std::option::Option::None,
            config_delta: ::protobuf::MessageField::none(),
            continue_action: ::protobuf::MessageField::none(),
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for Input {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("Input").unwrap()).clone()
    }
}

impl ::std::fmt::Display for Input {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for Input {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\x10ssl_gc_api.proto\x1a\x12ssl_gc_state.proto\x1a\x13ssl_gc_change.pr\
    oto\x1a\x13ssl_gc_engine.proto\x1a\x1assl_gc_engine_config.proto\x1a\x1e\
    google/protobuf/duration.proto\"\x9e\x01\n\x06Output\x12'\n\x0bmatch_sta\
    te\x18\x01\x20\x01(\x0b2\x06.StateR\nmatchState\x12#\n\x08gc_state\x18\
    \x02\x20\x01(\x0b2\x08.GcStateR\x07gcState\x12%\n\x08protocol\x18\x03\
    \x20\x01(\x0b2\t.ProtocolR\x08protocol\x12\x1f\n\x06config\x18\x04\x20\
    \x01(\x0b2\x07.ConfigR\x06config\"F\n\x08Protocol\x12\x14\n\x05delta\x18\
    \x01\x20\x01(\x08R\x05delta\x12$\n\x05entry\x18\x02\x20\x03(\x0b2\x0e.Pr\
    otocolEntryR\x05entry\"\xd2\x01\n\rProtocolEntry\x12\x0e\n\x02id\x18\x01\
    \x20\x01(\x05R\x02id\x12\x1f\n\x06change\x18\x02\x20\x01(\x0b2\x07.Chang\
    eR\x06change\x12G\n\x12match_time_elapsed\x18\x03\x20\x01(\x0b2\x19.goog\
    le.protobuf.DurationR\x10matchTimeElapsed\x12G\n\x12stage_time_elapsed\
    \x18\x04\x20\x01(\x0b2\x19.google.protobuf.DurationR\x10stageTimeElapsed\
    \"\xaf\x01\n\x05Input\x12\x1f\n\x06change\x18\x01\x20\x01(\x0b2\x07.Chan\
    geR\x06change\x12\x1f\n\x0breset_match\x18\x02\x20\x01(\x08R\nresetMatch\
    \x12*\n\x0cconfig_delta\x18\x03\x20\x01(\x0b2\x07.ConfigR\x0bconfigDelta\
    \x128\n\x0fcontinue_action\x18\x04\x20\x01(\x0b2\x0f.ContinueActionR\x0e\
    continueActionb\x06proto2\
";

/// `FileDescriptorProto` object which was a source for this generated file
fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    static file_descriptor_proto_lazy: ::protobuf::rt::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::Lazy::new();
    file_descriptor_proto_lazy.get(|| {
        ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
    })
}

/// `FileDescriptor` object which allows dynamic access to files
pub fn file_descriptor() -> &'static ::protobuf::reflect::FileDescriptor {
    static generated_file_descriptor_lazy: ::protobuf::rt::Lazy<::protobuf::reflect::GeneratedFileDescriptor> = ::protobuf::rt::Lazy::new();
    static file_descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::FileDescriptor> = ::protobuf::rt::Lazy::new();
    file_descriptor.get(|| {
        let generated_file_descriptor = generated_file_descriptor_lazy.get(|| {
            let mut deps = ::std::vec::Vec::with_capacity(5);
            deps.push(super::ssl_gc_state::file_descriptor().clone());
            deps.push(super::ssl_gc_change::file_descriptor().clone());
            deps.push(super::ssl_gc_engine::file_descriptor().clone());
            deps.push(super::ssl_gc_engine_config::file_descriptor().clone());
            deps.push(::protobuf::well_known_types::duration::file_descriptor().clone());
            let mut messages = ::std::vec::Vec::with_capacity(4);
            messages.push(Output::generated_message_descriptor_data());
            messages.push(Protocol::generated_message_descriptor_data());
            messages.push(ProtocolEntry::generated_message_descriptor_data());
            messages.push(Input::generated_message_descriptor_data());
            let mut enums = ::std::vec::Vec::with_capacity(0);
            ::protobuf::reflect::GeneratedFileDescriptor::new_generated(
                file_descriptor_proto(),
                deps,
                messages,
                enums,
            )
        });
        ::protobuf::reflect::FileDescriptor::new_generated_2(generated_file_descriptor)
    })
}
