// This file is generated by rust-protobuf 3.7.2. Do not edit
// .proto file is parsed by pure
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_results)]
#![allow(unused_mut)]

//! Generated file from `ssl_vision_wrapper.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_3_7_2;

// @@protoc_insertion_point(message:SSL_WrapperPacket)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct SSL_WrapperPacket {
    // message fields
    // @@protoc_insertion_point(field:SSL_WrapperPacket.detection)
    pub detection: ::protobuf::MessageField<super::ssl_vision_detection::SSL_DetectionFrame>,
    // @@protoc_insertion_point(field:SSL_WrapperPacket.geometry)
    pub geometry: ::protobuf::MessageField<super::ssl_vision_geometry::SSL_GeometryData>,
    // special fields
    // @@protoc_insertion_point(special_field:SSL_WrapperPacket.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a SSL_WrapperPacket {
    fn default() -> &'a SSL_WrapperPacket {
        <SSL_WrapperPacket as ::protobuf::Message>::default_instance()
    }
}

impl SSL_WrapperPacket {
    pub fn new() -> SSL_WrapperPacket {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(2);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_message_field_accessor::<_, super::ssl_vision_detection::SSL_DetectionFrame>(
            "detection",
            |m: &SSL_WrapperPacket| { &m.detection },
            |m: &mut SSL_WrapperPacket| { &mut m.detection },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_message_field_accessor::<_, super::ssl_vision_geometry::SSL_GeometryData>(
            "geometry",
            |m: &SSL_WrapperPacket| { &m.geometry },
            |m: &mut SSL_WrapperPacket| { &mut m.geometry },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<SSL_WrapperPacket>(
            "SSL_WrapperPacket",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for SSL_WrapperPacket {
    const NAME: &'static str = "SSL_WrapperPacket";

    fn is_initialized(&self) -> bool {
        for v in &self.detection {
            if !v.is_initialized() {
                return false;
            }
        };
        for v in &self.geometry {
            if !v.is_initialized() {
                return false;
            }
        };
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                10 => {
                    ::protobuf::rt::read_singular_message_into_field(is, &mut self.detection)?;
                },
                18 => {
                    ::protobuf::rt::read_singular_message_into_field(is, &mut self.geometry)?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if let Some(v) = self.detection.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        }
        if let Some(v) = self.geometry.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if let Some(v) = self.detection.as_ref() {
            ::protobuf::rt::write_message_field_with_cached_size(1, v, os)?;
        }
        if let Some(v) = self.geometry.as_ref() {
            ::protobuf::rt::write_message_field_with_cached_size(2, v, os)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> SSL_WrapperPacket {
        SSL_WrapperPacket::new()
    }

    fn clear(&mut self) {
        self.detection.clear();
        self.geometry.clear();
        self.special_fields.clear();
    }

    fn default_instance() -> &'static SSL_WrapperPacket {
        static instance: SSL_WrapperPacket = SSL_WrapperPacket {
            detection: ::protobuf::MessageField::none(),
            geometry: ::protobuf::MessageField::none(),
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for SSL_WrapperPacket {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("SSL_WrapperPacket").unwrap()).clone()
    }
}

impl ::std::fmt::Display for SSL_WrapperPacket {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for SSL_WrapperPacket {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\x18ssl_vision_wrapper.proto\x1a\x1assl_vision_detection.proto\x1a\x19\
    ssl_vision_geometry.proto\"u\n\x11SSL_WrapperPacket\x121\n\tdetection\
    \x18\x01\x20\x01(\x0b2\x13.SSL_DetectionFrameR\tdetection\x12-\n\x08geom\
    etry\x18\x02\x20\x01(\x0b2\x11.SSL_GeometryDataR\x08geometryb\x06proto2\
";

/// `FileDescriptorProto` object which was a source for this generated file
fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    static file_descriptor_proto_lazy: ::protobuf::rt::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::Lazy::new();
    file_descriptor_proto_lazy.get(|| {
        ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
    })
}

/// `FileDescriptor` object which allows dynamic access to files
pub fn file_descriptor() -> &'static ::protobuf::reflect::FileDescriptor {
    static generated_file_descriptor_lazy: ::protobuf::rt::Lazy<::protobuf::reflect::GeneratedFileDescriptor> = ::protobuf::rt::Lazy::new();
    static file_descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::FileDescriptor> = ::protobuf::rt::Lazy::new();
    file_descriptor.get(|| {
        let generated_file_descriptor = generated_file_descriptor_lazy.get(|| {
            let mut deps = ::std::vec::Vec::with_capacity(2);
            deps.push(super::ssl_vision_detection::file_descriptor().clone());
            deps.push(super::ssl_vision_geometry::file_descriptor().clone());
            let mut messages = ::std::vec::Vec::with_capacity(1);
            messages.push(SSL_WrapperPacket::generated_message_descriptor_data());
            let mut enums = ::std::vec::Vec::with_capacity(0);
            ::protobuf::reflect::GeneratedFileDescriptor::new_generated(
                file_descriptor_proto(),
                deps,
                messages,
                enums,
            )
        });
        ::protobuf::reflect::FileDescriptor::new_generated_2(generated_file_descriptor)
    })
}
