// This file is generated by rust-protobuf 3.7.2. Do not edit
// .proto file is parsed by pure
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_results)]
#![allow(unused_mut)]

//! Generated file from `ssl_gc_engine_config.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_3_7_2;

// @@protoc_insertion_point(message:Config)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct Config {
    // message fields
    // @@protoc_insertion_point(field:Config.game_event_behavior)
    pub game_event_behavior: ::std::collections::HashMap<::std::string::String, ::protobuf::EnumOrUnknown<config::Behavior>>,
    // @@protoc_insertion_point(field:Config.auto_ref_configs)
    pub auto_ref_configs: ::std::collections::HashMap<::std::string::String, AutoRefConfig>,
    // @@protoc_insertion_point(field:Config.active_tracker_source)
    pub active_tracker_source: ::std::option::Option<::std::string::String>,
    // @@protoc_insertion_point(field:Config.teams)
    pub teams: ::std::vec::Vec<::std::string::String>,
    // @@protoc_insertion_point(field:Config.auto_continue)
    pub auto_continue: ::std::option::Option<bool>,
    // special fields
    // @@protoc_insertion_point(special_field:Config.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a Config {
    fn default() -> &'a Config {
        <Config as ::protobuf::Message>::default_instance()
    }
}

impl Config {
    pub fn new() -> Config {
        ::std::default::Default::default()
    }

    // optional string active_tracker_source = 3;

    pub fn active_tracker_source(&self) -> &str {
        match self.active_tracker_source.as_ref() {
            Some(v) => v,
            None => "",
        }
    }

    pub fn clear_active_tracker_source(&mut self) {
        self.active_tracker_source = ::std::option::Option::None;
    }

    pub fn has_active_tracker_source(&self) -> bool {
        self.active_tracker_source.is_some()
    }

    // Param is passed by value, moved
    pub fn set_active_tracker_source(&mut self, v: ::std::string::String) {
        self.active_tracker_source = ::std::option::Option::Some(v);
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_active_tracker_source(&mut self) -> &mut ::std::string::String {
        if self.active_tracker_source.is_none() {
            self.active_tracker_source = ::std::option::Option::Some(::std::string::String::new());
        }
        self.active_tracker_source.as_mut().unwrap()
    }

    // Take field
    pub fn take_active_tracker_source(&mut self) -> ::std::string::String {
        self.active_tracker_source.take().unwrap_or_else(|| ::std::string::String::new())
    }

    // optional bool auto_continue = 5;

    pub fn auto_continue(&self) -> bool {
        self.auto_continue.unwrap_or(false)
    }

    pub fn clear_auto_continue(&mut self) {
        self.auto_continue = ::std::option::Option::None;
    }

    pub fn has_auto_continue(&self) -> bool {
        self.auto_continue.is_some()
    }

    // Param is passed by value, moved
    pub fn set_auto_continue(&mut self, v: bool) {
        self.auto_continue = ::std::option::Option::Some(v);
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(5);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_map_simpler_accessor_new::<_, _>(
            "game_event_behavior",
            |m: &Config| { &m.game_event_behavior },
            |m: &mut Config| { &mut m.game_event_behavior },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_map_simpler_accessor_new::<_, _>(
            "auto_ref_configs",
            |m: &Config| { &m.auto_ref_configs },
            |m: &mut Config| { &mut m.auto_ref_configs },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_option_accessor::<_, _>(
            "active_tracker_source",
            |m: &Config| { &m.active_tracker_source },
            |m: &mut Config| { &mut m.active_tracker_source },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_vec_simpler_accessor::<_, _>(
            "teams",
            |m: &Config| { &m.teams },
            |m: &mut Config| { &mut m.teams },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_option_accessor::<_, _>(
            "auto_continue",
            |m: &Config| { &m.auto_continue },
            |m: &mut Config| { &mut m.auto_continue },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<Config>(
            "Config",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for Config {
    const NAME: &'static str = "Config";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                10 => {
                    let len = is.read_raw_varint32()?;
                    let old_limit = is.push_limit(len as u64)?;
                    let mut key = ::std::default::Default::default();
                    let mut value = ::std::default::Default::default();
                    while let Some(tag) = is.read_raw_tag_or_eof()? {
                        match tag {
                            10 => key = is.read_string()?,
                            16 => value = is.read_enum_or_unknown()?,
                            _ => ::protobuf::rt::skip_field_for_tag(tag, is)?,
                        };
                    }
                    is.pop_limit(old_limit);
                    self.game_event_behavior.insert(key, value);
                },
                18 => {
                    let len = is.read_raw_varint32()?;
                    let old_limit = is.push_limit(len as u64)?;
                    let mut key = ::std::default::Default::default();
                    let mut value = ::std::default::Default::default();
                    while let Some(tag) = is.read_raw_tag_or_eof()? {
                        match tag {
                            10 => key = is.read_string()?,
                            18 => value = is.read_message()?,
                            _ => ::protobuf::rt::skip_field_for_tag(tag, is)?,
                        };
                    }
                    is.pop_limit(old_limit);
                    self.auto_ref_configs.insert(key, value);
                },
                26 => {
                    self.active_tracker_source = ::std::option::Option::Some(is.read_string()?);
                },
                34 => {
                    self.teams.push(is.read_string()?);
                },
                40 => {
                    self.auto_continue = ::std::option::Option::Some(is.read_bool()?);
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        for (k, v) in &self.game_event_behavior {
            let mut entry_size = 0;
            entry_size += ::protobuf::rt::string_size(1, &k);
            entry_size += ::protobuf::rt::int32_size(2, v.value());
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(entry_size) + entry_size
        };
        for (k, v) in &self.auto_ref_configs {
            let mut entry_size = 0;
            entry_size += ::protobuf::rt::string_size(1, &k);
            let len = v.compute_size();
            entry_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(entry_size) + entry_size
        };
        if let Some(v) = self.active_tracker_source.as_ref() {
            my_size += ::protobuf::rt::string_size(3, &v);
        }
        for value in &self.teams {
            my_size += ::protobuf::rt::string_size(4, &value);
        };
        if let Some(v) = self.auto_continue {
            my_size += 1 + 1;
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        for (k, v) in &self.game_event_behavior {
            let mut entry_size = 0;
            entry_size += ::protobuf::rt::string_size(1, &k);
            entry_size += ::protobuf::rt::int32_size(2, v.value());
            os.write_raw_varint32(10)?; // Tag.
            os.write_raw_varint32(entry_size as u32)?;
            os.write_string(1, &k)?;
            os.write_enum(2, ::protobuf::EnumOrUnknown::value(v))?;
        };
        for (k, v) in &self.auto_ref_configs {
            let mut entry_size = 0;
            entry_size += ::protobuf::rt::string_size(1, &k);
            let len = v.cached_size() as u64;
            entry_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
            os.write_raw_varint32(18)?; // Tag.
            os.write_raw_varint32(entry_size as u32)?;
            os.write_string(1, &k)?;
            ::protobuf::rt::write_message_field_with_cached_size(2, v, os)?;
        };
        if let Some(v) = self.active_tracker_source.as_ref() {
            os.write_string(3, v)?;
        }
        for v in &self.teams {
            os.write_string(4, &v)?;
        };
        if let Some(v) = self.auto_continue {
            os.write_bool(5, v)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> Config {
        Config::new()
    }

    fn clear(&mut self) {
        self.game_event_behavior.clear();
        self.auto_ref_configs.clear();
        self.active_tracker_source = ::std::option::Option::None;
        self.teams.clear();
        self.auto_continue = ::std::option::Option::None;
        self.special_fields.clear();
    }

    fn default_instance() -> &'static Config {
        static instance: ::protobuf::rt::Lazy<Config> = ::protobuf::rt::Lazy::new();
        instance.get(Config::new)
    }
}

impl ::protobuf::MessageFull for Config {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("Config").unwrap()).clone()
    }
}

impl ::std::fmt::Display for Config {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for Config {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

/// Nested message and enums of message `Config`
pub mod config {
    #[derive(Clone,Copy,PartialEq,Eq,Debug,Hash)]
    // @@protoc_insertion_point(enum:Config.Behavior)
    pub enum Behavior {
        // @@protoc_insertion_point(enum_value:Config.Behavior.BEHAVIOR_UNKNOWN)
        BEHAVIOR_UNKNOWN = 0,
        // @@protoc_insertion_point(enum_value:Config.Behavior.BEHAVIOR_ACCEPT)
        BEHAVIOR_ACCEPT = 1,
        // @@protoc_insertion_point(enum_value:Config.Behavior.BEHAVIOR_ACCEPT_MAJORITY)
        BEHAVIOR_ACCEPT_MAJORITY = 2,
        // @@protoc_insertion_point(enum_value:Config.Behavior.BEHAVIOR_PROPOSE_ONLY)
        BEHAVIOR_PROPOSE_ONLY = 3,
        // @@protoc_insertion_point(enum_value:Config.Behavior.BEHAVIOR_LOG)
        BEHAVIOR_LOG = 4,
        // @@protoc_insertion_point(enum_value:Config.Behavior.BEHAVIOR_IGNORE)
        BEHAVIOR_IGNORE = 5,
    }

    impl ::protobuf::Enum for Behavior {
        const NAME: &'static str = "Behavior";

        fn value(&self) -> i32 {
            *self as i32
        }

        fn from_i32(value: i32) -> ::std::option::Option<Behavior> {
            match value {
                0 => ::std::option::Option::Some(Behavior::BEHAVIOR_UNKNOWN),
                1 => ::std::option::Option::Some(Behavior::BEHAVIOR_ACCEPT),
                2 => ::std::option::Option::Some(Behavior::BEHAVIOR_ACCEPT_MAJORITY),
                3 => ::std::option::Option::Some(Behavior::BEHAVIOR_PROPOSE_ONLY),
                4 => ::std::option::Option::Some(Behavior::BEHAVIOR_LOG),
                5 => ::std::option::Option::Some(Behavior::BEHAVIOR_IGNORE),
                _ => ::std::option::Option::None
            }
        }

        fn from_str(str: &str) -> ::std::option::Option<Behavior> {
            match str {
                "BEHAVIOR_UNKNOWN" => ::std::option::Option::Some(Behavior::BEHAVIOR_UNKNOWN),
                "BEHAVIOR_ACCEPT" => ::std::option::Option::Some(Behavior::BEHAVIOR_ACCEPT),
                "BEHAVIOR_ACCEPT_MAJORITY" => ::std::option::Option::Some(Behavior::BEHAVIOR_ACCEPT_MAJORITY),
                "BEHAVIOR_PROPOSE_ONLY" => ::std::option::Option::Some(Behavior::BEHAVIOR_PROPOSE_ONLY),
                "BEHAVIOR_LOG" => ::std::option::Option::Some(Behavior::BEHAVIOR_LOG),
                "BEHAVIOR_IGNORE" => ::std::option::Option::Some(Behavior::BEHAVIOR_IGNORE),
                _ => ::std::option::Option::None
            }
        }

        const VALUES: &'static [Behavior] = &[
            Behavior::BEHAVIOR_UNKNOWN,
            Behavior::BEHAVIOR_ACCEPT,
            Behavior::BEHAVIOR_ACCEPT_MAJORITY,
            Behavior::BEHAVIOR_PROPOSE_ONLY,
            Behavior::BEHAVIOR_LOG,
            Behavior::BEHAVIOR_IGNORE,
        ];
    }

    impl ::protobuf::EnumFull for Behavior {
        fn enum_descriptor() -> ::protobuf::reflect::EnumDescriptor {
            static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::EnumDescriptor> = ::protobuf::rt::Lazy::new();
            descriptor.get(|| super::file_descriptor().enum_by_package_relative_name("Config.Behavior").unwrap()).clone()
        }

        fn descriptor(&self) -> ::protobuf::reflect::EnumValueDescriptor {
            let index = *self as usize;
            Self::enum_descriptor().value_by_index(index)
        }
    }

    impl ::std::default::Default for Behavior {
        fn default() -> Self {
            Behavior::BEHAVIOR_UNKNOWN
        }
    }

    impl Behavior {
        pub(in super) fn generated_enum_descriptor_data() -> ::protobuf::reflect::GeneratedEnumDescriptorData {
            ::protobuf::reflect::GeneratedEnumDescriptorData::new::<Behavior>("Config.Behavior")
        }
    }
}

// @@protoc_insertion_point(message:AutoRefConfig)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct AutoRefConfig {
    // message fields
    // @@protoc_insertion_point(field:AutoRefConfig.game_event_behavior)
    pub game_event_behavior: ::std::collections::HashMap<::std::string::String, ::protobuf::EnumOrUnknown<auto_ref_config::Behavior>>,
    // special fields
    // @@protoc_insertion_point(special_field:AutoRefConfig.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a AutoRefConfig {
    fn default() -> &'a AutoRefConfig {
        <AutoRefConfig as ::protobuf::Message>::default_instance()
    }
}

impl AutoRefConfig {
    pub fn new() -> AutoRefConfig {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(1);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_map_simpler_accessor_new::<_, _>(
            "game_event_behavior",
            |m: &AutoRefConfig| { &m.game_event_behavior },
            |m: &mut AutoRefConfig| { &mut m.game_event_behavior },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<AutoRefConfig>(
            "AutoRefConfig",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for AutoRefConfig {
    const NAME: &'static str = "AutoRefConfig";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                10 => {
                    let len = is.read_raw_varint32()?;
                    let old_limit = is.push_limit(len as u64)?;
                    let mut key = ::std::default::Default::default();
                    let mut value = ::std::default::Default::default();
                    while let Some(tag) = is.read_raw_tag_or_eof()? {
                        match tag {
                            10 => key = is.read_string()?,
                            16 => value = is.read_enum_or_unknown()?,
                            _ => ::protobuf::rt::skip_field_for_tag(tag, is)?,
                        };
                    }
                    is.pop_limit(old_limit);
                    self.game_event_behavior.insert(key, value);
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        for (k, v) in &self.game_event_behavior {
            let mut entry_size = 0;
            entry_size += ::protobuf::rt::string_size(1, &k);
            entry_size += ::protobuf::rt::int32_size(2, v.value());
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(entry_size) + entry_size
        };
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        for (k, v) in &self.game_event_behavior {
            let mut entry_size = 0;
            entry_size += ::protobuf::rt::string_size(1, &k);
            entry_size += ::protobuf::rt::int32_size(2, v.value());
            os.write_raw_varint32(10)?; // Tag.
            os.write_raw_varint32(entry_size as u32)?;
            os.write_string(1, &k)?;
            os.write_enum(2, ::protobuf::EnumOrUnknown::value(v))?;
        };
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> AutoRefConfig {
        AutoRefConfig::new()
    }

    fn clear(&mut self) {
        self.game_event_behavior.clear();
        self.special_fields.clear();
    }

    fn default_instance() -> &'static AutoRefConfig {
        static instance: ::protobuf::rt::Lazy<AutoRefConfig> = ::protobuf::rt::Lazy::new();
        instance.get(AutoRefConfig::new)
    }
}

impl ::protobuf::MessageFull for AutoRefConfig {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("AutoRefConfig").unwrap()).clone()
    }
}

impl ::std::fmt::Display for AutoRefConfig {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for AutoRefConfig {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

/// Nested message and enums of message `AutoRefConfig`
pub mod auto_ref_config {
    #[derive(Clone,Copy,PartialEq,Eq,Debug,Hash)]
    // @@protoc_insertion_point(enum:AutoRefConfig.Behavior)
    pub enum Behavior {
        // @@protoc_insertion_point(enum_value:AutoRefConfig.Behavior.BEHAVIOR_UNKNOWN)
        BEHAVIOR_UNKNOWN = 0,
        // @@protoc_insertion_point(enum_value:AutoRefConfig.Behavior.BEHAVIOR_ACCEPT)
        BEHAVIOR_ACCEPT = 1,
        // @@protoc_insertion_point(enum_value:AutoRefConfig.Behavior.BEHAVIOR_LOG)
        BEHAVIOR_LOG = 2,
        // @@protoc_insertion_point(enum_value:AutoRefConfig.Behavior.BEHAVIOR_IGNORE)
        BEHAVIOR_IGNORE = 3,
    }

    impl ::protobuf::Enum for Behavior {
        const NAME: &'static str = "Behavior";

        fn value(&self) -> i32 {
            *self as i32
        }

        fn from_i32(value: i32) -> ::std::option::Option<Behavior> {
            match value {
                0 => ::std::option::Option::Some(Behavior::BEHAVIOR_UNKNOWN),
                1 => ::std::option::Option::Some(Behavior::BEHAVIOR_ACCEPT),
                2 => ::std::option::Option::Some(Behavior::BEHAVIOR_LOG),
                3 => ::std::option::Option::Some(Behavior::BEHAVIOR_IGNORE),
                _ => ::std::option::Option::None
            }
        }

        fn from_str(str: &str) -> ::std::option::Option<Behavior> {
            match str {
                "BEHAVIOR_UNKNOWN" => ::std::option::Option::Some(Behavior::BEHAVIOR_UNKNOWN),
                "BEHAVIOR_ACCEPT" => ::std::option::Option::Some(Behavior::BEHAVIOR_ACCEPT),
                "BEHAVIOR_LOG" => ::std::option::Option::Some(Behavior::BEHAVIOR_LOG),
                "BEHAVIOR_IGNORE" => ::std::option::Option::Some(Behavior::BEHAVIOR_IGNORE),
                _ => ::std::option::Option::None
            }
        }

        const VALUES: &'static [Behavior] = &[
            Behavior::BEHAVIOR_UNKNOWN,
            Behavior::BEHAVIOR_ACCEPT,
            Behavior::BEHAVIOR_LOG,
            Behavior::BEHAVIOR_IGNORE,
        ];
    }

    impl ::protobuf::EnumFull for Behavior {
        fn enum_descriptor() -> ::protobuf::reflect::EnumDescriptor {
            static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::EnumDescriptor> = ::protobuf::rt::Lazy::new();
            descriptor.get(|| super::file_descriptor().enum_by_package_relative_name("AutoRefConfig.Behavior").unwrap()).clone()
        }

        fn descriptor(&self) -> ::protobuf::reflect::EnumValueDescriptor {
            let index = *self as usize;
            Self::enum_descriptor().value_by_index(index)
        }
    }

    impl ::std::default::Default for Behavior {
        fn default() -> Self {
            Behavior::BEHAVIOR_UNKNOWN
        }
    }

    impl Behavior {
        pub(in super) fn generated_enum_descriptor_data() -> ::protobuf::reflect::GeneratedEnumDescriptorData {
            ::protobuf::reflect::GeneratedEnumDescriptorData::new::<Behavior>("AutoRefConfig.Behavior")
        }
    }
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\x1assl_gc_engine_config.proto\"\xd1\x04\n\x06Config\x12N\n\x13game_ev\
    ent_behavior\x18\x01\x20\x03(\x0b2\x1e.Config.GameEventBehaviorEntryR\
    \x11gameEventBehavior\x12E\n\x10auto_ref_configs\x18\x02\x20\x03(\x0b2\
    \x1b.Config.AutoRefConfigsEntryR\x0eautoRefConfigs\x122\n\x15active_trac\
    ker_source\x18\x03\x20\x01(\tR\x13activeTrackerSource\x12\x14\n\x05teams\
    \x18\x04\x20\x03(\tR\x05teams\x12#\n\rauto_continue\x18\x05\x20\x01(\x08\
    R\x0cautoContinue\x1aV\n\x16GameEventBehaviorEntry\x12\x10\n\x03key\x18\
    \x01\x20\x01(\tR\x03key\x12&\n\x05value\x18\x02\x20\x01(\x0e2\x10.Config\
    .BehaviorR\x05value:\x028\x01\x1aQ\n\x13AutoRefConfigsEntry\x12\x10\n\
    \x03key\x18\x01\x20\x01(\tR\x03key\x12$\n\x05value\x18\x02\x20\x01(\x0b2\
    \x0e.AutoRefConfigR\x05value:\x028\x01\"\x95\x01\n\x08Behavior\x12\x14\n\
    \x10BEHAVIOR_UNKNOWN\x10\0\x12\x13\n\x0fBEHAVIOR_ACCEPT\x10\x01\x12\x1c\
    \n\x18BEHAVIOR_ACCEPT_MAJORITY\x10\x02\x12\x19\n\x15BEHAVIOR_PROPOSE_ONL\
    Y\x10\x03\x12\x10\n\x0cBEHAVIOR_LOG\x10\x04\x12\x13\n\x0fBEHAVIOR_IGNORE\
    \x10\x05\"\xa3\x02\n\rAutoRefConfig\x12U\n\x13game_event_behavior\x18\
    \x01\x20\x03(\x0b2%.AutoRefConfig.GameEventBehaviorEntryR\x11gameEventBe\
    havior\x1a]\n\x16GameEventBehaviorEntry\x12\x10\n\x03key\x18\x01\x20\x01\
    (\tR\x03key\x12-\n\x05value\x18\x02\x20\x01(\x0e2\x17.AutoRefConfig.Beha\
    viorR\x05value:\x028\x01\"\\\n\x08Behavior\x12\x14\n\x10BEHAVIOR_UNKNOWN\
    \x10\0\x12\x13\n\x0fBEHAVIOR_ACCEPT\x10\x01\x12\x10\n\x0cBEHAVIOR_LOG\
    \x10\x02\x12\x13\n\x0fBEHAVIOR_IGNORE\x10\x03b\x06proto2\
";

/// `FileDescriptorProto` object which was a source for this generated file
fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    static file_descriptor_proto_lazy: ::protobuf::rt::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::Lazy::new();
    file_descriptor_proto_lazy.get(|| {
        ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
    })
}

/// `FileDescriptor` object which allows dynamic access to files
pub fn file_descriptor() -> &'static ::protobuf::reflect::FileDescriptor {
    static generated_file_descriptor_lazy: ::protobuf::rt::Lazy<::protobuf::reflect::GeneratedFileDescriptor> = ::protobuf::rt::Lazy::new();
    static file_descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::FileDescriptor> = ::protobuf::rt::Lazy::new();
    file_descriptor.get(|| {
        let generated_file_descriptor = generated_file_descriptor_lazy.get(|| {
            let mut deps = ::std::vec::Vec::with_capacity(0);
            let mut messages = ::std::vec::Vec::with_capacity(2);
            messages.push(Config::generated_message_descriptor_data());
            messages.push(AutoRefConfig::generated_message_descriptor_data());
            let mut enums = ::std::vec::Vec::with_capacity(2);
            enums.push(config::Behavior::generated_enum_descriptor_data());
            enums.push(auto_ref_config::Behavior::generated_enum_descriptor_data());
            ::protobuf::reflect::GeneratedFileDescriptor::new_generated(
                file_descriptor_proto(),
                deps,
                messages,
                enums,
            )
        });
        ::protobuf::reflect::FileDescriptor::new_generated_2(generated_file_descriptor)
    })
}
