// This file is generated by rust-protobuf 3.7.2. Do not edit
// .proto file is parsed by pure
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_results)]
#![allow(unused_mut)]

//! Generated file from `ssl_gc_engine.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_3_7_2;

// @@protoc_insertion_point(message:GcState)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct GcState {
    // message fields
    // @@protoc_insertion_point(field:GcState.team_state)
    pub team_state: ::std::collections::HashMap<::std::string::String, GcStateTeam>,
    // @@protoc_insertion_point(field:GcState.auto_ref_state)
    pub auto_ref_state: ::std::collections::HashMap<::std::string::String, GcStateAutoRef>,
    // @@protoc_insertion_point(field:GcState.trackers)
    pub trackers: ::std::collections::HashMap<::std::string::String, ::std::string::String>,
    // @@protoc_insertion_point(field:GcState.continue_actions)
    pub continue_actions: ::std::vec::Vec<ContinueAction>,
    // @@protoc_insertion_point(field:GcState.continue_hints)
    pub continue_hints: ::std::vec::Vec<ContinueHint>,
    // special fields
    // @@protoc_insertion_point(special_field:GcState.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a GcState {
    fn default() -> &'a GcState {
        <GcState as ::protobuf::Message>::default_instance()
    }
}

impl GcState {
    pub fn new() -> GcState {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(5);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_map_simpler_accessor_new::<_, _>(
            "team_state",
            |m: &GcState| { &m.team_state },
            |m: &mut GcState| { &mut m.team_state },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_map_simpler_accessor_new::<_, _>(
            "auto_ref_state",
            |m: &GcState| { &m.auto_ref_state },
            |m: &mut GcState| { &mut m.auto_ref_state },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_map_simpler_accessor_new::<_, _>(
            "trackers",
            |m: &GcState| { &m.trackers },
            |m: &mut GcState| { &mut m.trackers },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_vec_simpler_accessor::<_, _>(
            "continue_actions",
            |m: &GcState| { &m.continue_actions },
            |m: &mut GcState| { &mut m.continue_actions },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_vec_simpler_accessor::<_, _>(
            "continue_hints",
            |m: &GcState| { &m.continue_hints },
            |m: &mut GcState| { &mut m.continue_hints },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<GcState>(
            "GcState",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for GcState {
    const NAME: &'static str = "GcState";

    fn is_initialized(&self) -> bool {
        // TODO: check map values are initialized
        // TODO: check map values are initialized
        // TODO: check map values are initialized
        for v in &self.continue_actions {
            if !v.is_initialized() {
                return false;
            }
        };
        for v in &self.continue_hints {
            if !v.is_initialized() {
                return false;
            }
        };
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                10 => {
                    let len = is.read_raw_varint32()?;
                    let old_limit = is.push_limit(len as u64)?;
                    let mut key = ::std::default::Default::default();
                    let mut value = ::std::default::Default::default();
                    while let Some(tag) = is.read_raw_tag_or_eof()? {
                        match tag {
                            10 => key = is.read_string()?,
                            18 => value = is.read_message()?,
                            _ => ::protobuf::rt::skip_field_for_tag(tag, is)?,
                        };
                    }
                    is.pop_limit(old_limit);
                    self.team_state.insert(key, value);
                },
                18 => {
                    let len = is.read_raw_varint32()?;
                    let old_limit = is.push_limit(len as u64)?;
                    let mut key = ::std::default::Default::default();
                    let mut value = ::std::default::Default::default();
                    while let Some(tag) = is.read_raw_tag_or_eof()? {
                        match tag {
                            10 => key = is.read_string()?,
                            18 => value = is.read_message()?,
                            _ => ::protobuf::rt::skip_field_for_tag(tag, is)?,
                        };
                    }
                    is.pop_limit(old_limit);
                    self.auto_ref_state.insert(key, value);
                },
                26 => {
                    let len = is.read_raw_varint32()?;
                    let old_limit = is.push_limit(len as u64)?;
                    let mut key = ::std::default::Default::default();
                    let mut value = ::std::default::Default::default();
                    while let Some(tag) = is.read_raw_tag_or_eof()? {
                        match tag {
                            10 => key = is.read_string()?,
                            18 => value = is.read_string()?,
                            _ => ::protobuf::rt::skip_field_for_tag(tag, is)?,
                        };
                    }
                    is.pop_limit(old_limit);
                    self.trackers.insert(key, value);
                },
                34 => {
                    self.continue_actions.push(is.read_message()?);
                },
                42 => {
                    self.continue_hints.push(is.read_message()?);
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        for (k, v) in &self.team_state {
            let mut entry_size = 0;
            entry_size += ::protobuf::rt::string_size(1, &k);
            let len = v.compute_size();
            entry_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(entry_size) + entry_size
        };
        for (k, v) in &self.auto_ref_state {
            let mut entry_size = 0;
            entry_size += ::protobuf::rt::string_size(1, &k);
            let len = v.compute_size();
            entry_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(entry_size) + entry_size
        };
        for (k, v) in &self.trackers {
            let mut entry_size = 0;
            entry_size += ::protobuf::rt::string_size(1, &k);
            entry_size += ::protobuf::rt::string_size(2, &v);
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(entry_size) + entry_size
        };
        for value in &self.continue_actions {
            let len = value.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        };
        for value in &self.continue_hints {
            let len = value.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        };
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        for (k, v) in &self.team_state {
            let mut entry_size = 0;
            entry_size += ::protobuf::rt::string_size(1, &k);
            let len = v.cached_size() as u64;
            entry_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
            os.write_raw_varint32(10)?; // Tag.
            os.write_raw_varint32(entry_size as u32)?;
            os.write_string(1, &k)?;
            ::protobuf::rt::write_message_field_with_cached_size(2, v, os)?;
        };
        for (k, v) in &self.auto_ref_state {
            let mut entry_size = 0;
            entry_size += ::protobuf::rt::string_size(1, &k);
            let len = v.cached_size() as u64;
            entry_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
            os.write_raw_varint32(18)?; // Tag.
            os.write_raw_varint32(entry_size as u32)?;
            os.write_string(1, &k)?;
            ::protobuf::rt::write_message_field_with_cached_size(2, v, os)?;
        };
        for (k, v) in &self.trackers {
            let mut entry_size = 0;
            entry_size += ::protobuf::rt::string_size(1, &k);
            entry_size += ::protobuf::rt::string_size(2, &v);
            os.write_raw_varint32(26)?; // Tag.
            os.write_raw_varint32(entry_size as u32)?;
            os.write_string(1, &k)?;
            os.write_string(2, &v)?;
        };
        for v in &self.continue_actions {
            ::protobuf::rt::write_message_field_with_cached_size(4, v, os)?;
        };
        for v in &self.continue_hints {
            ::protobuf::rt::write_message_field_with_cached_size(5, v, os)?;
        };
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> GcState {
        GcState::new()
    }

    fn clear(&mut self) {
        self.team_state.clear();
        self.auto_ref_state.clear();
        self.trackers.clear();
        self.continue_actions.clear();
        self.continue_hints.clear();
        self.special_fields.clear();
    }

    fn default_instance() -> &'static GcState {
        static instance: ::protobuf::rt::Lazy<GcState> = ::protobuf::rt::Lazy::new();
        instance.get(GcState::new)
    }
}

impl ::protobuf::MessageFull for GcState {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("GcState").unwrap()).clone()
    }
}

impl ::std::fmt::Display for GcState {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for GcState {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

// @@protoc_insertion_point(message:GcStateTeam)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct GcStateTeam {
    // message fields
    // @@protoc_insertion_point(field:GcStateTeam.connected)
    pub connected: ::std::option::Option<bool>,
    // @@protoc_insertion_point(field:GcStateTeam.connection_verified)
    pub connection_verified: ::std::option::Option<bool>,
    // @@protoc_insertion_point(field:GcStateTeam.remote_control_connected)
    pub remote_control_connected: ::std::option::Option<bool>,
    // @@protoc_insertion_point(field:GcStateTeam.remote_control_connection_verified)
    pub remote_control_connection_verified: ::std::option::Option<bool>,
    // @@protoc_insertion_point(field:GcStateTeam.advantage_choice)
    pub advantage_choice: ::protobuf::MessageField<TeamAdvantageChoice>,
    // special fields
    // @@protoc_insertion_point(special_field:GcStateTeam.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a GcStateTeam {
    fn default() -> &'a GcStateTeam {
        <GcStateTeam as ::protobuf::Message>::default_instance()
    }
}

impl GcStateTeam {
    pub fn new() -> GcStateTeam {
        ::std::default::Default::default()
    }

    // optional bool connected = 1;

    pub fn connected(&self) -> bool {
        self.connected.unwrap_or(false)
    }

    pub fn clear_connected(&mut self) {
        self.connected = ::std::option::Option::None;
    }

    pub fn has_connected(&self) -> bool {
        self.connected.is_some()
    }

    // Param is passed by value, moved
    pub fn set_connected(&mut self, v: bool) {
        self.connected = ::std::option::Option::Some(v);
    }

    // optional bool connection_verified = 2;

    pub fn connection_verified(&self) -> bool {
        self.connection_verified.unwrap_or(false)
    }

    pub fn clear_connection_verified(&mut self) {
        self.connection_verified = ::std::option::Option::None;
    }

    pub fn has_connection_verified(&self) -> bool {
        self.connection_verified.is_some()
    }

    // Param is passed by value, moved
    pub fn set_connection_verified(&mut self, v: bool) {
        self.connection_verified = ::std::option::Option::Some(v);
    }

    // optional bool remote_control_connected = 3;

    pub fn remote_control_connected(&self) -> bool {
        self.remote_control_connected.unwrap_or(false)
    }

    pub fn clear_remote_control_connected(&mut self) {
        self.remote_control_connected = ::std::option::Option::None;
    }

    pub fn has_remote_control_connected(&self) -> bool {
        self.remote_control_connected.is_some()
    }

    // Param is passed by value, moved
    pub fn set_remote_control_connected(&mut self, v: bool) {
        self.remote_control_connected = ::std::option::Option::Some(v);
    }

    // optional bool remote_control_connection_verified = 4;

    pub fn remote_control_connection_verified(&self) -> bool {
        self.remote_control_connection_verified.unwrap_or(false)
    }

    pub fn clear_remote_control_connection_verified(&mut self) {
        self.remote_control_connection_verified = ::std::option::Option::None;
    }

    pub fn has_remote_control_connection_verified(&self) -> bool {
        self.remote_control_connection_verified.is_some()
    }

    // Param is passed by value, moved
    pub fn set_remote_control_connection_verified(&mut self, v: bool) {
        self.remote_control_connection_verified = ::std::option::Option::Some(v);
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(5);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_option_accessor::<_, _>(
            "connected",
            |m: &GcStateTeam| { &m.connected },
            |m: &mut GcStateTeam| { &mut m.connected },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_option_accessor::<_, _>(
            "connection_verified",
            |m: &GcStateTeam| { &m.connection_verified },
            |m: &mut GcStateTeam| { &mut m.connection_verified },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_option_accessor::<_, _>(
            "remote_control_connected",
            |m: &GcStateTeam| { &m.remote_control_connected },
            |m: &mut GcStateTeam| { &mut m.remote_control_connected },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_option_accessor::<_, _>(
            "remote_control_connection_verified",
            |m: &GcStateTeam| { &m.remote_control_connection_verified },
            |m: &mut GcStateTeam| { &mut m.remote_control_connection_verified },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_message_field_accessor::<_, TeamAdvantageChoice>(
            "advantage_choice",
            |m: &GcStateTeam| { &m.advantage_choice },
            |m: &mut GcStateTeam| { &mut m.advantage_choice },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<GcStateTeam>(
            "GcStateTeam",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for GcStateTeam {
    const NAME: &'static str = "GcStateTeam";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                8 => {
                    self.connected = ::std::option::Option::Some(is.read_bool()?);
                },
                16 => {
                    self.connection_verified = ::std::option::Option::Some(is.read_bool()?);
                },
                24 => {
                    self.remote_control_connected = ::std::option::Option::Some(is.read_bool()?);
                },
                32 => {
                    self.remote_control_connection_verified = ::std::option::Option::Some(is.read_bool()?);
                },
                42 => {
                    ::protobuf::rt::read_singular_message_into_field(is, &mut self.advantage_choice)?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if let Some(v) = self.connected {
            my_size += 1 + 1;
        }
        if let Some(v) = self.connection_verified {
            my_size += 1 + 1;
        }
        if let Some(v) = self.remote_control_connected {
            my_size += 1 + 1;
        }
        if let Some(v) = self.remote_control_connection_verified {
            my_size += 1 + 1;
        }
        if let Some(v) = self.advantage_choice.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if let Some(v) = self.connected {
            os.write_bool(1, v)?;
        }
        if let Some(v) = self.connection_verified {
            os.write_bool(2, v)?;
        }
        if let Some(v) = self.remote_control_connected {
            os.write_bool(3, v)?;
        }
        if let Some(v) = self.remote_control_connection_verified {
            os.write_bool(4, v)?;
        }
        if let Some(v) = self.advantage_choice.as_ref() {
            ::protobuf::rt::write_message_field_with_cached_size(5, v, os)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> GcStateTeam {
        GcStateTeam::new()
    }

    fn clear(&mut self) {
        self.connected = ::std::option::Option::None;
        self.connection_verified = ::std::option::Option::None;
        self.remote_control_connected = ::std::option::Option::None;
        self.remote_control_connection_verified = ::std::option::Option::None;
        self.advantage_choice.clear();
        self.special_fields.clear();
    }

    fn default_instance() -> &'static GcStateTeam {
        static instance: GcStateTeam = GcStateTeam {
            connected: ::std::option::Option::None,
            connection_verified: ::std::option::Option::None,
            remote_control_connected: ::std::option::Option::None,
            remote_control_connection_verified: ::std::option::Option::None,
            advantage_choice: ::protobuf::MessageField::none(),
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for GcStateTeam {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("GcStateTeam").unwrap()).clone()
    }
}

impl ::std::fmt::Display for GcStateTeam {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for GcStateTeam {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

// @@protoc_insertion_point(message:TeamAdvantageChoice)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct TeamAdvantageChoice {
    // message fields
    // @@protoc_insertion_point(field:TeamAdvantageChoice.choice)
    pub choice: ::std::option::Option<::protobuf::EnumOrUnknown<team_advantage_choice::AdvantageChoice>>,
    // special fields
    // @@protoc_insertion_point(special_field:TeamAdvantageChoice.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a TeamAdvantageChoice {
    fn default() -> &'a TeamAdvantageChoice {
        <TeamAdvantageChoice as ::protobuf::Message>::default_instance()
    }
}

impl TeamAdvantageChoice {
    pub fn new() -> TeamAdvantageChoice {
        ::std::default::Default::default()
    }

    // optional .TeamAdvantageChoice.AdvantageChoice choice = 1;

    pub fn choice(&self) -> team_advantage_choice::AdvantageChoice {
        match self.choice {
            Some(e) => e.enum_value_or(team_advantage_choice::AdvantageChoice::STOP),
            None => team_advantage_choice::AdvantageChoice::STOP,
        }
    }

    pub fn clear_choice(&mut self) {
        self.choice = ::std::option::Option::None;
    }

    pub fn has_choice(&self) -> bool {
        self.choice.is_some()
    }

    // Param is passed by value, moved
    pub fn set_choice(&mut self, v: team_advantage_choice::AdvantageChoice) {
        self.choice = ::std::option::Option::Some(::protobuf::EnumOrUnknown::new(v));
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(1);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_option_accessor::<_, _>(
            "choice",
            |m: &TeamAdvantageChoice| { &m.choice },
            |m: &mut TeamAdvantageChoice| { &mut m.choice },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<TeamAdvantageChoice>(
            "TeamAdvantageChoice",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for TeamAdvantageChoice {
    const NAME: &'static str = "TeamAdvantageChoice";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                8 => {
                    self.choice = ::std::option::Option::Some(is.read_enum_or_unknown()?);
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if let Some(v) = self.choice {
            my_size += ::protobuf::rt::int32_size(1, v.value());
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if let Some(v) = self.choice {
            os.write_enum(1, ::protobuf::EnumOrUnknown::value(&v))?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> TeamAdvantageChoice {
        TeamAdvantageChoice::new()
    }

    fn clear(&mut self) {
        self.choice = ::std::option::Option::None;
        self.special_fields.clear();
    }

    fn default_instance() -> &'static TeamAdvantageChoice {
        static instance: TeamAdvantageChoice = TeamAdvantageChoice {
            choice: ::std::option::Option::None,
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for TeamAdvantageChoice {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("TeamAdvantageChoice").unwrap()).clone()
    }
}

impl ::std::fmt::Display for TeamAdvantageChoice {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for TeamAdvantageChoice {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

/// Nested message and enums of message `TeamAdvantageChoice`
pub mod team_advantage_choice {
    #[derive(Clone,Copy,PartialEq,Eq,Debug,Hash)]
    // @@protoc_insertion_point(enum:TeamAdvantageChoice.AdvantageChoice)
    pub enum AdvantageChoice {
        // @@protoc_insertion_point(enum_value:TeamAdvantageChoice.AdvantageChoice.STOP)
        STOP = 0,
        // @@protoc_insertion_point(enum_value:TeamAdvantageChoice.AdvantageChoice.CONTINUE)
        CONTINUE = 1,
    }

    impl ::protobuf::Enum for AdvantageChoice {
        const NAME: &'static str = "AdvantageChoice";

        fn value(&self) -> i32 {
            *self as i32
        }

        fn from_i32(value: i32) -> ::std::option::Option<AdvantageChoice> {
            match value {
                0 => ::std::option::Option::Some(AdvantageChoice::STOP),
                1 => ::std::option::Option::Some(AdvantageChoice::CONTINUE),
                _ => ::std::option::Option::None
            }
        }

        fn from_str(str: &str) -> ::std::option::Option<AdvantageChoice> {
            match str {
                "STOP" => ::std::option::Option::Some(AdvantageChoice::STOP),
                "CONTINUE" => ::std::option::Option::Some(AdvantageChoice::CONTINUE),
                _ => ::std::option::Option::None
            }
        }

        const VALUES: &'static [AdvantageChoice] = &[
            AdvantageChoice::STOP,
            AdvantageChoice::CONTINUE,
        ];
    }

    impl ::protobuf::EnumFull for AdvantageChoice {
        fn enum_descriptor() -> ::protobuf::reflect::EnumDescriptor {
            static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::EnumDescriptor> = ::protobuf::rt::Lazy::new();
            descriptor.get(|| super::file_descriptor().enum_by_package_relative_name("TeamAdvantageChoice.AdvantageChoice").unwrap()).clone()
        }

        fn descriptor(&self) -> ::protobuf::reflect::EnumValueDescriptor {
            let index = *self as usize;
            Self::enum_descriptor().value_by_index(index)
        }
    }

    impl ::std::default::Default for AdvantageChoice {
        fn default() -> Self {
            AdvantageChoice::STOP
        }
    }

    impl AdvantageChoice {
        pub(in super) fn generated_enum_descriptor_data() -> ::protobuf::reflect::GeneratedEnumDescriptorData {
            ::protobuf::reflect::GeneratedEnumDescriptorData::new::<AdvantageChoice>("TeamAdvantageChoice.AdvantageChoice")
        }
    }
}

// @@protoc_insertion_point(message:GcStateAutoRef)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct GcStateAutoRef {
    // message fields
    // @@protoc_insertion_point(field:GcStateAutoRef.connection_verified)
    pub connection_verified: ::std::option::Option<bool>,
    // special fields
    // @@protoc_insertion_point(special_field:GcStateAutoRef.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a GcStateAutoRef {
    fn default() -> &'a GcStateAutoRef {
        <GcStateAutoRef as ::protobuf::Message>::default_instance()
    }
}

impl GcStateAutoRef {
    pub fn new() -> GcStateAutoRef {
        ::std::default::Default::default()
    }

    // optional bool connection_verified = 1;

    pub fn connection_verified(&self) -> bool {
        self.connection_verified.unwrap_or(false)
    }

    pub fn clear_connection_verified(&mut self) {
        self.connection_verified = ::std::option::Option::None;
    }

    pub fn has_connection_verified(&self) -> bool {
        self.connection_verified.is_some()
    }

    // Param is passed by value, moved
    pub fn set_connection_verified(&mut self, v: bool) {
        self.connection_verified = ::std::option::Option::Some(v);
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(1);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_option_accessor::<_, _>(
            "connection_verified",
            |m: &GcStateAutoRef| { &m.connection_verified },
            |m: &mut GcStateAutoRef| { &mut m.connection_verified },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<GcStateAutoRef>(
            "GcStateAutoRef",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for GcStateAutoRef {
    const NAME: &'static str = "GcStateAutoRef";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                8 => {
                    self.connection_verified = ::std::option::Option::Some(is.read_bool()?);
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if let Some(v) = self.connection_verified {
            my_size += 1 + 1;
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if let Some(v) = self.connection_verified {
            os.write_bool(1, v)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> GcStateAutoRef {
        GcStateAutoRef::new()
    }

    fn clear(&mut self) {
        self.connection_verified = ::std::option::Option::None;
        self.special_fields.clear();
    }

    fn default_instance() -> &'static GcStateAutoRef {
        static instance: GcStateAutoRef = GcStateAutoRef {
            connection_verified: ::std::option::Option::None,
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for GcStateAutoRef {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("GcStateAutoRef").unwrap()).clone()
    }
}

impl ::std::fmt::Display for GcStateAutoRef {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for GcStateAutoRef {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

// @@protoc_insertion_point(message:GcStateTracker)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct GcStateTracker {
    // message fields
    // @@protoc_insertion_point(field:GcStateTracker.source_name)
    pub source_name: ::std::option::Option<::std::string::String>,
    // @@protoc_insertion_point(field:GcStateTracker.uuid)
    pub uuid: ::std::option::Option<::std::string::String>,
    // @@protoc_insertion_point(field:GcStateTracker.ball)
    pub ball: ::protobuf::MessageField<Ball>,
    // @@protoc_insertion_point(field:GcStateTracker.robots)
    pub robots: ::std::vec::Vec<Robot>,
    // special fields
    // @@protoc_insertion_point(special_field:GcStateTracker.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a GcStateTracker {
    fn default() -> &'a GcStateTracker {
        <GcStateTracker as ::protobuf::Message>::default_instance()
    }
}

impl GcStateTracker {
    pub fn new() -> GcStateTracker {
        ::std::default::Default::default()
    }

    // optional string source_name = 1;

    pub fn source_name(&self) -> &str {
        match self.source_name.as_ref() {
            Some(v) => v,
            None => "",
        }
    }

    pub fn clear_source_name(&mut self) {
        self.source_name = ::std::option::Option::None;
    }

    pub fn has_source_name(&self) -> bool {
        self.source_name.is_some()
    }

    // Param is passed by value, moved
    pub fn set_source_name(&mut self, v: ::std::string::String) {
        self.source_name = ::std::option::Option::Some(v);
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_source_name(&mut self) -> &mut ::std::string::String {
        if self.source_name.is_none() {
            self.source_name = ::std::option::Option::Some(::std::string::String::new());
        }
        self.source_name.as_mut().unwrap()
    }

    // Take field
    pub fn take_source_name(&mut self) -> ::std::string::String {
        self.source_name.take().unwrap_or_else(|| ::std::string::String::new())
    }

    // optional string uuid = 4;

    pub fn uuid(&self) -> &str {
        match self.uuid.as_ref() {
            Some(v) => v,
            None => "",
        }
    }

    pub fn clear_uuid(&mut self) {
        self.uuid = ::std::option::Option::None;
    }

    pub fn has_uuid(&self) -> bool {
        self.uuid.is_some()
    }

    // Param is passed by value, moved
    pub fn set_uuid(&mut self, v: ::std::string::String) {
        self.uuid = ::std::option::Option::Some(v);
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_uuid(&mut self) -> &mut ::std::string::String {
        if self.uuid.is_none() {
            self.uuid = ::std::option::Option::Some(::std::string::String::new());
        }
        self.uuid.as_mut().unwrap()
    }

    // Take field
    pub fn take_uuid(&mut self) -> ::std::string::String {
        self.uuid.take().unwrap_or_else(|| ::std::string::String::new())
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(4);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_option_accessor::<_, _>(
            "source_name",
            |m: &GcStateTracker| { &m.source_name },
            |m: &mut GcStateTracker| { &mut m.source_name },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_option_accessor::<_, _>(
            "uuid",
            |m: &GcStateTracker| { &m.uuid },
            |m: &mut GcStateTracker| { &mut m.uuid },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_message_field_accessor::<_, Ball>(
            "ball",
            |m: &GcStateTracker| { &m.ball },
            |m: &mut GcStateTracker| { &mut m.ball },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_vec_simpler_accessor::<_, _>(
            "robots",
            |m: &GcStateTracker| { &m.robots },
            |m: &mut GcStateTracker| { &mut m.robots },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<GcStateTracker>(
            "GcStateTracker",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for GcStateTracker {
    const NAME: &'static str = "GcStateTracker";

    fn is_initialized(&self) -> bool {
        for v in &self.ball {
            if !v.is_initialized() {
                return false;
            }
        };
        for v in &self.robots {
            if !v.is_initialized() {
                return false;
            }
        };
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                10 => {
                    self.source_name = ::std::option::Option::Some(is.read_string()?);
                },
                34 => {
                    self.uuid = ::std::option::Option::Some(is.read_string()?);
                },
                18 => {
                    ::protobuf::rt::read_singular_message_into_field(is, &mut self.ball)?;
                },
                26 => {
                    self.robots.push(is.read_message()?);
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if let Some(v) = self.source_name.as_ref() {
            my_size += ::protobuf::rt::string_size(1, &v);
        }
        if let Some(v) = self.uuid.as_ref() {
            my_size += ::protobuf::rt::string_size(4, &v);
        }
        if let Some(v) = self.ball.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        }
        for value in &self.robots {
            let len = value.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        };
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if let Some(v) = self.source_name.as_ref() {
            os.write_string(1, v)?;
        }
        if let Some(v) = self.uuid.as_ref() {
            os.write_string(4, v)?;
        }
        if let Some(v) = self.ball.as_ref() {
            ::protobuf::rt::write_message_field_with_cached_size(2, v, os)?;
        }
        for v in &self.robots {
            ::protobuf::rt::write_message_field_with_cached_size(3, v, os)?;
        };
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> GcStateTracker {
        GcStateTracker::new()
    }

    fn clear(&mut self) {
        self.source_name = ::std::option::Option::None;
        self.uuid = ::std::option::Option::None;
        self.ball.clear();
        self.robots.clear();
        self.special_fields.clear();
    }

    fn default_instance() -> &'static GcStateTracker {
        static instance: GcStateTracker = GcStateTracker {
            source_name: ::std::option::Option::None,
            uuid: ::std::option::Option::None,
            ball: ::protobuf::MessageField::none(),
            robots: ::std::vec::Vec::new(),
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for GcStateTracker {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("GcStateTracker").unwrap()).clone()
    }
}

impl ::std::fmt::Display for GcStateTracker {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for GcStateTracker {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

// @@protoc_insertion_point(message:Ball)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct Ball {
    // message fields
    // @@protoc_insertion_point(field:Ball.pos)
    pub pos: ::protobuf::MessageField<super::ssl_gc_geometry::Vector3>,
    // @@protoc_insertion_point(field:Ball.vel)
    pub vel: ::protobuf::MessageField<super::ssl_gc_geometry::Vector3>,
    // special fields
    // @@protoc_insertion_point(special_field:Ball.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a Ball {
    fn default() -> &'a Ball {
        <Ball as ::protobuf::Message>::default_instance()
    }
}

impl Ball {
    pub fn new() -> Ball {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(2);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_message_field_accessor::<_, super::ssl_gc_geometry::Vector3>(
            "pos",
            |m: &Ball| { &m.pos },
            |m: &mut Ball| { &mut m.pos },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_message_field_accessor::<_, super::ssl_gc_geometry::Vector3>(
            "vel",
            |m: &Ball| { &m.vel },
            |m: &mut Ball| { &mut m.vel },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<Ball>(
            "Ball",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for Ball {
    const NAME: &'static str = "Ball";

    fn is_initialized(&self) -> bool {
        for v in &self.pos {
            if !v.is_initialized() {
                return false;
            }
        };
        for v in &self.vel {
            if !v.is_initialized() {
                return false;
            }
        };
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                10 => {
                    ::protobuf::rt::read_singular_message_into_field(is, &mut self.pos)?;
                },
                18 => {
                    ::protobuf::rt::read_singular_message_into_field(is, &mut self.vel)?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if let Some(v) = self.pos.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        }
        if let Some(v) = self.vel.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if let Some(v) = self.pos.as_ref() {
            ::protobuf::rt::write_message_field_with_cached_size(1, v, os)?;
        }
        if let Some(v) = self.vel.as_ref() {
            ::protobuf::rt::write_message_field_with_cached_size(2, v, os)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> Ball {
        Ball::new()
    }

    fn clear(&mut self) {
        self.pos.clear();
        self.vel.clear();
        self.special_fields.clear();
    }

    fn default_instance() -> &'static Ball {
        static instance: Ball = Ball {
            pos: ::protobuf::MessageField::none(),
            vel: ::protobuf::MessageField::none(),
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for Ball {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("Ball").unwrap()).clone()
    }
}

impl ::std::fmt::Display for Ball {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for Ball {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

// @@protoc_insertion_point(message:Robot)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct Robot {
    // message fields
    // @@protoc_insertion_point(field:Robot.id)
    pub id: ::protobuf::MessageField<super::ssl_gc_common::RobotId>,
    // @@protoc_insertion_point(field:Robot.pos)
    pub pos: ::protobuf::MessageField<super::ssl_gc_geometry::Vector2>,
    // special fields
    // @@protoc_insertion_point(special_field:Robot.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a Robot {
    fn default() -> &'a Robot {
        <Robot as ::protobuf::Message>::default_instance()
    }
}

impl Robot {
    pub fn new() -> Robot {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(2);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_message_field_accessor::<_, super::ssl_gc_common::RobotId>(
            "id",
            |m: &Robot| { &m.id },
            |m: &mut Robot| { &mut m.id },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_message_field_accessor::<_, super::ssl_gc_geometry::Vector2>(
            "pos",
            |m: &Robot| { &m.pos },
            |m: &mut Robot| { &mut m.pos },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<Robot>(
            "Robot",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for Robot {
    const NAME: &'static str = "Robot";

    fn is_initialized(&self) -> bool {
        for v in &self.id {
            if !v.is_initialized() {
                return false;
            }
        };
        for v in &self.pos {
            if !v.is_initialized() {
                return false;
            }
        };
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                10 => {
                    ::protobuf::rt::read_singular_message_into_field(is, &mut self.id)?;
                },
                18 => {
                    ::protobuf::rt::read_singular_message_into_field(is, &mut self.pos)?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if let Some(v) = self.id.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        }
        if let Some(v) = self.pos.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if let Some(v) = self.id.as_ref() {
            ::protobuf::rt::write_message_field_with_cached_size(1, v, os)?;
        }
        if let Some(v) = self.pos.as_ref() {
            ::protobuf::rt::write_message_field_with_cached_size(2, v, os)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> Robot {
        Robot::new()
    }

    fn clear(&mut self) {
        self.id.clear();
        self.pos.clear();
        self.special_fields.clear();
    }

    fn default_instance() -> &'static Robot {
        static instance: Robot = Robot {
            id: ::protobuf::MessageField::none(),
            pos: ::protobuf::MessageField::none(),
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for Robot {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("Robot").unwrap()).clone()
    }
}

impl ::std::fmt::Display for Robot {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for Robot {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

// @@protoc_insertion_point(message:ContinueAction)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct ContinueAction {
    // message fields
    // @@protoc_insertion_point(field:ContinueAction.type)
    pub type_: ::std::option::Option<::protobuf::EnumOrUnknown<continue_action::Type>>,
    // @@protoc_insertion_point(field:ContinueAction.for_team)
    pub for_team: ::std::option::Option<::protobuf::EnumOrUnknown<super::ssl_gc_common::Team>>,
    // @@protoc_insertion_point(field:ContinueAction.continuation_issues)
    pub continuation_issues: ::std::vec::Vec<::std::string::String>,
    // @@protoc_insertion_point(field:ContinueAction.ready_at)
    pub ready_at: ::protobuf::MessageField<::protobuf::well_known_types::timestamp::Timestamp>,
    // @@protoc_insertion_point(field:ContinueAction.state)
    pub state: ::std::option::Option<::protobuf::EnumOrUnknown<continue_action::State>>,
    // special fields
    // @@protoc_insertion_point(special_field:ContinueAction.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a ContinueAction {
    fn default() -> &'a ContinueAction {
        <ContinueAction as ::protobuf::Message>::default_instance()
    }
}

impl ContinueAction {
    pub fn new() -> ContinueAction {
        ::std::default::Default::default()
    }

    // required .ContinueAction.Type type = 1;

    pub fn type_(&self) -> continue_action::Type {
        match self.type_ {
            Some(e) => e.enum_value_or(continue_action::Type::TYPE_UNKNOWN),
            None => continue_action::Type::TYPE_UNKNOWN,
        }
    }

    pub fn clear_type_(&mut self) {
        self.type_ = ::std::option::Option::None;
    }

    pub fn has_type(&self) -> bool {
        self.type_.is_some()
    }

    // Param is passed by value, moved
    pub fn set_type(&mut self, v: continue_action::Type) {
        self.type_ = ::std::option::Option::Some(::protobuf::EnumOrUnknown::new(v));
    }

    // required .Team for_team = 2;

    pub fn for_team(&self) -> super::ssl_gc_common::Team {
        match self.for_team {
            Some(e) => e.enum_value_or(super::ssl_gc_common::Team::UNKNOWN),
            None => super::ssl_gc_common::Team::UNKNOWN,
        }
    }

    pub fn clear_for_team(&mut self) {
        self.for_team = ::std::option::Option::None;
    }

    pub fn has_for_team(&self) -> bool {
        self.for_team.is_some()
    }

    // Param is passed by value, moved
    pub fn set_for_team(&mut self, v: super::ssl_gc_common::Team) {
        self.for_team = ::std::option::Option::Some(::protobuf::EnumOrUnknown::new(v));
    }

    // optional .ContinueAction.State state = 5;

    pub fn state(&self) -> continue_action::State {
        match self.state {
            Some(e) => e.enum_value_or(continue_action::State::STATE_UNKNOWN),
            None => continue_action::State::STATE_UNKNOWN,
        }
    }

    pub fn clear_state(&mut self) {
        self.state = ::std::option::Option::None;
    }

    pub fn has_state(&self) -> bool {
        self.state.is_some()
    }

    // Param is passed by value, moved
    pub fn set_state(&mut self, v: continue_action::State) {
        self.state = ::std::option::Option::Some(::protobuf::EnumOrUnknown::new(v));
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(5);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_option_accessor::<_, _>(
            "type",
            |m: &ContinueAction| { &m.type_ },
            |m: &mut ContinueAction| { &mut m.type_ },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_option_accessor::<_, _>(
            "for_team",
            |m: &ContinueAction| { &m.for_team },
            |m: &mut ContinueAction| { &mut m.for_team },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_vec_simpler_accessor::<_, _>(
            "continuation_issues",
            |m: &ContinueAction| { &m.continuation_issues },
            |m: &mut ContinueAction| { &mut m.continuation_issues },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_message_field_accessor::<_, ::protobuf::well_known_types::timestamp::Timestamp>(
            "ready_at",
            |m: &ContinueAction| { &m.ready_at },
            |m: &mut ContinueAction| { &mut m.ready_at },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_option_accessor::<_, _>(
            "state",
            |m: &ContinueAction| { &m.state },
            |m: &mut ContinueAction| { &mut m.state },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<ContinueAction>(
            "ContinueAction",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for ContinueAction {
    const NAME: &'static str = "ContinueAction";

    fn is_initialized(&self) -> bool {
        if self.type_.is_none() {
            return false;
        }
        if self.for_team.is_none() {
            return false;
        }
        for v in &self.ready_at {
            if !v.is_initialized() {
                return false;
            }
        };
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                8 => {
                    self.type_ = ::std::option::Option::Some(is.read_enum_or_unknown()?);
                },
                16 => {
                    self.for_team = ::std::option::Option::Some(is.read_enum_or_unknown()?);
                },
                26 => {
                    self.continuation_issues.push(is.read_string()?);
                },
                34 => {
                    ::protobuf::rt::read_singular_message_into_field(is, &mut self.ready_at)?;
                },
                40 => {
                    self.state = ::std::option::Option::Some(is.read_enum_or_unknown()?);
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if let Some(v) = self.type_ {
            my_size += ::protobuf::rt::int32_size(1, v.value());
        }
        if let Some(v) = self.for_team {
            my_size += ::protobuf::rt::int32_size(2, v.value());
        }
        for value in &self.continuation_issues {
            my_size += ::protobuf::rt::string_size(3, &value);
        };
        if let Some(v) = self.ready_at.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        }
        if let Some(v) = self.state {
            my_size += ::protobuf::rt::int32_size(5, v.value());
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if let Some(v) = self.type_ {
            os.write_enum(1, ::protobuf::EnumOrUnknown::value(&v))?;
        }
        if let Some(v) = self.for_team {
            os.write_enum(2, ::protobuf::EnumOrUnknown::value(&v))?;
        }
        for v in &self.continuation_issues {
            os.write_string(3, &v)?;
        };
        if let Some(v) = self.ready_at.as_ref() {
            ::protobuf::rt::write_message_field_with_cached_size(4, v, os)?;
        }
        if let Some(v) = self.state {
            os.write_enum(5, ::protobuf::EnumOrUnknown::value(&v))?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> ContinueAction {
        ContinueAction::new()
    }

    fn clear(&mut self) {
        self.type_ = ::std::option::Option::None;
        self.for_team = ::std::option::Option::None;
        self.continuation_issues.clear();
        self.ready_at.clear();
        self.state = ::std::option::Option::None;
        self.special_fields.clear();
    }

    fn default_instance() -> &'static ContinueAction {
        static instance: ContinueAction = ContinueAction {
            type_: ::std::option::Option::None,
            for_team: ::std::option::Option::None,
            continuation_issues: ::std::vec::Vec::new(),
            ready_at: ::protobuf::MessageField::none(),
            state: ::std::option::Option::None,
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for ContinueAction {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("ContinueAction").unwrap()).clone()
    }
}

impl ::std::fmt::Display for ContinueAction {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for ContinueAction {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

/// Nested message and enums of message `ContinueAction`
pub mod continue_action {
    #[derive(Clone,Copy,PartialEq,Eq,Debug,Hash)]
    // @@protoc_insertion_point(enum:ContinueAction.Type)
    pub enum Type {
        // @@protoc_insertion_point(enum_value:ContinueAction.Type.TYPE_UNKNOWN)
        TYPE_UNKNOWN = 0,
        // @@protoc_insertion_point(enum_value:ContinueAction.Type.HALT)
        HALT = 1,
        // @@protoc_insertion_point(enum_value:ContinueAction.Type.RESUME_FROM_HALT)
        RESUME_FROM_HALT = 10,
        // @@protoc_insertion_point(enum_value:ContinueAction.Type.STOP_GAME)
        STOP_GAME = 2,
        // @@protoc_insertion_point(enum_value:ContinueAction.Type.FORCE_START)
        FORCE_START = 11,
        // @@protoc_insertion_point(enum_value:ContinueAction.Type.FREE_KICK)
        FREE_KICK = 17,
        // @@protoc_insertion_point(enum_value:ContinueAction.Type.NEXT_COMMAND)
        NEXT_COMMAND = 3,
        // @@protoc_insertion_point(enum_value:ContinueAction.Type.BALL_PLACEMENT_START)
        BALL_PLACEMENT_START = 4,
        // @@protoc_insertion_point(enum_value:ContinueAction.Type.BALL_PLACEMENT_CANCEL)
        BALL_PLACEMENT_CANCEL = 9,
        // @@protoc_insertion_point(enum_value:ContinueAction.Type.BALL_PLACEMENT_COMPLETE)
        BALL_PLACEMENT_COMPLETE = 14,
        // @@protoc_insertion_point(enum_value:ContinueAction.Type.BALL_PLACEMENT_FAIL)
        BALL_PLACEMENT_FAIL = 15,
        // @@protoc_insertion_point(enum_value:ContinueAction.Type.TIMEOUT_START)
        TIMEOUT_START = 5,
        // @@protoc_insertion_point(enum_value:ContinueAction.Type.TIMEOUT_STOP)
        TIMEOUT_STOP = 6,
        // @@protoc_insertion_point(enum_value:ContinueAction.Type.BOT_SUBSTITUTION)
        BOT_SUBSTITUTION = 7,
        // @@protoc_insertion_point(enum_value:ContinueAction.Type.NEXT_STAGE)
        NEXT_STAGE = 8,
        // @@protoc_insertion_point(enum_value:ContinueAction.Type.END_GAME)
        END_GAME = 16,
        // @@protoc_insertion_point(enum_value:ContinueAction.Type.ACCEPT_GOAL)
        ACCEPT_GOAL = 12,
        // @@protoc_insertion_point(enum_value:ContinueAction.Type.REJECT_GOAL)
        REJECT_GOAL = 20,
        // @@protoc_insertion_point(enum_value:ContinueAction.Type.NORMAL_START)
        NORMAL_START = 13,
        // @@protoc_insertion_point(enum_value:ContinueAction.Type.CHALLENGE_ACCEPT)
        CHALLENGE_ACCEPT = 18,
        // @@protoc_insertion_point(enum_value:ContinueAction.Type.CHALLENGE_REJECT)
        CHALLENGE_REJECT = 19,
    }

    impl ::protobuf::Enum for Type {
        const NAME: &'static str = "Type";

        fn value(&self) -> i32 {
            *self as i32
        }

        fn from_i32(value: i32) -> ::std::option::Option<Type> {
            match value {
                0 => ::std::option::Option::Some(Type::TYPE_UNKNOWN),
                1 => ::std::option::Option::Some(Type::HALT),
                10 => ::std::option::Option::Some(Type::RESUME_FROM_HALT),
                2 => ::std::option::Option::Some(Type::STOP_GAME),
                11 => ::std::option::Option::Some(Type::FORCE_START),
                17 => ::std::option::Option::Some(Type::FREE_KICK),
                3 => ::std::option::Option::Some(Type::NEXT_COMMAND),
                4 => ::std::option::Option::Some(Type::BALL_PLACEMENT_START),
                9 => ::std::option::Option::Some(Type::BALL_PLACEMENT_CANCEL),
                14 => ::std::option::Option::Some(Type::BALL_PLACEMENT_COMPLETE),
                15 => ::std::option::Option::Some(Type::BALL_PLACEMENT_FAIL),
                5 => ::std::option::Option::Some(Type::TIMEOUT_START),
                6 => ::std::option::Option::Some(Type::TIMEOUT_STOP),
                7 => ::std::option::Option::Some(Type::BOT_SUBSTITUTION),
                8 => ::std::option::Option::Some(Type::NEXT_STAGE),
                16 => ::std::option::Option::Some(Type::END_GAME),
                12 => ::std::option::Option::Some(Type::ACCEPT_GOAL),
                20 => ::std::option::Option::Some(Type::REJECT_GOAL),
                13 => ::std::option::Option::Some(Type::NORMAL_START),
                18 => ::std::option::Option::Some(Type::CHALLENGE_ACCEPT),
                19 => ::std::option::Option::Some(Type::CHALLENGE_REJECT),
                _ => ::std::option::Option::None
            }
        }

        fn from_str(str: &str) -> ::std::option::Option<Type> {
            match str {
                "TYPE_UNKNOWN" => ::std::option::Option::Some(Type::TYPE_UNKNOWN),
                "HALT" => ::std::option::Option::Some(Type::HALT),
                "RESUME_FROM_HALT" => ::std::option::Option::Some(Type::RESUME_FROM_HALT),
                "STOP_GAME" => ::std::option::Option::Some(Type::STOP_GAME),
                "FORCE_START" => ::std::option::Option::Some(Type::FORCE_START),
                "FREE_KICK" => ::std::option::Option::Some(Type::FREE_KICK),
                "NEXT_COMMAND" => ::std::option::Option::Some(Type::NEXT_COMMAND),
                "BALL_PLACEMENT_START" => ::std::option::Option::Some(Type::BALL_PLACEMENT_START),
                "BALL_PLACEMENT_CANCEL" => ::std::option::Option::Some(Type::BALL_PLACEMENT_CANCEL),
                "BALL_PLACEMENT_COMPLETE" => ::std::option::Option::Some(Type::BALL_PLACEMENT_COMPLETE),
                "BALL_PLACEMENT_FAIL" => ::std::option::Option::Some(Type::BALL_PLACEMENT_FAIL),
                "TIMEOUT_START" => ::std::option::Option::Some(Type::TIMEOUT_START),
                "TIMEOUT_STOP" => ::std::option::Option::Some(Type::TIMEOUT_STOP),
                "BOT_SUBSTITUTION" => ::std::option::Option::Some(Type::BOT_SUBSTITUTION),
                "NEXT_STAGE" => ::std::option::Option::Some(Type::NEXT_STAGE),
                "END_GAME" => ::std::option::Option::Some(Type::END_GAME),
                "ACCEPT_GOAL" => ::std::option::Option::Some(Type::ACCEPT_GOAL),
                "REJECT_GOAL" => ::std::option::Option::Some(Type::REJECT_GOAL),
                "NORMAL_START" => ::std::option::Option::Some(Type::NORMAL_START),
                "CHALLENGE_ACCEPT" => ::std::option::Option::Some(Type::CHALLENGE_ACCEPT),
                "CHALLENGE_REJECT" => ::std::option::Option::Some(Type::CHALLENGE_REJECT),
                _ => ::std::option::Option::None
            }
        }

        const VALUES: &'static [Type] = &[
            Type::TYPE_UNKNOWN,
            Type::HALT,
            Type::RESUME_FROM_HALT,
            Type::STOP_GAME,
            Type::FORCE_START,
            Type::FREE_KICK,
            Type::NEXT_COMMAND,
            Type::BALL_PLACEMENT_START,
            Type::BALL_PLACEMENT_CANCEL,
            Type::BALL_PLACEMENT_COMPLETE,
            Type::BALL_PLACEMENT_FAIL,
            Type::TIMEOUT_START,
            Type::TIMEOUT_STOP,
            Type::BOT_SUBSTITUTION,
            Type::NEXT_STAGE,
            Type::END_GAME,
            Type::ACCEPT_GOAL,
            Type::REJECT_GOAL,
            Type::NORMAL_START,
            Type::CHALLENGE_ACCEPT,
            Type::CHALLENGE_REJECT,
        ];
    }

    impl ::protobuf::EnumFull for Type {
        fn enum_descriptor() -> ::protobuf::reflect::EnumDescriptor {
            static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::EnumDescriptor> = ::protobuf::rt::Lazy::new();
            descriptor.get(|| super::file_descriptor().enum_by_package_relative_name("ContinueAction.Type").unwrap()).clone()
        }

        fn descriptor(&self) -> ::protobuf::reflect::EnumValueDescriptor {
            let index = match self {
                Type::TYPE_UNKNOWN => 0,
                Type::HALT => 1,
                Type::RESUME_FROM_HALT => 2,
                Type::STOP_GAME => 3,
                Type::FORCE_START => 4,
                Type::FREE_KICK => 5,
                Type::NEXT_COMMAND => 6,
                Type::BALL_PLACEMENT_START => 7,
                Type::BALL_PLACEMENT_CANCEL => 8,
                Type::BALL_PLACEMENT_COMPLETE => 9,
                Type::BALL_PLACEMENT_FAIL => 10,
                Type::TIMEOUT_START => 11,
                Type::TIMEOUT_STOP => 12,
                Type::BOT_SUBSTITUTION => 13,
                Type::NEXT_STAGE => 14,
                Type::END_GAME => 15,
                Type::ACCEPT_GOAL => 16,
                Type::REJECT_GOAL => 17,
                Type::NORMAL_START => 18,
                Type::CHALLENGE_ACCEPT => 19,
                Type::CHALLENGE_REJECT => 20,
            };
            Self::enum_descriptor().value_by_index(index)
        }
    }

    impl ::std::default::Default for Type {
        fn default() -> Self {
            Type::TYPE_UNKNOWN
        }
    }

    impl Type {
        pub(in super) fn generated_enum_descriptor_data() -> ::protobuf::reflect::GeneratedEnumDescriptorData {
            ::protobuf::reflect::GeneratedEnumDescriptorData::new::<Type>("ContinueAction.Type")
        }
    }

    #[derive(Clone,Copy,PartialEq,Eq,Debug,Hash)]
    // @@protoc_insertion_point(enum:ContinueAction.State)
    pub enum State {
        // @@protoc_insertion_point(enum_value:ContinueAction.State.STATE_UNKNOWN)
        STATE_UNKNOWN = 0,
        // @@protoc_insertion_point(enum_value:ContinueAction.State.BLOCKED)
        BLOCKED = 1,
        // @@protoc_insertion_point(enum_value:ContinueAction.State.WAITING)
        WAITING = 2,
        // @@protoc_insertion_point(enum_value:ContinueAction.State.READY_AUTO)
        READY_AUTO = 3,
        // @@protoc_insertion_point(enum_value:ContinueAction.State.READY_MANUAL)
        READY_MANUAL = 4,
        // @@protoc_insertion_point(enum_value:ContinueAction.State.DISABLED)
        DISABLED = 5,
    }

    impl ::protobuf::Enum for State {
        const NAME: &'static str = "State";

        fn value(&self) -> i32 {
            *self as i32
        }

        fn from_i32(value: i32) -> ::std::option::Option<State> {
            match value {
                0 => ::std::option::Option::Some(State::STATE_UNKNOWN),
                1 => ::std::option::Option::Some(State::BLOCKED),
                2 => ::std::option::Option::Some(State::WAITING),
                3 => ::std::option::Option::Some(State::READY_AUTO),
                4 => ::std::option::Option::Some(State::READY_MANUAL),
                5 => ::std::option::Option::Some(State::DISABLED),
                _ => ::std::option::Option::None
            }
        }

        fn from_str(str: &str) -> ::std::option::Option<State> {
            match str {
                "STATE_UNKNOWN" => ::std::option::Option::Some(State::STATE_UNKNOWN),
                "BLOCKED" => ::std::option::Option::Some(State::BLOCKED),
                "WAITING" => ::std::option::Option::Some(State::WAITING),
                "READY_AUTO" => ::std::option::Option::Some(State::READY_AUTO),
                "READY_MANUAL" => ::std::option::Option::Some(State::READY_MANUAL),
                "DISABLED" => ::std::option::Option::Some(State::DISABLED),
                _ => ::std::option::Option::None
            }
        }

        const VALUES: &'static [State] = &[
            State::STATE_UNKNOWN,
            State::BLOCKED,
            State::WAITING,
            State::READY_AUTO,
            State::READY_MANUAL,
            State::DISABLED,
        ];
    }

    impl ::protobuf::EnumFull for State {
        fn enum_descriptor() -> ::protobuf::reflect::EnumDescriptor {
            static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::EnumDescriptor> = ::protobuf::rt::Lazy::new();
            descriptor.get(|| super::file_descriptor().enum_by_package_relative_name("ContinueAction.State").unwrap()).clone()
        }

        fn descriptor(&self) -> ::protobuf::reflect::EnumValueDescriptor {
            let index = *self as usize;
            Self::enum_descriptor().value_by_index(index)
        }
    }

    impl ::std::default::Default for State {
        fn default() -> Self {
            State::STATE_UNKNOWN
        }
    }

    impl State {
        pub(in super) fn generated_enum_descriptor_data() -> ::protobuf::reflect::GeneratedEnumDescriptorData {
            ::protobuf::reflect::GeneratedEnumDescriptorData::new::<State>("ContinueAction.State")
        }
    }
}

// @@protoc_insertion_point(message:ContinueHint)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct ContinueHint {
    // message fields
    // @@protoc_insertion_point(field:ContinueHint.message)
    pub message: ::std::option::Option<::std::string::String>,
    // special fields
    // @@protoc_insertion_point(special_field:ContinueHint.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a ContinueHint {
    fn default() -> &'a ContinueHint {
        <ContinueHint as ::protobuf::Message>::default_instance()
    }
}

impl ContinueHint {
    pub fn new() -> ContinueHint {
        ::std::default::Default::default()
    }

    // required string message = 1;

    pub fn message(&self) -> &str {
        match self.message.as_ref() {
            Some(v) => v,
            None => "",
        }
    }

    pub fn clear_message(&mut self) {
        self.message = ::std::option::Option::None;
    }

    pub fn has_message(&self) -> bool {
        self.message.is_some()
    }

    // Param is passed by value, moved
    pub fn set_message(&mut self, v: ::std::string::String) {
        self.message = ::std::option::Option::Some(v);
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_message(&mut self) -> &mut ::std::string::String {
        if self.message.is_none() {
            self.message = ::std::option::Option::Some(::std::string::String::new());
        }
        self.message.as_mut().unwrap()
    }

    // Take field
    pub fn take_message(&mut self) -> ::std::string::String {
        self.message.take().unwrap_or_else(|| ::std::string::String::new())
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(1);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_option_accessor::<_, _>(
            "message",
            |m: &ContinueHint| { &m.message },
            |m: &mut ContinueHint| { &mut m.message },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<ContinueHint>(
            "ContinueHint",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for ContinueHint {
    const NAME: &'static str = "ContinueHint";

    fn is_initialized(&self) -> bool {
        if self.message.is_none() {
            return false;
        }
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                10 => {
                    self.message = ::std::option::Option::Some(is.read_string()?);
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if let Some(v) = self.message.as_ref() {
            my_size += ::protobuf::rt::string_size(1, &v);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if let Some(v) = self.message.as_ref() {
            os.write_string(1, v)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> ContinueHint {
        ContinueHint::new()
    }

    fn clear(&mut self) {
        self.message = ::std::option::Option::None;
        self.special_fields.clear();
    }

    fn default_instance() -> &'static ContinueHint {
        static instance: ContinueHint = ContinueHint {
            message: ::std::option::Option::None,
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for ContinueHint {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("ContinueHint").unwrap()).clone()
    }
}

impl ::std::fmt::Display for ContinueHint {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for ContinueHint {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\x13ssl_gc_engine.proto\x1a\x15ssl_gc_geometry.proto\x1a\x13ssl_gc_com\
    mon.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x84\x04\n\x07GcState\
    \x126\n\nteam_state\x18\x01\x20\x03(\x0b2\x17.GcState.TeamStateEntryR\tt\
    eamState\x12@\n\x0eauto_ref_state\x18\x02\x20\x03(\x0b2\x1a.GcState.Auto\
    RefStateEntryR\x0cautoRefState\x122\n\x08trackers\x18\x03\x20\x03(\x0b2\
    \x16.GcState.TrackersEntryR\x08trackers\x12:\n\x10continue_actions\x18\
    \x04\x20\x03(\x0b2\x0f.ContinueActionR\x0fcontinueActions\x124\n\x0econt\
    inue_hints\x18\x05\x20\x03(\x0b2\r.ContinueHintR\rcontinueHints\x1aJ\n\
    \x0eTeamStateEntry\x12\x10\n\x03key\x18\x01\x20\x01(\tR\x03key\x12\"\n\
    \x05value\x18\x02\x20\x01(\x0b2\x0c.GcStateTeamR\x05value:\x028\x01\x1aP\
    \n\x11AutoRefStateEntry\x12\x10\n\x03key\x18\x01\x20\x01(\tR\x03key\x12%\
    \n\x05value\x18\x02\x20\x01(\x0b2\x0f.GcStateAutoRefR\x05value:\x028\x01\
    \x1a;\n\rTrackersEntry\x12\x10\n\x03key\x18\x01\x20\x01(\tR\x03key\x12\
    \x14\n\x05value\x18\x02\x20\x01(\tR\x05value:\x028\x01\"\xa4\x02\n\x0bGc\
    StateTeam\x12\x1c\n\tconnected\x18\x01\x20\x01(\x08R\tconnected\x12/\n\
    \x13connection_verified\x18\x02\x20\x01(\x08R\x12connectionVerified\x128\
    \n\x18remote_control_connected\x18\x03\x20\x01(\x08R\x16remoteControlCon\
    nected\x12K\n\"remote_control_connection_verified\x18\x04\x20\x01(\x08R\
    \x1fremoteControlConnectionVerified\x12?\n\x10advantage_choice\x18\x05\
    \x20\x01(\x0b2\x14.TeamAdvantageChoiceR\x0fadvantageChoice\"~\n\x13TeamA\
    dvantageChoice\x12<\n\x06choice\x18\x01\x20\x01(\x0e2$.TeamAdvantageChoi\
    ce.AdvantageChoiceR\x06choice\")\n\x0fAdvantageChoice\x12\x08\n\x04STOP\
    \x10\0\x12\x0c\n\x08CONTINUE\x10\x01\"A\n\x0eGcStateAutoRef\x12/\n\x13co\
    nnection_verified\x18\x01\x20\x01(\x08R\x12connectionVerified\"\x80\x01\
    \n\x0eGcStateTracker\x12\x1f\n\x0bsource_name\x18\x01\x20\x01(\tR\nsourc\
    eName\x12\x12\n\x04uuid\x18\x04\x20\x01(\tR\x04uuid\x12\x19\n\x04ball\
    \x18\x02\x20\x01(\x0b2\x05.BallR\x04ball\x12\x1e\n\x06robots\x18\x03\x20\
    \x03(\x0b2\x06.RobotR\x06robots\">\n\x04Ball\x12\x1a\n\x03pos\x18\x01\
    \x20\x01(\x0b2\x08.Vector3R\x03pos\x12\x1a\n\x03vel\x18\x02\x20\x01(\x0b\
    2\x08.Vector3R\x03vel\"=\n\x05Robot\x12\x18\n\x02id\x18\x01\x20\x01(\x0b\
    2\x08.RobotIdR\x02id\x12\x1a\n\x03pos\x18\x02\x20\x01(\x0b2\x08.Vector2R\
    \x03pos\"\xf7\x05\n\x0eContinueAction\x12(\n\x04type\x18\x01\x20\x02(\
    \x0e2\x14.ContinueAction.TypeR\x04type\x12\x20\n\x08for_team\x18\x02\x20\
    \x02(\x0e2\x05.TeamR\x07forTeam\x12/\n\x13continuation_issues\x18\x03\
    \x20\x03(\tR\x12continuationIssues\x125\n\x08ready_at\x18\x04\x20\x01(\
    \x0b2\x1a.google.protobuf.TimestampR\x07readyAt\x12+\n\x05state\x18\x05\
    \x20\x01(\x0e2\x15.ContinueAction.StateR\x05state\"\x9d\x03\n\x04Type\
    \x12\x10\n\x0cTYPE_UNKNOWN\x10\0\x12\x08\n\x04HALT\x10\x01\x12\x14\n\x10\
    RESUME_FROM_HALT\x10\n\x12\r\n\tSTOP_GAME\x10\x02\x12\x0f\n\x0bFORCE_STA\
    RT\x10\x0b\x12\r\n\tFREE_KICK\x10\x11\x12\x10\n\x0cNEXT_COMMAND\x10\x03\
    \x12\x18\n\x14BALL_PLACEMENT_START\x10\x04\x12\x19\n\x15BALL_PLACEMENT_C\
    ANCEL\x10\t\x12\x1b\n\x17BALL_PLACEMENT_COMPLETE\x10\x0e\x12\x17\n\x13BA\
    LL_PLACEMENT_FAIL\x10\x0f\x12\x11\n\rTIMEOUT_START\x10\x05\x12\x10\n\x0c\
    TIMEOUT_STOP\x10\x06\x12\x14\n\x10BOT_SUBSTITUTION\x10\x07\x12\x0e\n\nNE\
    XT_STAGE\x10\x08\x12\x0c\n\x08END_GAME\x10\x10\x12\x0f\n\x0bACCEPT_GOAL\
    \x10\x0c\x12\x0f\n\x0bREJECT_GOAL\x10\x14\x12\x10\n\x0cNORMAL_START\x10\
    \r\x12\x14\n\x10CHALLENGE_ACCEPT\x10\x12\x12\x14\n\x10CHALLENGE_REJECT\
    \x10\x13\"d\n\x05State\x12\x11\n\rSTATE_UNKNOWN\x10\0\x12\x0b\n\x07BLOCK\
    ED\x10\x01\x12\x0b\n\x07WAITING\x10\x02\x12\x0e\n\nREADY_AUTO\x10\x03\
    \x12\x10\n\x0cREADY_MANUAL\x10\x04\x12\x0c\n\x08DISABLED\x10\x05\"(\n\
    \x0cContinueHint\x12\x18\n\x07message\x18\x01\x20\x02(\tR\x07messageb\
    \x06proto2\
";

/// `FileDescriptorProto` object which was a source for this generated file
fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    static file_descriptor_proto_lazy: ::protobuf::rt::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::Lazy::new();
    file_descriptor_proto_lazy.get(|| {
        ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
    })
}

/// `FileDescriptor` object which allows dynamic access to files
pub fn file_descriptor() -> &'static ::protobuf::reflect::FileDescriptor {
    static generated_file_descriptor_lazy: ::protobuf::rt::Lazy<::protobuf::reflect::GeneratedFileDescriptor> = ::protobuf::rt::Lazy::new();
    static file_descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::FileDescriptor> = ::protobuf::rt::Lazy::new();
    file_descriptor.get(|| {
        let generated_file_descriptor = generated_file_descriptor_lazy.get(|| {
            let mut deps = ::std::vec::Vec::with_capacity(3);
            deps.push(super::ssl_gc_geometry::file_descriptor().clone());
            deps.push(super::ssl_gc_common::file_descriptor().clone());
            deps.push(::protobuf::well_known_types::timestamp::file_descriptor().clone());
            let mut messages = ::std::vec::Vec::with_capacity(9);
            messages.push(GcState::generated_message_descriptor_data());
            messages.push(GcStateTeam::generated_message_descriptor_data());
            messages.push(TeamAdvantageChoice::generated_message_descriptor_data());
            messages.push(GcStateAutoRef::generated_message_descriptor_data());
            messages.push(GcStateTracker::generated_message_descriptor_data());
            messages.push(Ball::generated_message_descriptor_data());
            messages.push(Robot::generated_message_descriptor_data());
            messages.push(ContinueAction::generated_message_descriptor_data());
            messages.push(ContinueHint::generated_message_descriptor_data());
            let mut enums = ::std::vec::Vec::with_capacity(3);
            enums.push(team_advantage_choice::AdvantageChoice::generated_enum_descriptor_data());
            enums.push(continue_action::Type::generated_enum_descriptor_data());
            enums.push(continue_action::State::generated_enum_descriptor_data());
            ::protobuf::reflect::GeneratedFileDescriptor::new_generated(
                file_descriptor_proto(),
                deps,
                messages,
                enums,
            )
        });
        ::protobuf::reflect::FileDescriptor::new_generated_2(generated_file_descriptor)
    })
}
