// This file is generated by rust-protobuf 3.7.2. Do not edit
// .proto file is parsed by pure
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_results)]
#![allow(unused_mut)]

//! Generated file from `ssl_gc_common.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_3_7_2;

// @@protoc_insertion_point(message:RobotId)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct RobotId {
    // message fields
    // @@protoc_insertion_point(field:RobotId.id)
    pub id: ::std::option::Option<u32>,
    // @@protoc_insertion_point(field:RobotId.team)
    pub team: ::std::option::Option<::protobuf::EnumOrUnknown<Team>>,
    // special fields
    // @@protoc_insertion_point(special_field:RobotId.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a RobotId {
    fn default() -> &'a RobotId {
        <RobotId as ::protobuf::Message>::default_instance()
    }
}

impl RobotId {
    pub fn new() -> RobotId {
        ::std::default::Default::default()
    }

    // optional uint32 id = 1;

    pub fn id(&self) -> u32 {
        self.id.unwrap_or(0)
    }

    pub fn clear_id(&mut self) {
        self.id = ::std::option::Option::None;
    }

    pub fn has_id(&self) -> bool {
        self.id.is_some()
    }

    // Param is passed by value, moved
    pub fn set_id(&mut self, v: u32) {
        self.id = ::std::option::Option::Some(v);
    }

    // optional .Team team = 2;

    pub fn team(&self) -> Team {
        match self.team {
            Some(e) => e.enum_value_or(Team::UNKNOWN),
            None => Team::UNKNOWN,
        }
    }

    pub fn clear_team(&mut self) {
        self.team = ::std::option::Option::None;
    }

    pub fn has_team(&self) -> bool {
        self.team.is_some()
    }

    // Param is passed by value, moved
    pub fn set_team(&mut self, v: Team) {
        self.team = ::std::option::Option::Some(::protobuf::EnumOrUnknown::new(v));
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(2);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_option_accessor::<_, _>(
            "id",
            |m: &RobotId| { &m.id },
            |m: &mut RobotId| { &mut m.id },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_option_accessor::<_, _>(
            "team",
            |m: &RobotId| { &m.team },
            |m: &mut RobotId| { &mut m.team },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<RobotId>(
            "RobotId",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for RobotId {
    const NAME: &'static str = "RobotId";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                8 => {
                    self.id = ::std::option::Option::Some(is.read_uint32()?);
                },
                16 => {
                    self.team = ::std::option::Option::Some(is.read_enum_or_unknown()?);
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if let Some(v) = self.id {
            my_size += ::protobuf::rt::uint32_size(1, v);
        }
        if let Some(v) = self.team {
            my_size += ::protobuf::rt::int32_size(2, v.value());
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if let Some(v) = self.id {
            os.write_uint32(1, v)?;
        }
        if let Some(v) = self.team {
            os.write_enum(2, ::protobuf::EnumOrUnknown::value(&v))?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> RobotId {
        RobotId::new()
    }

    fn clear(&mut self) {
        self.id = ::std::option::Option::None;
        self.team = ::std::option::Option::None;
        self.special_fields.clear();
    }

    fn default_instance() -> &'static RobotId {
        static instance: RobotId = RobotId {
            id: ::std::option::Option::None,
            team: ::std::option::Option::None,
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for RobotId {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("RobotId").unwrap()).clone()
    }
}

impl ::std::fmt::Display for RobotId {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for RobotId {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

#[derive(Clone,Copy,PartialEq,Eq,Debug,Hash)]
// @@protoc_insertion_point(enum:Team)
pub enum Team {
    // @@protoc_insertion_point(enum_value:Team.UNKNOWN)
    UNKNOWN = 0,
    // @@protoc_insertion_point(enum_value:Team.YELLOW)
    YELLOW = 1,
    // @@protoc_insertion_point(enum_value:Team.BLUE)
    BLUE = 2,
}

impl ::protobuf::Enum for Team {
    const NAME: &'static str = "Team";

    fn value(&self) -> i32 {
        *self as i32
    }

    fn from_i32(value: i32) -> ::std::option::Option<Team> {
        match value {
            0 => ::std::option::Option::Some(Team::UNKNOWN),
            1 => ::std::option::Option::Some(Team::YELLOW),
            2 => ::std::option::Option::Some(Team::BLUE),
            _ => ::std::option::Option::None
        }
    }

    fn from_str(str: &str) -> ::std::option::Option<Team> {
        match str {
            "UNKNOWN" => ::std::option::Option::Some(Team::UNKNOWN),
            "YELLOW" => ::std::option::Option::Some(Team::YELLOW),
            "BLUE" => ::std::option::Option::Some(Team::BLUE),
            _ => ::std::option::Option::None
        }
    }

    const VALUES: &'static [Team] = &[
        Team::UNKNOWN,
        Team::YELLOW,
        Team::BLUE,
    ];
}

impl ::protobuf::EnumFull for Team {
    fn enum_descriptor() -> ::protobuf::reflect::EnumDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::EnumDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().enum_by_package_relative_name("Team").unwrap()).clone()
    }

    fn descriptor(&self) -> ::protobuf::reflect::EnumValueDescriptor {
        let index = *self as usize;
        Self::enum_descriptor().value_by_index(index)
    }
}

impl ::std::default::Default for Team {
    fn default() -> Self {
        Team::UNKNOWN
    }
}

impl Team {
    fn generated_enum_descriptor_data() -> ::protobuf::reflect::GeneratedEnumDescriptorData {
        ::protobuf::reflect::GeneratedEnumDescriptorData::new::<Team>("Team")
    }
}

#[derive(Clone,Copy,PartialEq,Eq,Debug,Hash)]
// @@protoc_insertion_point(enum:Division)
pub enum Division {
    // @@protoc_insertion_point(enum_value:Division.DIV_UNKNOWN)
    DIV_UNKNOWN = 0,
    // @@protoc_insertion_point(enum_value:Division.DIV_A)
    DIV_A = 1,
    // @@protoc_insertion_point(enum_value:Division.DIV_B)
    DIV_B = 2,
}

impl ::protobuf::Enum for Division {
    const NAME: &'static str = "Division";

    fn value(&self) -> i32 {
        *self as i32
    }

    fn from_i32(value: i32) -> ::std::option::Option<Division> {
        match value {
            0 => ::std::option::Option::Some(Division::DIV_UNKNOWN),
            1 => ::std::option::Option::Some(Division::DIV_A),
            2 => ::std::option::Option::Some(Division::DIV_B),
            _ => ::std::option::Option::None
        }
    }

    fn from_str(str: &str) -> ::std::option::Option<Division> {
        match str {
            "DIV_UNKNOWN" => ::std::option::Option::Some(Division::DIV_UNKNOWN),
            "DIV_A" => ::std::option::Option::Some(Division::DIV_A),
            "DIV_B" => ::std::option::Option::Some(Division::DIV_B),
            _ => ::std::option::Option::None
        }
    }

    const VALUES: &'static [Division] = &[
        Division::DIV_UNKNOWN,
        Division::DIV_A,
        Division::DIV_B,
    ];
}

impl ::protobuf::EnumFull for Division {
    fn enum_descriptor() -> ::protobuf::reflect::EnumDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::EnumDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().enum_by_package_relative_name("Division").unwrap()).clone()
    }

    fn descriptor(&self) -> ::protobuf::reflect::EnumValueDescriptor {
        let index = *self as usize;
        Self::enum_descriptor().value_by_index(index)
    }
}

impl ::std::default::Default for Division {
    fn default() -> Self {
        Division::DIV_UNKNOWN
    }
}

impl Division {
    fn generated_enum_descriptor_data() -> ::protobuf::reflect::GeneratedEnumDescriptorData {
        ::protobuf::reflect::GeneratedEnumDescriptorData::new::<Division>("Division")
    }
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\x13ssl_gc_common.proto\"4\n\x07RobotId\x12\x0e\n\x02id\x18\x01\x20\
    \x01(\rR\x02id\x12\x19\n\x04team\x18\x02\x20\x01(\x0e2\x05.TeamR\x04team\
    *)\n\x04Team\x12\x0b\n\x07UNKNOWN\x10\0\x12\n\n\x06YELLOW\x10\x01\x12\
    \x08\n\x04BLUE\x10\x02*1\n\x08Division\x12\x0f\n\x0bDIV_UNKNOWN\x10\0\
    \x12\t\n\x05DIV_A\x10\x01\x12\t\n\x05DIV_B\x10\x02b\x06proto2\
";

/// `FileDescriptorProto` object which was a source for this generated file
fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    static file_descriptor_proto_lazy: ::protobuf::rt::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::Lazy::new();
    file_descriptor_proto_lazy.get(|| {
        ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
    })
}

/// `FileDescriptor` object which allows dynamic access to files
pub fn file_descriptor() -> &'static ::protobuf::reflect::FileDescriptor {
    static generated_file_descriptor_lazy: ::protobuf::rt::Lazy<::protobuf::reflect::GeneratedFileDescriptor> = ::protobuf::rt::Lazy::new();
    static file_descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::FileDescriptor> = ::protobuf::rt::Lazy::new();
    file_descriptor.get(|| {
        let generated_file_descriptor = generated_file_descriptor_lazy.get(|| {
            let mut deps = ::std::vec::Vec::with_capacity(0);
            let mut messages = ::std::vec::Vec::with_capacity(1);
            messages.push(RobotId::generated_message_descriptor_data());
            let mut enums = ::std::vec::Vec::with_capacity(2);
            enums.push(Team::generated_enum_descriptor_data());
            enums.push(Division::generated_enum_descriptor_data());
            ::protobuf::reflect::GeneratedFileDescriptor::new_generated(
                file_descriptor_proto(),
                deps,
                messages,
                enums,
            )
        });
        ::protobuf::reflect::FileDescriptor::new_generated_2(generated_file_descriptor)
    })
}
