// This file is generated by rust-protobuf 3.7.2. Do not edit
// .proto file is parsed by pure
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_results)]
#![allow(unused_mut)]

//! Generated file from `ssl_gc_rcon_remotecontrol.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_3_7_2;

// @@protoc_insertion_point(message:RemoteControlRegistration)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct RemoteControlRegistration {
    // message fields
    // @@protoc_insertion_point(field:RemoteControlRegistration.team)
    pub team: ::std::option::Option<::protobuf::EnumOrUnknown<super::ssl_gc_common::Team>>,
    // @@protoc_insertion_point(field:RemoteControlRegistration.signature)
    pub signature: ::protobuf::MessageField<super::ssl_gc_rcon::Signature>,
    // special fields
    // @@protoc_insertion_point(special_field:RemoteControlRegistration.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a RemoteControlRegistration {
    fn default() -> &'a RemoteControlRegistration {
        <RemoteControlRegistration as ::protobuf::Message>::default_instance()
    }
}

impl RemoteControlRegistration {
    pub fn new() -> RemoteControlRegistration {
        ::std::default::Default::default()
    }

    // required .Team team = 1;

    pub fn team(&self) -> super::ssl_gc_common::Team {
        match self.team {
            Some(e) => e.enum_value_or(super::ssl_gc_common::Team::UNKNOWN),
            None => super::ssl_gc_common::Team::UNKNOWN,
        }
    }

    pub fn clear_team(&mut self) {
        self.team = ::std::option::Option::None;
    }

    pub fn has_team(&self) -> bool {
        self.team.is_some()
    }

    // Param is passed by value, moved
    pub fn set_team(&mut self, v: super::ssl_gc_common::Team) {
        self.team = ::std::option::Option::Some(::protobuf::EnumOrUnknown::new(v));
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(2);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_option_accessor::<_, _>(
            "team",
            |m: &RemoteControlRegistration| { &m.team },
            |m: &mut RemoteControlRegistration| { &mut m.team },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_message_field_accessor::<_, super::ssl_gc_rcon::Signature>(
            "signature",
            |m: &RemoteControlRegistration| { &m.signature },
            |m: &mut RemoteControlRegistration| { &mut m.signature },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<RemoteControlRegistration>(
            "RemoteControlRegistration",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for RemoteControlRegistration {
    const NAME: &'static str = "RemoteControlRegistration";

    fn is_initialized(&self) -> bool {
        if self.team.is_none() {
            return false;
        }
        for v in &self.signature {
            if !v.is_initialized() {
                return false;
            }
        };
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                8 => {
                    self.team = ::std::option::Option::Some(is.read_enum_or_unknown()?);
                },
                18 => {
                    ::protobuf::rt::read_singular_message_into_field(is, &mut self.signature)?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if let Some(v) = self.team {
            my_size += ::protobuf::rt::int32_size(1, v.value());
        }
        if let Some(v) = self.signature.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if let Some(v) = self.team {
            os.write_enum(1, ::protobuf::EnumOrUnknown::value(&v))?;
        }
        if let Some(v) = self.signature.as_ref() {
            ::protobuf::rt::write_message_field_with_cached_size(2, v, os)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> RemoteControlRegistration {
        RemoteControlRegistration::new()
    }

    fn clear(&mut self) {
        self.team = ::std::option::Option::None;
        self.signature.clear();
        self.special_fields.clear();
    }

    fn default_instance() -> &'static RemoteControlRegistration {
        static instance: RemoteControlRegistration = RemoteControlRegistration {
            team: ::std::option::Option::None,
            signature: ::protobuf::MessageField::none(),
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for RemoteControlRegistration {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("RemoteControlRegistration").unwrap()).clone()
    }
}

impl ::std::fmt::Display for RemoteControlRegistration {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for RemoteControlRegistration {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

// @@protoc_insertion_point(message:RemoteControlToController)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct RemoteControlToController {
    // message fields
    // @@protoc_insertion_point(field:RemoteControlToController.signature)
    pub signature: ::protobuf::MessageField<super::ssl_gc_rcon::Signature>,
    // message oneof groups
    pub msg: ::std::option::Option<remote_control_to_controller::Msg>,
    // special fields
    // @@protoc_insertion_point(special_field:RemoteControlToController.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a RemoteControlToController {
    fn default() -> &'a RemoteControlToController {
        <RemoteControlToController as ::protobuf::Message>::default_instance()
    }
}

impl RemoteControlToController {
    pub fn new() -> RemoteControlToController {
        ::std::default::Default::default()
    }

    // optional .RemoteControlToController.Request request = 2;

    pub fn request(&self) -> remote_control_to_controller::Request {
        match self.msg {
            ::std::option::Option::Some(remote_control_to_controller::Msg::Request(v)) => ::protobuf::EnumOrUnknown::enum_value_or_default(&v),
            _ => remote_control_to_controller::Request::UNKNOWN,
        }
    }

    pub fn clear_request(&mut self) {
        self.msg = ::std::option::Option::None;
    }

    pub fn has_request(&self) -> bool {
        match self.msg {
            ::std::option::Option::Some(remote_control_to_controller::Msg::Request(..)) => true,
            _ => false,
        }
    }

    // Param is passed by value, moved
    pub fn set_request(&mut self, v: remote_control_to_controller::Request) {
        self.msg = ::std::option::Option::Some(remote_control_to_controller::Msg::Request(::protobuf::EnumOrUnknown::new(v)))
    }

    // optional int32 desired_keeper = 3;

    pub fn desired_keeper(&self) -> i32 {
        match self.msg {
            ::std::option::Option::Some(remote_control_to_controller::Msg::DesiredKeeper(v)) => v,
            _ => 0,
        }
    }

    pub fn clear_desired_keeper(&mut self) {
        self.msg = ::std::option::Option::None;
    }

    pub fn has_desired_keeper(&self) -> bool {
        match self.msg {
            ::std::option::Option::Some(remote_control_to_controller::Msg::DesiredKeeper(..)) => true,
            _ => false,
        }
    }

    // Param is passed by value, moved
    pub fn set_desired_keeper(&mut self, v: i32) {
        self.msg = ::std::option::Option::Some(remote_control_to_controller::Msg::DesiredKeeper(v))
    }

    // optional bool request_robot_substitution = 4;

    pub fn request_robot_substitution(&self) -> bool {
        match self.msg {
            ::std::option::Option::Some(remote_control_to_controller::Msg::RequestRobotSubstitution(v)) => v,
            _ => false,
        }
    }

    pub fn clear_request_robot_substitution(&mut self) {
        self.msg = ::std::option::Option::None;
    }

    pub fn has_request_robot_substitution(&self) -> bool {
        match self.msg {
            ::std::option::Option::Some(remote_control_to_controller::Msg::RequestRobotSubstitution(..)) => true,
            _ => false,
        }
    }

    // Param is passed by value, moved
    pub fn set_request_robot_substitution(&mut self, v: bool) {
        self.msg = ::std::option::Option::Some(remote_control_to_controller::Msg::RequestRobotSubstitution(v))
    }

    // optional bool request_timeout = 5;

    pub fn request_timeout(&self) -> bool {
        match self.msg {
            ::std::option::Option::Some(remote_control_to_controller::Msg::RequestTimeout(v)) => v,
            _ => false,
        }
    }

    pub fn clear_request_timeout(&mut self) {
        self.msg = ::std::option::Option::None;
    }

    pub fn has_request_timeout(&self) -> bool {
        match self.msg {
            ::std::option::Option::Some(remote_control_to_controller::Msg::RequestTimeout(..)) => true,
            _ => false,
        }
    }

    // Param is passed by value, moved
    pub fn set_request_timeout(&mut self, v: bool) {
        self.msg = ::std::option::Option::Some(remote_control_to_controller::Msg::RequestTimeout(v))
    }

    // optional bool request_emergency_stop = 6;

    pub fn request_emergency_stop(&self) -> bool {
        match self.msg {
            ::std::option::Option::Some(remote_control_to_controller::Msg::RequestEmergencyStop(v)) => v,
            _ => false,
        }
    }

    pub fn clear_request_emergency_stop(&mut self) {
        self.msg = ::std::option::Option::None;
    }

    pub fn has_request_emergency_stop(&self) -> bool {
        match self.msg {
            ::std::option::Option::Some(remote_control_to_controller::Msg::RequestEmergencyStop(..)) => true,
            _ => false,
        }
    }

    // Param is passed by value, moved
    pub fn set_request_emergency_stop(&mut self, v: bool) {
        self.msg = ::std::option::Option::Some(remote_control_to_controller::Msg::RequestEmergencyStop(v))
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(6);
        let mut oneofs = ::std::vec::Vec::with_capacity(1);
        fields.push(::protobuf::reflect::rt::v2::make_message_field_accessor::<_, super::ssl_gc_rcon::Signature>(
            "signature",
            |m: &RemoteControlToController| { &m.signature },
            |m: &mut RemoteControlToController| { &mut m.signature },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_oneof_enum_accessors::<_, _>(
            "request",
            |message: &RemoteControlToController| match &message.msg {
                ::std::option::Option::Some(remote_control_to_controller::Msg::Request(e)) => ::std::option::Option::Some(*e),
                _ => ::std::option::Option::None,
            },
            |message: &mut RemoteControlToController, e: ::protobuf::EnumOrUnknown<remote_control_to_controller::Request>| {
                message.msg = ::std::option::Option::Some(remote_control_to_controller::Msg::Request(e));
            },
            remote_control_to_controller::Request::UNKNOWN,
        ));
        fields.push(::protobuf::reflect::rt::v2::make_oneof_copy_has_get_set_simpler_accessors::<_, _>(
            "desired_keeper",
            RemoteControlToController::has_desired_keeper,
            RemoteControlToController::desired_keeper,
            RemoteControlToController::set_desired_keeper,
        ));
        fields.push(::protobuf::reflect::rt::v2::make_oneof_copy_has_get_set_simpler_accessors::<_, _>(
            "request_robot_substitution",
            RemoteControlToController::has_request_robot_substitution,
            RemoteControlToController::request_robot_substitution,
            RemoteControlToController::set_request_robot_substitution,
        ));
        fields.push(::protobuf::reflect::rt::v2::make_oneof_copy_has_get_set_simpler_accessors::<_, _>(
            "request_timeout",
            RemoteControlToController::has_request_timeout,
            RemoteControlToController::request_timeout,
            RemoteControlToController::set_request_timeout,
        ));
        fields.push(::protobuf::reflect::rt::v2::make_oneof_copy_has_get_set_simpler_accessors::<_, _>(
            "request_emergency_stop",
            RemoteControlToController::has_request_emergency_stop,
            RemoteControlToController::request_emergency_stop,
            RemoteControlToController::set_request_emergency_stop,
        ));
        oneofs.push(remote_control_to_controller::Msg::generated_oneof_descriptor_data());
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<RemoteControlToController>(
            "RemoteControlToController",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for RemoteControlToController {
    const NAME: &'static str = "RemoteControlToController";

    fn is_initialized(&self) -> bool {
        for v in &self.signature {
            if !v.is_initialized() {
                return false;
            }
        };
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                10 => {
                    ::protobuf::rt::read_singular_message_into_field(is, &mut self.signature)?;
                },
                16 => {
                    self.msg = ::std::option::Option::Some(remote_control_to_controller::Msg::Request(is.read_enum_or_unknown()?));
                },
                24 => {
                    self.msg = ::std::option::Option::Some(remote_control_to_controller::Msg::DesiredKeeper(is.read_int32()?));
                },
                32 => {
                    self.msg = ::std::option::Option::Some(remote_control_to_controller::Msg::RequestRobotSubstitution(is.read_bool()?));
                },
                40 => {
                    self.msg = ::std::option::Option::Some(remote_control_to_controller::Msg::RequestTimeout(is.read_bool()?));
                },
                48 => {
                    self.msg = ::std::option::Option::Some(remote_control_to_controller::Msg::RequestEmergencyStop(is.read_bool()?));
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if let Some(v) = self.signature.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        }
        if let ::std::option::Option::Some(ref v) = self.msg {
            match v {
                &remote_control_to_controller::Msg::Request(v) => {
                    my_size += ::protobuf::rt::int32_size(2, v.value());
                },
                &remote_control_to_controller::Msg::DesiredKeeper(v) => {
                    my_size += ::protobuf::rt::int32_size(3, v);
                },
                &remote_control_to_controller::Msg::RequestRobotSubstitution(v) => {
                    my_size += 1 + 1;
                },
                &remote_control_to_controller::Msg::RequestTimeout(v) => {
                    my_size += 1 + 1;
                },
                &remote_control_to_controller::Msg::RequestEmergencyStop(v) => {
                    my_size += 1 + 1;
                },
            };
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if let Some(v) = self.signature.as_ref() {
            ::protobuf::rt::write_message_field_with_cached_size(1, v, os)?;
        }
        if let ::std::option::Option::Some(ref v) = self.msg {
            match v {
                &remote_control_to_controller::Msg::Request(v) => {
                    os.write_enum(2, ::protobuf::EnumOrUnknown::value(&v))?;
                },
                &remote_control_to_controller::Msg::DesiredKeeper(v) => {
                    os.write_int32(3, v)?;
                },
                &remote_control_to_controller::Msg::RequestRobotSubstitution(v) => {
                    os.write_bool(4, v)?;
                },
                &remote_control_to_controller::Msg::RequestTimeout(v) => {
                    os.write_bool(5, v)?;
                },
                &remote_control_to_controller::Msg::RequestEmergencyStop(v) => {
                    os.write_bool(6, v)?;
                },
            };
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> RemoteControlToController {
        RemoteControlToController::new()
    }

    fn clear(&mut self) {
        self.signature.clear();
        self.msg = ::std::option::Option::None;
        self.msg = ::std::option::Option::None;
        self.msg = ::std::option::Option::None;
        self.msg = ::std::option::Option::None;
        self.msg = ::std::option::Option::None;
        self.special_fields.clear();
    }

    fn default_instance() -> &'static RemoteControlToController {
        static instance: RemoteControlToController = RemoteControlToController {
            signature: ::protobuf::MessageField::none(),
            msg: ::std::option::Option::None,
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for RemoteControlToController {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("RemoteControlToController").unwrap()).clone()
    }
}

impl ::std::fmt::Display for RemoteControlToController {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for RemoteControlToController {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

/// Nested message and enums of message `RemoteControlToController`
pub mod remote_control_to_controller {

    #[derive(Clone,PartialEq,Debug)]
    #[non_exhaustive]
    // @@protoc_insertion_point(oneof:RemoteControlToController.msg)
    pub enum Msg {
        // @@protoc_insertion_point(oneof_field:RemoteControlToController.request)
        Request(::protobuf::EnumOrUnknown<Request>),
        // @@protoc_insertion_point(oneof_field:RemoteControlToController.desired_keeper)
        DesiredKeeper(i32),
        // @@protoc_insertion_point(oneof_field:RemoteControlToController.request_robot_substitution)
        RequestRobotSubstitution(bool),
        // @@protoc_insertion_point(oneof_field:RemoteControlToController.request_timeout)
        RequestTimeout(bool),
        // @@protoc_insertion_point(oneof_field:RemoteControlToController.request_emergency_stop)
        RequestEmergencyStop(bool),
    }

    impl ::protobuf::Oneof for Msg {
    }

    impl ::protobuf::OneofFull for Msg {
        fn descriptor() -> ::protobuf::reflect::OneofDescriptor {
            static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::OneofDescriptor> = ::protobuf::rt::Lazy::new();
            descriptor.get(|| <super::RemoteControlToController as ::protobuf::MessageFull>::descriptor().oneof_by_name("msg").unwrap()).clone()
        }
    }

    impl Msg {
        pub(in super) fn generated_oneof_descriptor_data() -> ::protobuf::reflect::GeneratedOneofDescriptorData {
            ::protobuf::reflect::GeneratedOneofDescriptorData::new::<Msg>("msg")
        }
    }
    #[derive(Clone,Copy,PartialEq,Eq,Debug,Hash)]
    // @@protoc_insertion_point(enum:RemoteControlToController.Request)
    pub enum Request {
        // @@protoc_insertion_point(enum_value:RemoteControlToController.Request.UNKNOWN)
        UNKNOWN = 0,
        // @@protoc_insertion_point(enum_value:RemoteControlToController.Request.PING)
        PING = 1,
        // @@protoc_insertion_point(enum_value:RemoteControlToController.Request.CHALLENGE_FLAG)
        CHALLENGE_FLAG = 2,
        // @@protoc_insertion_point(enum_value:RemoteControlToController.Request.STOP_TIMEOUT)
        STOP_TIMEOUT = 3,
        // @@protoc_insertion_point(enum_value:RemoteControlToController.Request.FAIL_BALLPLACEMENT)
        FAIL_BALLPLACEMENT = 4,
    }

    impl ::protobuf::Enum for Request {
        const NAME: &'static str = "Request";

        fn value(&self) -> i32 {
            *self as i32
        }

        fn from_i32(value: i32) -> ::std::option::Option<Request> {
            match value {
                0 => ::std::option::Option::Some(Request::UNKNOWN),
                1 => ::std::option::Option::Some(Request::PING),
                2 => ::std::option::Option::Some(Request::CHALLENGE_FLAG),
                3 => ::std::option::Option::Some(Request::STOP_TIMEOUT),
                4 => ::std::option::Option::Some(Request::FAIL_BALLPLACEMENT),
                _ => ::std::option::Option::None
            }
        }

        fn from_str(str: &str) -> ::std::option::Option<Request> {
            match str {
                "UNKNOWN" => ::std::option::Option::Some(Request::UNKNOWN),
                "PING" => ::std::option::Option::Some(Request::PING),
                "CHALLENGE_FLAG" => ::std::option::Option::Some(Request::CHALLENGE_FLAG),
                "STOP_TIMEOUT" => ::std::option::Option::Some(Request::STOP_TIMEOUT),
                "FAIL_BALLPLACEMENT" => ::std::option::Option::Some(Request::FAIL_BALLPLACEMENT),
                _ => ::std::option::Option::None
            }
        }

        const VALUES: &'static [Request] = &[
            Request::UNKNOWN,
            Request::PING,
            Request::CHALLENGE_FLAG,
            Request::STOP_TIMEOUT,
            Request::FAIL_BALLPLACEMENT,
        ];
    }

    impl ::protobuf::EnumFull for Request {
        fn enum_descriptor() -> ::protobuf::reflect::EnumDescriptor {
            static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::EnumDescriptor> = ::protobuf::rt::Lazy::new();
            descriptor.get(|| super::file_descriptor().enum_by_package_relative_name("RemoteControlToController.Request").unwrap()).clone()
        }

        fn descriptor(&self) -> ::protobuf::reflect::EnumValueDescriptor {
            let index = *self as usize;
            Self::enum_descriptor().value_by_index(index)
        }
    }

    impl ::std::default::Default for Request {
        fn default() -> Self {
            Request::UNKNOWN
        }
    }

    impl Request {
        pub(in super) fn generated_enum_descriptor_data() -> ::protobuf::reflect::GeneratedEnumDescriptorData {
            ::protobuf::reflect::GeneratedEnumDescriptorData::new::<Request>("RemoteControlToController.Request")
        }
    }
}

// @@protoc_insertion_point(message:ControllerToRemoteControl)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct ControllerToRemoteControl {
    // message fields
    // @@protoc_insertion_point(field:ControllerToRemoteControl.controller_reply)
    pub controller_reply: ::protobuf::MessageField<super::ssl_gc_rcon::ControllerReply>,
    // @@protoc_insertion_point(field:ControllerToRemoteControl.state)
    pub state: ::protobuf::MessageField<RemoteControlTeamState>,
    // special fields
    // @@protoc_insertion_point(special_field:ControllerToRemoteControl.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a ControllerToRemoteControl {
    fn default() -> &'a ControllerToRemoteControl {
        <ControllerToRemoteControl as ::protobuf::Message>::default_instance()
    }
}

impl ControllerToRemoteControl {
    pub fn new() -> ControllerToRemoteControl {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(2);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_message_field_accessor::<_, super::ssl_gc_rcon::ControllerReply>(
            "controller_reply",
            |m: &ControllerToRemoteControl| { &m.controller_reply },
            |m: &mut ControllerToRemoteControl| { &mut m.controller_reply },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_message_field_accessor::<_, RemoteControlTeamState>(
            "state",
            |m: &ControllerToRemoteControl| { &m.state },
            |m: &mut ControllerToRemoteControl| { &mut m.state },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<ControllerToRemoteControl>(
            "ControllerToRemoteControl",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for ControllerToRemoteControl {
    const NAME: &'static str = "ControllerToRemoteControl";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                10 => {
                    ::protobuf::rt::read_singular_message_into_field(is, &mut self.controller_reply)?;
                },
                18 => {
                    ::protobuf::rt::read_singular_message_into_field(is, &mut self.state)?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if let Some(v) = self.controller_reply.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        }
        if let Some(v) = self.state.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if let Some(v) = self.controller_reply.as_ref() {
            ::protobuf::rt::write_message_field_with_cached_size(1, v, os)?;
        }
        if let Some(v) = self.state.as_ref() {
            ::protobuf::rt::write_message_field_with_cached_size(2, v, os)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> ControllerToRemoteControl {
        ControllerToRemoteControl::new()
    }

    fn clear(&mut self) {
        self.controller_reply.clear();
        self.state.clear();
        self.special_fields.clear();
    }

    fn default_instance() -> &'static ControllerToRemoteControl {
        static instance: ControllerToRemoteControl = ControllerToRemoteControl {
            controller_reply: ::protobuf::MessageField::none(),
            state: ::protobuf::MessageField::none(),
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for ControllerToRemoteControl {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("ControllerToRemoteControl").unwrap()).clone()
    }
}

impl ::std::fmt::Display for ControllerToRemoteControl {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for ControllerToRemoteControl {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

// @@protoc_insertion_point(message:RemoteControlTeamState)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct RemoteControlTeamState {
    // message fields
    // @@protoc_insertion_point(field:RemoteControlTeamState.team)
    pub team: ::std::option::Option<::protobuf::EnumOrUnknown<super::ssl_gc_common::Team>>,
    // @@protoc_insertion_point(field:RemoteControlTeamState.available_requests)
    pub available_requests: ::std::vec::Vec<::protobuf::EnumOrUnknown<RemoteControlRequestType>>,
    // @@protoc_insertion_point(field:RemoteControlTeamState.active_requests)
    pub active_requests: ::std::vec::Vec<::protobuf::EnumOrUnknown<RemoteControlRequestType>>,
    // @@protoc_insertion_point(field:RemoteControlTeamState.keeper_id)
    pub keeper_id: ::std::option::Option<i32>,
    // @@protoc_insertion_point(field:RemoteControlTeamState.emergency_stop_in)
    pub emergency_stop_in: ::std::option::Option<f32>,
    // @@protoc_insertion_point(field:RemoteControlTeamState.timeouts_left)
    pub timeouts_left: ::std::option::Option<i32>,
    // @@protoc_insertion_point(field:RemoteControlTeamState.timeout_time_left)
    pub timeout_time_left: ::std::option::Option<f32>,
    // @@protoc_insertion_point(field:RemoteControlTeamState.challenge_flags_left)
    pub challenge_flags_left: ::std::option::Option<i32>,
    // @@protoc_insertion_point(field:RemoteControlTeamState.max_robots)
    pub max_robots: ::std::option::Option<i32>,
    // @@protoc_insertion_point(field:RemoteControlTeamState.robots_on_field)
    pub robots_on_field: ::std::option::Option<i32>,
    // @@protoc_insertion_point(field:RemoteControlTeamState.yellow_cards_due)
    pub yellow_cards_due: ::std::vec::Vec<f32>,
    // @@protoc_insertion_point(field:RemoteControlTeamState.can_substitute_robot)
    pub can_substitute_robot: ::std::option::Option<bool>,
    // @@protoc_insertion_point(field:RemoteControlTeamState.bot_substitutions_left)
    pub bot_substitutions_left: ::std::option::Option<u32>,
    // @@protoc_insertion_point(field:RemoteControlTeamState.bot_substitution_time_left)
    pub bot_substitution_time_left: ::std::option::Option<f32>,
    // special fields
    // @@protoc_insertion_point(special_field:RemoteControlTeamState.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a RemoteControlTeamState {
    fn default() -> &'a RemoteControlTeamState {
        <RemoteControlTeamState as ::protobuf::Message>::default_instance()
    }
}

impl RemoteControlTeamState {
    pub fn new() -> RemoteControlTeamState {
        ::std::default::Default::default()
    }

    // optional .Team team = 12;

    pub fn team(&self) -> super::ssl_gc_common::Team {
        match self.team {
            Some(e) => e.enum_value_or(super::ssl_gc_common::Team::UNKNOWN),
            None => super::ssl_gc_common::Team::UNKNOWN,
        }
    }

    pub fn clear_team(&mut self) {
        self.team = ::std::option::Option::None;
    }

    pub fn has_team(&self) -> bool {
        self.team.is_some()
    }

    // Param is passed by value, moved
    pub fn set_team(&mut self, v: super::ssl_gc_common::Team) {
        self.team = ::std::option::Option::Some(::protobuf::EnumOrUnknown::new(v));
    }

    // optional int32 keeper_id = 3;

    pub fn keeper_id(&self) -> i32 {
        self.keeper_id.unwrap_or(0)
    }

    pub fn clear_keeper_id(&mut self) {
        self.keeper_id = ::std::option::Option::None;
    }

    pub fn has_keeper_id(&self) -> bool {
        self.keeper_id.is_some()
    }

    // Param is passed by value, moved
    pub fn set_keeper_id(&mut self, v: i32) {
        self.keeper_id = ::std::option::Option::Some(v);
    }

    // optional float emergency_stop_in = 4;

    pub fn emergency_stop_in(&self) -> f32 {
        self.emergency_stop_in.unwrap_or(0.)
    }

    pub fn clear_emergency_stop_in(&mut self) {
        self.emergency_stop_in = ::std::option::Option::None;
    }

    pub fn has_emergency_stop_in(&self) -> bool {
        self.emergency_stop_in.is_some()
    }

    // Param is passed by value, moved
    pub fn set_emergency_stop_in(&mut self, v: f32) {
        self.emergency_stop_in = ::std::option::Option::Some(v);
    }

    // optional int32 timeouts_left = 5;

    pub fn timeouts_left(&self) -> i32 {
        self.timeouts_left.unwrap_or(0)
    }

    pub fn clear_timeouts_left(&mut self) {
        self.timeouts_left = ::std::option::Option::None;
    }

    pub fn has_timeouts_left(&self) -> bool {
        self.timeouts_left.is_some()
    }

    // Param is passed by value, moved
    pub fn set_timeouts_left(&mut self, v: i32) {
        self.timeouts_left = ::std::option::Option::Some(v);
    }

    // optional float timeout_time_left = 10;

    pub fn timeout_time_left(&self) -> f32 {
        self.timeout_time_left.unwrap_or(0.)
    }

    pub fn clear_timeout_time_left(&mut self) {
        self.timeout_time_left = ::std::option::Option::None;
    }

    pub fn has_timeout_time_left(&self) -> bool {
        self.timeout_time_left.is_some()
    }

    // Param is passed by value, moved
    pub fn set_timeout_time_left(&mut self, v: f32) {
        self.timeout_time_left = ::std::option::Option::Some(v);
    }

    // optional int32 challenge_flags_left = 6;

    pub fn challenge_flags_left(&self) -> i32 {
        self.challenge_flags_left.unwrap_or(0)
    }

    pub fn clear_challenge_flags_left(&mut self) {
        self.challenge_flags_left = ::std::option::Option::None;
    }

    pub fn has_challenge_flags_left(&self) -> bool {
        self.challenge_flags_left.is_some()
    }

    // Param is passed by value, moved
    pub fn set_challenge_flags_left(&mut self, v: i32) {
        self.challenge_flags_left = ::std::option::Option::Some(v);
    }

    // optional int32 max_robots = 7;

    pub fn max_robots(&self) -> i32 {
        self.max_robots.unwrap_or(0)
    }

    pub fn clear_max_robots(&mut self) {
        self.max_robots = ::std::option::Option::None;
    }

    pub fn has_max_robots(&self) -> bool {
        self.max_robots.is_some()
    }

    // Param is passed by value, moved
    pub fn set_max_robots(&mut self, v: i32) {
        self.max_robots = ::std::option::Option::Some(v);
    }

    // optional int32 robots_on_field = 9;

    pub fn robots_on_field(&self) -> i32 {
        self.robots_on_field.unwrap_or(0)
    }

    pub fn clear_robots_on_field(&mut self) {
        self.robots_on_field = ::std::option::Option::None;
    }

    pub fn has_robots_on_field(&self) -> bool {
        self.robots_on_field.is_some()
    }

    // Param is passed by value, moved
    pub fn set_robots_on_field(&mut self, v: i32) {
        self.robots_on_field = ::std::option::Option::Some(v);
    }

    // optional bool can_substitute_robot = 11;

    pub fn can_substitute_robot(&self) -> bool {
        self.can_substitute_robot.unwrap_or(false)
    }

    pub fn clear_can_substitute_robot(&mut self) {
        self.can_substitute_robot = ::std::option::Option::None;
    }

    pub fn has_can_substitute_robot(&self) -> bool {
        self.can_substitute_robot.is_some()
    }

    // Param is passed by value, moved
    pub fn set_can_substitute_robot(&mut self, v: bool) {
        self.can_substitute_robot = ::std::option::Option::Some(v);
    }

    // optional uint32 bot_substitutions_left = 13;

    pub fn bot_substitutions_left(&self) -> u32 {
        self.bot_substitutions_left.unwrap_or(0)
    }

    pub fn clear_bot_substitutions_left(&mut self) {
        self.bot_substitutions_left = ::std::option::Option::None;
    }

    pub fn has_bot_substitutions_left(&self) -> bool {
        self.bot_substitutions_left.is_some()
    }

    // Param is passed by value, moved
    pub fn set_bot_substitutions_left(&mut self, v: u32) {
        self.bot_substitutions_left = ::std::option::Option::Some(v);
    }

    // optional float bot_substitution_time_left = 14;

    pub fn bot_substitution_time_left(&self) -> f32 {
        self.bot_substitution_time_left.unwrap_or(0.)
    }

    pub fn clear_bot_substitution_time_left(&mut self) {
        self.bot_substitution_time_left = ::std::option::Option::None;
    }

    pub fn has_bot_substitution_time_left(&self) -> bool {
        self.bot_substitution_time_left.is_some()
    }

    // Param is passed by value, moved
    pub fn set_bot_substitution_time_left(&mut self, v: f32) {
        self.bot_substitution_time_left = ::std::option::Option::Some(v);
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(14);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_option_accessor::<_, _>(
            "team",
            |m: &RemoteControlTeamState| { &m.team },
            |m: &mut RemoteControlTeamState| { &mut m.team },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_vec_simpler_accessor::<_, _>(
            "available_requests",
            |m: &RemoteControlTeamState| { &m.available_requests },
            |m: &mut RemoteControlTeamState| { &mut m.available_requests },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_vec_simpler_accessor::<_, _>(
            "active_requests",
            |m: &RemoteControlTeamState| { &m.active_requests },
            |m: &mut RemoteControlTeamState| { &mut m.active_requests },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_option_accessor::<_, _>(
            "keeper_id",
            |m: &RemoteControlTeamState| { &m.keeper_id },
            |m: &mut RemoteControlTeamState| { &mut m.keeper_id },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_option_accessor::<_, _>(
            "emergency_stop_in",
            |m: &RemoteControlTeamState| { &m.emergency_stop_in },
            |m: &mut RemoteControlTeamState| { &mut m.emergency_stop_in },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_option_accessor::<_, _>(
            "timeouts_left",
            |m: &RemoteControlTeamState| { &m.timeouts_left },
            |m: &mut RemoteControlTeamState| { &mut m.timeouts_left },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_option_accessor::<_, _>(
            "timeout_time_left",
            |m: &RemoteControlTeamState| { &m.timeout_time_left },
            |m: &mut RemoteControlTeamState| { &mut m.timeout_time_left },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_option_accessor::<_, _>(
            "challenge_flags_left",
            |m: &RemoteControlTeamState| { &m.challenge_flags_left },
            |m: &mut RemoteControlTeamState| { &mut m.challenge_flags_left },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_option_accessor::<_, _>(
            "max_robots",
            |m: &RemoteControlTeamState| { &m.max_robots },
            |m: &mut RemoteControlTeamState| { &mut m.max_robots },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_option_accessor::<_, _>(
            "robots_on_field",
            |m: &RemoteControlTeamState| { &m.robots_on_field },
            |m: &mut RemoteControlTeamState| { &mut m.robots_on_field },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_vec_simpler_accessor::<_, _>(
            "yellow_cards_due",
            |m: &RemoteControlTeamState| { &m.yellow_cards_due },
            |m: &mut RemoteControlTeamState| { &mut m.yellow_cards_due },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_option_accessor::<_, _>(
            "can_substitute_robot",
            |m: &RemoteControlTeamState| { &m.can_substitute_robot },
            |m: &mut RemoteControlTeamState| { &mut m.can_substitute_robot },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_option_accessor::<_, _>(
            "bot_substitutions_left",
            |m: &RemoteControlTeamState| { &m.bot_substitutions_left },
            |m: &mut RemoteControlTeamState| { &mut m.bot_substitutions_left },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_option_accessor::<_, _>(
            "bot_substitution_time_left",
            |m: &RemoteControlTeamState| { &m.bot_substitution_time_left },
            |m: &mut RemoteControlTeamState| { &mut m.bot_substitution_time_left },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<RemoteControlTeamState>(
            "RemoteControlTeamState",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for RemoteControlTeamState {
    const NAME: &'static str = "RemoteControlTeamState";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                96 => {
                    self.team = ::std::option::Option::Some(is.read_enum_or_unknown()?);
                },
                8 => {
                    self.available_requests.push(is.read_enum_or_unknown()?);
                },
                10 => {
                    ::protobuf::rt::read_repeated_packed_enum_or_unknown_into(is, &mut self.available_requests)?
                },
                16 => {
                    self.active_requests.push(is.read_enum_or_unknown()?);
                },
                18 => {
                    ::protobuf::rt::read_repeated_packed_enum_or_unknown_into(is, &mut self.active_requests)?
                },
                24 => {
                    self.keeper_id = ::std::option::Option::Some(is.read_int32()?);
                },
                37 => {
                    self.emergency_stop_in = ::std::option::Option::Some(is.read_float()?);
                },
                40 => {
                    self.timeouts_left = ::std::option::Option::Some(is.read_int32()?);
                },
                85 => {
                    self.timeout_time_left = ::std::option::Option::Some(is.read_float()?);
                },
                48 => {
                    self.challenge_flags_left = ::std::option::Option::Some(is.read_int32()?);
                },
                56 => {
                    self.max_robots = ::std::option::Option::Some(is.read_int32()?);
                },
                72 => {
                    self.robots_on_field = ::std::option::Option::Some(is.read_int32()?);
                },
                66 => {
                    is.read_repeated_packed_float_into(&mut self.yellow_cards_due)?;
                },
                69 => {
                    self.yellow_cards_due.push(is.read_float()?);
                },
                88 => {
                    self.can_substitute_robot = ::std::option::Option::Some(is.read_bool()?);
                },
                104 => {
                    self.bot_substitutions_left = ::std::option::Option::Some(is.read_uint32()?);
                },
                117 => {
                    self.bot_substitution_time_left = ::std::option::Option::Some(is.read_float()?);
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if let Some(v) = self.team {
            my_size += ::protobuf::rt::int32_size(12, v.value());
        }
        for value in &self.available_requests {
            my_size += ::protobuf::rt::int32_size(1, value.value());
        };
        for value in &self.active_requests {
            my_size += ::protobuf::rt::int32_size(2, value.value());
        };
        if let Some(v) = self.keeper_id {
            my_size += ::protobuf::rt::int32_size(3, v);
        }
        if let Some(v) = self.emergency_stop_in {
            my_size += 1 + 4;
        }
        if let Some(v) = self.timeouts_left {
            my_size += ::protobuf::rt::int32_size(5, v);
        }
        if let Some(v) = self.timeout_time_left {
            my_size += 1 + 4;
        }
        if let Some(v) = self.challenge_flags_left {
            my_size += ::protobuf::rt::int32_size(6, v);
        }
        if let Some(v) = self.max_robots {
            my_size += ::protobuf::rt::int32_size(7, v);
        }
        if let Some(v) = self.robots_on_field {
            my_size += ::protobuf::rt::int32_size(9, v);
        }
        my_size += 5 * self.yellow_cards_due.len() as u64;
        if let Some(v) = self.can_substitute_robot {
            my_size += 1 + 1;
        }
        if let Some(v) = self.bot_substitutions_left {
            my_size += ::protobuf::rt::uint32_size(13, v);
        }
        if let Some(v) = self.bot_substitution_time_left {
            my_size += 1 + 4;
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if let Some(v) = self.team {
            os.write_enum(12, ::protobuf::EnumOrUnknown::value(&v))?;
        }
        for v in &self.available_requests {
            os.write_enum(1, ::protobuf::EnumOrUnknown::value(v))?;
        };
        for v in &self.active_requests {
            os.write_enum(2, ::protobuf::EnumOrUnknown::value(v))?;
        };
        if let Some(v) = self.keeper_id {
            os.write_int32(3, v)?;
        }
        if let Some(v) = self.emergency_stop_in {
            os.write_float(4, v)?;
        }
        if let Some(v) = self.timeouts_left {
            os.write_int32(5, v)?;
        }
        if let Some(v) = self.timeout_time_left {
            os.write_float(10, v)?;
        }
        if let Some(v) = self.challenge_flags_left {
            os.write_int32(6, v)?;
        }
        if let Some(v) = self.max_robots {
            os.write_int32(7, v)?;
        }
        if let Some(v) = self.robots_on_field {
            os.write_int32(9, v)?;
        }
        for v in &self.yellow_cards_due {
            os.write_float(8, *v)?;
        };
        if let Some(v) = self.can_substitute_robot {
            os.write_bool(11, v)?;
        }
        if let Some(v) = self.bot_substitutions_left {
            os.write_uint32(13, v)?;
        }
        if let Some(v) = self.bot_substitution_time_left {
            os.write_float(14, v)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> RemoteControlTeamState {
        RemoteControlTeamState::new()
    }

    fn clear(&mut self) {
        self.team = ::std::option::Option::None;
        self.available_requests.clear();
        self.active_requests.clear();
        self.keeper_id = ::std::option::Option::None;
        self.emergency_stop_in = ::std::option::Option::None;
        self.timeouts_left = ::std::option::Option::None;
        self.timeout_time_left = ::std::option::Option::None;
        self.challenge_flags_left = ::std::option::Option::None;
        self.max_robots = ::std::option::Option::None;
        self.robots_on_field = ::std::option::Option::None;
        self.yellow_cards_due.clear();
        self.can_substitute_robot = ::std::option::Option::None;
        self.bot_substitutions_left = ::std::option::Option::None;
        self.bot_substitution_time_left = ::std::option::Option::None;
        self.special_fields.clear();
    }

    fn default_instance() -> &'static RemoteControlTeamState {
        static instance: RemoteControlTeamState = RemoteControlTeamState {
            team: ::std::option::Option::None,
            available_requests: ::std::vec::Vec::new(),
            active_requests: ::std::vec::Vec::new(),
            keeper_id: ::std::option::Option::None,
            emergency_stop_in: ::std::option::Option::None,
            timeouts_left: ::std::option::Option::None,
            timeout_time_left: ::std::option::Option::None,
            challenge_flags_left: ::std::option::Option::None,
            max_robots: ::std::option::Option::None,
            robots_on_field: ::std::option::Option::None,
            yellow_cards_due: ::std::vec::Vec::new(),
            can_substitute_robot: ::std::option::Option::None,
            bot_substitutions_left: ::std::option::Option::None,
            bot_substitution_time_left: ::std::option::Option::None,
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for RemoteControlTeamState {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("RemoteControlTeamState").unwrap()).clone()
    }
}

impl ::std::fmt::Display for RemoteControlTeamState {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for RemoteControlTeamState {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

#[derive(Clone,Copy,PartialEq,Eq,Debug,Hash)]
// @@protoc_insertion_point(enum:RemoteControlRequestType)
pub enum RemoteControlRequestType {
    // @@protoc_insertion_point(enum_value:RemoteControlRequestType.UNKNOWN_REQUEST_TYPE)
    UNKNOWN_REQUEST_TYPE = 0,
    // @@protoc_insertion_point(enum_value:RemoteControlRequestType.EMERGENCY_STOP)
    EMERGENCY_STOP = 1,
    // @@protoc_insertion_point(enum_value:RemoteControlRequestType.ROBOT_SUBSTITUTION)
    ROBOT_SUBSTITUTION = 2,
    // @@protoc_insertion_point(enum_value:RemoteControlRequestType.TIMEOUT)
    TIMEOUT = 3,
    // @@protoc_insertion_point(enum_value:RemoteControlRequestType.CHALLENGE_FLAG)
    CHALLENGE_FLAG = 4,
    // @@protoc_insertion_point(enum_value:RemoteControlRequestType.CHANGE_KEEPER_ID)
    CHANGE_KEEPER_ID = 5,
    // @@protoc_insertion_point(enum_value:RemoteControlRequestType.STOP_TIMEOUT)
    STOP_TIMEOUT = 6,
    // @@protoc_insertion_point(enum_value:RemoteControlRequestType.FAIL_BALLPLACEMENT)
    FAIL_BALLPLACEMENT = 7,
}

impl ::protobuf::Enum for RemoteControlRequestType {
    const NAME: &'static str = "RemoteControlRequestType";

    fn value(&self) -> i32 {
        *self as i32
    }

    fn from_i32(value: i32) -> ::std::option::Option<RemoteControlRequestType> {
        match value {
            0 => ::std::option::Option::Some(RemoteControlRequestType::UNKNOWN_REQUEST_TYPE),
            1 => ::std::option::Option::Some(RemoteControlRequestType::EMERGENCY_STOP),
            2 => ::std::option::Option::Some(RemoteControlRequestType::ROBOT_SUBSTITUTION),
            3 => ::std::option::Option::Some(RemoteControlRequestType::TIMEOUT),
            4 => ::std::option::Option::Some(RemoteControlRequestType::CHALLENGE_FLAG),
            5 => ::std::option::Option::Some(RemoteControlRequestType::CHANGE_KEEPER_ID),
            6 => ::std::option::Option::Some(RemoteControlRequestType::STOP_TIMEOUT),
            7 => ::std::option::Option::Some(RemoteControlRequestType::FAIL_BALLPLACEMENT),
            _ => ::std::option::Option::None
        }
    }

    fn from_str(str: &str) -> ::std::option::Option<RemoteControlRequestType> {
        match str {
            "UNKNOWN_REQUEST_TYPE" => ::std::option::Option::Some(RemoteControlRequestType::UNKNOWN_REQUEST_TYPE),
            "EMERGENCY_STOP" => ::std::option::Option::Some(RemoteControlRequestType::EMERGENCY_STOP),
            "ROBOT_SUBSTITUTION" => ::std::option::Option::Some(RemoteControlRequestType::ROBOT_SUBSTITUTION),
            "TIMEOUT" => ::std::option::Option::Some(RemoteControlRequestType::TIMEOUT),
            "CHALLENGE_FLAG" => ::std::option::Option::Some(RemoteControlRequestType::CHALLENGE_FLAG),
            "CHANGE_KEEPER_ID" => ::std::option::Option::Some(RemoteControlRequestType::CHANGE_KEEPER_ID),
            "STOP_TIMEOUT" => ::std::option::Option::Some(RemoteControlRequestType::STOP_TIMEOUT),
            "FAIL_BALLPLACEMENT" => ::std::option::Option::Some(RemoteControlRequestType::FAIL_BALLPLACEMENT),
            _ => ::std::option::Option::None
        }
    }

    const VALUES: &'static [RemoteControlRequestType] = &[
        RemoteControlRequestType::UNKNOWN_REQUEST_TYPE,
        RemoteControlRequestType::EMERGENCY_STOP,
        RemoteControlRequestType::ROBOT_SUBSTITUTION,
        RemoteControlRequestType::TIMEOUT,
        RemoteControlRequestType::CHALLENGE_FLAG,
        RemoteControlRequestType::CHANGE_KEEPER_ID,
        RemoteControlRequestType::STOP_TIMEOUT,
        RemoteControlRequestType::FAIL_BALLPLACEMENT,
    ];
}

impl ::protobuf::EnumFull for RemoteControlRequestType {
    fn enum_descriptor() -> ::protobuf::reflect::EnumDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::EnumDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().enum_by_package_relative_name("RemoteControlRequestType").unwrap()).clone()
    }

    fn descriptor(&self) -> ::protobuf::reflect::EnumValueDescriptor {
        let index = *self as usize;
        Self::enum_descriptor().value_by_index(index)
    }
}

impl ::std::default::Default for RemoteControlRequestType {
    fn default() -> Self {
        RemoteControlRequestType::UNKNOWN_REQUEST_TYPE
    }
}

impl RemoteControlRequestType {
    fn generated_enum_descriptor_data() -> ::protobuf::reflect::GeneratedEnumDescriptorData {
        ::protobuf::reflect::GeneratedEnumDescriptorData::new::<RemoteControlRequestType>("RemoteControlRequestType")
    }
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\x1fssl_gc_rcon_remotecontrol.proto\x1a\x13ssl_gc_common.proto\x1a\x11\
    ssl_gc_rcon.proto\"`\n\x19RemoteControlRegistration\x12\x19\n\x04team\
    \x18\x01\x20\x02(\x0e2\x05.TeamR\x04team\x12(\n\tsignature\x18\x02\x20\
    \x01(\x0b2\n.SignatureR\tsignature\"\xb8\x03\n\x19RemoteControlToControl\
    ler\x12(\n\tsignature\x18\x01\x20\x01(\x0b2\n.SignatureR\tsignature\x12>\
    \n\x07request\x18\x02\x20\x01(\x0e2\".RemoteControlToController.RequestH\
    \0R\x07request\x12'\n\x0edesired_keeper\x18\x03\x20\x01(\x05H\0R\rdesire\
    dKeeper\x12>\n\x1arequest_robot_substitution\x18\x04\x20\x01(\x08H\0R\
    \x18requestRobotSubstitution\x12)\n\x0frequest_timeout\x18\x05\x20\x01(\
    \x08H\0R\x0erequestTimeout\x126\n\x16request_emergency_stop\x18\x06\x20\
    \x01(\x08H\0R\x14requestEmergencyStop\"^\n\x07Request\x12\x0b\n\x07UNKNO\
    WN\x10\0\x12\x08\n\x04PING\x10\x01\x12\x12\n\x0eCHALLENGE_FLAG\x10\x02\
    \x12\x10\n\x0cSTOP_TIMEOUT\x10\x03\x12\x16\n\x12FAIL_BALLPLACEMENT\x10\
    \x04B\x05\n\x03msg\"\x87\x01\n\x19ControllerToRemoteControl\x12;\n\x10co\
    ntroller_reply\x18\x01\x20\x01(\x0b2\x10.ControllerReplyR\x0fcontrollerR\
    eply\x12-\n\x05state\x18\x02\x20\x01(\x0b2\x17.RemoteControlTeamStateR\
    \x05state\"\xa3\x05\n\x16RemoteControlTeamState\x12\x19\n\x04team\x18\
    \x0c\x20\x01(\x0e2\x05.TeamR\x04team\x12H\n\x12available_requests\x18\
    \x01\x20\x03(\x0e2\x19.RemoteControlRequestTypeR\x11availableRequests\
    \x12B\n\x0factive_requests\x18\x02\x20\x03(\x0e2\x19.RemoteControlReques\
    tTypeR\x0eactiveRequests\x12\x1b\n\tkeeper_id\x18\x03\x20\x01(\x05R\x08k\
    eeperId\x12*\n\x11emergency_stop_in\x18\x04\x20\x01(\x02R\x0femergencySt\
    opIn\x12#\n\rtimeouts_left\x18\x05\x20\x01(\x05R\x0ctimeoutsLeft\x12*\n\
    \x11timeout_time_left\x18\n\x20\x01(\x02R\x0ftimeoutTimeLeft\x120\n\x14c\
    hallenge_flags_left\x18\x06\x20\x01(\x05R\x12challengeFlagsLeft\x12\x1d\
    \n\nmax_robots\x18\x07\x20\x01(\x05R\tmaxRobots\x12&\n\x0frobots_on_fiel\
    d\x18\t\x20\x01(\x05R\rrobotsOnField\x12(\n\x10yellow_cards_due\x18\x08\
    \x20\x03(\x02R\x0eyellowCardsDue\x120\n\x14can_substitute_robot\x18\x0b\
    \x20\x01(\x08R\x12canSubstituteRobot\x124\n\x16bot_substitutions_left\
    \x18\r\x20\x01(\rR\x14botSubstitutionsLeft\x12;\n\x1abot_substitution_ti\
    me_left\x18\x0e\x20\x01(\x02R\x17botSubstitutionTimeLeft*\xc1\x01\n\x18R\
    emoteControlRequestType\x12\x18\n\x14UNKNOWN_REQUEST_TYPE\x10\0\x12\x12\
    \n\x0eEMERGENCY_STOP\x10\x01\x12\x16\n\x12ROBOT_SUBSTITUTION\x10\x02\x12\
    \x0b\n\x07TIMEOUT\x10\x03\x12\x12\n\x0eCHALLENGE_FLAG\x10\x04\x12\x14\n\
    \x10CHANGE_KEEPER_ID\x10\x05\x12\x10\n\x0cSTOP_TIMEOUT\x10\x06\x12\x16\n\
    \x12FAIL_BALLPLACEMENT\x10\x07b\x06proto2\
";

/// `FileDescriptorProto` object which was a source for this generated file
fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    static file_descriptor_proto_lazy: ::protobuf::rt::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::Lazy::new();
    file_descriptor_proto_lazy.get(|| {
        ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
    })
}

/// `FileDescriptor` object which allows dynamic access to files
pub fn file_descriptor() -> &'static ::protobuf::reflect::FileDescriptor {
    static generated_file_descriptor_lazy: ::protobuf::rt::Lazy<::protobuf::reflect::GeneratedFileDescriptor> = ::protobuf::rt::Lazy::new();
    static file_descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::FileDescriptor> = ::protobuf::rt::Lazy::new();
    file_descriptor.get(|| {
        let generated_file_descriptor = generated_file_descriptor_lazy.get(|| {
            let mut deps = ::std::vec::Vec::with_capacity(2);
            deps.push(super::ssl_gc_common::file_descriptor().clone());
            deps.push(super::ssl_gc_rcon::file_descriptor().clone());
            let mut messages = ::std::vec::Vec::with_capacity(4);
            messages.push(RemoteControlRegistration::generated_message_descriptor_data());
            messages.push(RemoteControlToController::generated_message_descriptor_data());
            messages.push(ControllerToRemoteControl::generated_message_descriptor_data());
            messages.push(RemoteControlTeamState::generated_message_descriptor_data());
            let mut enums = ::std::vec::Vec::with_capacity(2);
            enums.push(RemoteControlRequestType::generated_enum_descriptor_data());
            enums.push(remote_control_to_controller::Request::generated_enum_descriptor_data());
            ::protobuf::reflect::GeneratedFileDescriptor::new_generated(
                file_descriptor_proto(),
                deps,
                messages,
                enums,
            )
        });
        ::protobuf::reflect::FileDescriptor::new_generated_2(generated_file_descriptor)
    })
}
