// This file is generated by rust-protobuf 3.7.2. Do not edit
// .proto file is parsed by pure
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_results)]
#![allow(unused_mut)]

//! Generated file from `ssl_simulation_config.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_3_7_2;

// @@protoc_insertion_point(message:RobotLimits)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct RobotLimits {
    // message fields
    // @@protoc_insertion_point(field:RobotLimits.acc_speedup_absolute_max)
    pub acc_speedup_absolute_max: ::std::option::Option<f32>,
    // @@protoc_insertion_point(field:RobotLimits.acc_speedup_angular_max)
    pub acc_speedup_angular_max: ::std::option::Option<f32>,
    // @@protoc_insertion_point(field:RobotLimits.acc_brake_absolute_max)
    pub acc_brake_absolute_max: ::std::option::Option<f32>,
    // @@protoc_insertion_point(field:RobotLimits.acc_brake_angular_max)
    pub acc_brake_angular_max: ::std::option::Option<f32>,
    // @@protoc_insertion_point(field:RobotLimits.vel_absolute_max)
    pub vel_absolute_max: ::std::option::Option<f32>,
    // @@protoc_insertion_point(field:RobotLimits.vel_angular_max)
    pub vel_angular_max: ::std::option::Option<f32>,
    // special fields
    // @@protoc_insertion_point(special_field:RobotLimits.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a RobotLimits {
    fn default() -> &'a RobotLimits {
        <RobotLimits as ::protobuf::Message>::default_instance()
    }
}

impl RobotLimits {
    pub fn new() -> RobotLimits {
        ::std::default::Default::default()
    }

    // optional float acc_speedup_absolute_max = 1;

    pub fn acc_speedup_absolute_max(&self) -> f32 {
        self.acc_speedup_absolute_max.unwrap_or(0.)
    }

    pub fn clear_acc_speedup_absolute_max(&mut self) {
        self.acc_speedup_absolute_max = ::std::option::Option::None;
    }

    pub fn has_acc_speedup_absolute_max(&self) -> bool {
        self.acc_speedup_absolute_max.is_some()
    }

    // Param is passed by value, moved
    pub fn set_acc_speedup_absolute_max(&mut self, v: f32) {
        self.acc_speedup_absolute_max = ::std::option::Option::Some(v);
    }

    // optional float acc_speedup_angular_max = 2;

    pub fn acc_speedup_angular_max(&self) -> f32 {
        self.acc_speedup_angular_max.unwrap_or(0.)
    }

    pub fn clear_acc_speedup_angular_max(&mut self) {
        self.acc_speedup_angular_max = ::std::option::Option::None;
    }

    pub fn has_acc_speedup_angular_max(&self) -> bool {
        self.acc_speedup_angular_max.is_some()
    }

    // Param is passed by value, moved
    pub fn set_acc_speedup_angular_max(&mut self, v: f32) {
        self.acc_speedup_angular_max = ::std::option::Option::Some(v);
    }

    // optional float acc_brake_absolute_max = 3;

    pub fn acc_brake_absolute_max(&self) -> f32 {
        self.acc_brake_absolute_max.unwrap_or(0.)
    }

    pub fn clear_acc_brake_absolute_max(&mut self) {
        self.acc_brake_absolute_max = ::std::option::Option::None;
    }

    pub fn has_acc_brake_absolute_max(&self) -> bool {
        self.acc_brake_absolute_max.is_some()
    }

    // Param is passed by value, moved
    pub fn set_acc_brake_absolute_max(&mut self, v: f32) {
        self.acc_brake_absolute_max = ::std::option::Option::Some(v);
    }

    // optional float acc_brake_angular_max = 4;

    pub fn acc_brake_angular_max(&self) -> f32 {
        self.acc_brake_angular_max.unwrap_or(0.)
    }

    pub fn clear_acc_brake_angular_max(&mut self) {
        self.acc_brake_angular_max = ::std::option::Option::None;
    }

    pub fn has_acc_brake_angular_max(&self) -> bool {
        self.acc_brake_angular_max.is_some()
    }

    // Param is passed by value, moved
    pub fn set_acc_brake_angular_max(&mut self, v: f32) {
        self.acc_brake_angular_max = ::std::option::Option::Some(v);
    }

    // optional float vel_absolute_max = 5;

    pub fn vel_absolute_max(&self) -> f32 {
        self.vel_absolute_max.unwrap_or(0.)
    }

    pub fn clear_vel_absolute_max(&mut self) {
        self.vel_absolute_max = ::std::option::Option::None;
    }

    pub fn has_vel_absolute_max(&self) -> bool {
        self.vel_absolute_max.is_some()
    }

    // Param is passed by value, moved
    pub fn set_vel_absolute_max(&mut self, v: f32) {
        self.vel_absolute_max = ::std::option::Option::Some(v);
    }

    // optional float vel_angular_max = 6;

    pub fn vel_angular_max(&self) -> f32 {
        self.vel_angular_max.unwrap_or(0.)
    }

    pub fn clear_vel_angular_max(&mut self) {
        self.vel_angular_max = ::std::option::Option::None;
    }

    pub fn has_vel_angular_max(&self) -> bool {
        self.vel_angular_max.is_some()
    }

    // Param is passed by value, moved
    pub fn set_vel_angular_max(&mut self, v: f32) {
        self.vel_angular_max = ::std::option::Option::Some(v);
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(6);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_option_accessor::<_, _>(
            "acc_speedup_absolute_max",
            |m: &RobotLimits| { &m.acc_speedup_absolute_max },
            |m: &mut RobotLimits| { &mut m.acc_speedup_absolute_max },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_option_accessor::<_, _>(
            "acc_speedup_angular_max",
            |m: &RobotLimits| { &m.acc_speedup_angular_max },
            |m: &mut RobotLimits| { &mut m.acc_speedup_angular_max },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_option_accessor::<_, _>(
            "acc_brake_absolute_max",
            |m: &RobotLimits| { &m.acc_brake_absolute_max },
            |m: &mut RobotLimits| { &mut m.acc_brake_absolute_max },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_option_accessor::<_, _>(
            "acc_brake_angular_max",
            |m: &RobotLimits| { &m.acc_brake_angular_max },
            |m: &mut RobotLimits| { &mut m.acc_brake_angular_max },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_option_accessor::<_, _>(
            "vel_absolute_max",
            |m: &RobotLimits| { &m.vel_absolute_max },
            |m: &mut RobotLimits| { &mut m.vel_absolute_max },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_option_accessor::<_, _>(
            "vel_angular_max",
            |m: &RobotLimits| { &m.vel_angular_max },
            |m: &mut RobotLimits| { &mut m.vel_angular_max },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<RobotLimits>(
            "RobotLimits",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for RobotLimits {
    const NAME: &'static str = "RobotLimits";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                13 => {
                    self.acc_speedup_absolute_max = ::std::option::Option::Some(is.read_float()?);
                },
                21 => {
                    self.acc_speedup_angular_max = ::std::option::Option::Some(is.read_float()?);
                },
                29 => {
                    self.acc_brake_absolute_max = ::std::option::Option::Some(is.read_float()?);
                },
                37 => {
                    self.acc_brake_angular_max = ::std::option::Option::Some(is.read_float()?);
                },
                45 => {
                    self.vel_absolute_max = ::std::option::Option::Some(is.read_float()?);
                },
                53 => {
                    self.vel_angular_max = ::std::option::Option::Some(is.read_float()?);
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if let Some(v) = self.acc_speedup_absolute_max {
            my_size += 1 + 4;
        }
        if let Some(v) = self.acc_speedup_angular_max {
            my_size += 1 + 4;
        }
        if let Some(v) = self.acc_brake_absolute_max {
            my_size += 1 + 4;
        }
        if let Some(v) = self.acc_brake_angular_max {
            my_size += 1 + 4;
        }
        if let Some(v) = self.vel_absolute_max {
            my_size += 1 + 4;
        }
        if let Some(v) = self.vel_angular_max {
            my_size += 1 + 4;
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if let Some(v) = self.acc_speedup_absolute_max {
            os.write_float(1, v)?;
        }
        if let Some(v) = self.acc_speedup_angular_max {
            os.write_float(2, v)?;
        }
        if let Some(v) = self.acc_brake_absolute_max {
            os.write_float(3, v)?;
        }
        if let Some(v) = self.acc_brake_angular_max {
            os.write_float(4, v)?;
        }
        if let Some(v) = self.vel_absolute_max {
            os.write_float(5, v)?;
        }
        if let Some(v) = self.vel_angular_max {
            os.write_float(6, v)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> RobotLimits {
        RobotLimits::new()
    }

    fn clear(&mut self) {
        self.acc_speedup_absolute_max = ::std::option::Option::None;
        self.acc_speedup_angular_max = ::std::option::Option::None;
        self.acc_brake_absolute_max = ::std::option::Option::None;
        self.acc_brake_angular_max = ::std::option::Option::None;
        self.vel_absolute_max = ::std::option::Option::None;
        self.vel_angular_max = ::std::option::Option::None;
        self.special_fields.clear();
    }

    fn default_instance() -> &'static RobotLimits {
        static instance: RobotLimits = RobotLimits {
            acc_speedup_absolute_max: ::std::option::Option::None,
            acc_speedup_angular_max: ::std::option::Option::None,
            acc_brake_absolute_max: ::std::option::Option::None,
            acc_brake_angular_max: ::std::option::Option::None,
            vel_absolute_max: ::std::option::Option::None,
            vel_angular_max: ::std::option::Option::None,
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for RobotLimits {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("RobotLimits").unwrap()).clone()
    }
}

impl ::std::fmt::Display for RobotLimits {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for RobotLimits {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

// @@protoc_insertion_point(message:RobotWheelAngles)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct RobotWheelAngles {
    // message fields
    // @@protoc_insertion_point(field:RobotWheelAngles.front_right)
    pub front_right: ::std::option::Option<f32>,
    // @@protoc_insertion_point(field:RobotWheelAngles.back_right)
    pub back_right: ::std::option::Option<f32>,
    // @@protoc_insertion_point(field:RobotWheelAngles.back_left)
    pub back_left: ::std::option::Option<f32>,
    // @@protoc_insertion_point(field:RobotWheelAngles.front_left)
    pub front_left: ::std::option::Option<f32>,
    // special fields
    // @@protoc_insertion_point(special_field:RobotWheelAngles.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a RobotWheelAngles {
    fn default() -> &'a RobotWheelAngles {
        <RobotWheelAngles as ::protobuf::Message>::default_instance()
    }
}

impl RobotWheelAngles {
    pub fn new() -> RobotWheelAngles {
        ::std::default::Default::default()
    }

    // required float front_right = 1;

    pub fn front_right(&self) -> f32 {
        self.front_right.unwrap_or(0.)
    }

    pub fn clear_front_right(&mut self) {
        self.front_right = ::std::option::Option::None;
    }

    pub fn has_front_right(&self) -> bool {
        self.front_right.is_some()
    }

    // Param is passed by value, moved
    pub fn set_front_right(&mut self, v: f32) {
        self.front_right = ::std::option::Option::Some(v);
    }

    // required float back_right = 2;

    pub fn back_right(&self) -> f32 {
        self.back_right.unwrap_or(0.)
    }

    pub fn clear_back_right(&mut self) {
        self.back_right = ::std::option::Option::None;
    }

    pub fn has_back_right(&self) -> bool {
        self.back_right.is_some()
    }

    // Param is passed by value, moved
    pub fn set_back_right(&mut self, v: f32) {
        self.back_right = ::std::option::Option::Some(v);
    }

    // required float back_left = 3;

    pub fn back_left(&self) -> f32 {
        self.back_left.unwrap_or(0.)
    }

    pub fn clear_back_left(&mut self) {
        self.back_left = ::std::option::Option::None;
    }

    pub fn has_back_left(&self) -> bool {
        self.back_left.is_some()
    }

    // Param is passed by value, moved
    pub fn set_back_left(&mut self, v: f32) {
        self.back_left = ::std::option::Option::Some(v);
    }

    // required float front_left = 4;

    pub fn front_left(&self) -> f32 {
        self.front_left.unwrap_or(0.)
    }

    pub fn clear_front_left(&mut self) {
        self.front_left = ::std::option::Option::None;
    }

    pub fn has_front_left(&self) -> bool {
        self.front_left.is_some()
    }

    // Param is passed by value, moved
    pub fn set_front_left(&mut self, v: f32) {
        self.front_left = ::std::option::Option::Some(v);
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(4);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_option_accessor::<_, _>(
            "front_right",
            |m: &RobotWheelAngles| { &m.front_right },
            |m: &mut RobotWheelAngles| { &mut m.front_right },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_option_accessor::<_, _>(
            "back_right",
            |m: &RobotWheelAngles| { &m.back_right },
            |m: &mut RobotWheelAngles| { &mut m.back_right },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_option_accessor::<_, _>(
            "back_left",
            |m: &RobotWheelAngles| { &m.back_left },
            |m: &mut RobotWheelAngles| { &mut m.back_left },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_option_accessor::<_, _>(
            "front_left",
            |m: &RobotWheelAngles| { &m.front_left },
            |m: &mut RobotWheelAngles| { &mut m.front_left },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<RobotWheelAngles>(
            "RobotWheelAngles",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for RobotWheelAngles {
    const NAME: &'static str = "RobotWheelAngles";

    fn is_initialized(&self) -> bool {
        if self.front_right.is_none() {
            return false;
        }
        if self.back_right.is_none() {
            return false;
        }
        if self.back_left.is_none() {
            return false;
        }
        if self.front_left.is_none() {
            return false;
        }
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                13 => {
                    self.front_right = ::std::option::Option::Some(is.read_float()?);
                },
                21 => {
                    self.back_right = ::std::option::Option::Some(is.read_float()?);
                },
                29 => {
                    self.back_left = ::std::option::Option::Some(is.read_float()?);
                },
                37 => {
                    self.front_left = ::std::option::Option::Some(is.read_float()?);
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if let Some(v) = self.front_right {
            my_size += 1 + 4;
        }
        if let Some(v) = self.back_right {
            my_size += 1 + 4;
        }
        if let Some(v) = self.back_left {
            my_size += 1 + 4;
        }
        if let Some(v) = self.front_left {
            my_size += 1 + 4;
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if let Some(v) = self.front_right {
            os.write_float(1, v)?;
        }
        if let Some(v) = self.back_right {
            os.write_float(2, v)?;
        }
        if let Some(v) = self.back_left {
            os.write_float(3, v)?;
        }
        if let Some(v) = self.front_left {
            os.write_float(4, v)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> RobotWheelAngles {
        RobotWheelAngles::new()
    }

    fn clear(&mut self) {
        self.front_right = ::std::option::Option::None;
        self.back_right = ::std::option::Option::None;
        self.back_left = ::std::option::Option::None;
        self.front_left = ::std::option::Option::None;
        self.special_fields.clear();
    }

    fn default_instance() -> &'static RobotWheelAngles {
        static instance: RobotWheelAngles = RobotWheelAngles {
            front_right: ::std::option::Option::None,
            back_right: ::std::option::Option::None,
            back_left: ::std::option::Option::None,
            front_left: ::std::option::Option::None,
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for RobotWheelAngles {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("RobotWheelAngles").unwrap()).clone()
    }
}

impl ::std::fmt::Display for RobotWheelAngles {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for RobotWheelAngles {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

// @@protoc_insertion_point(message:RobotSpecs)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct RobotSpecs {
    // message fields
    // @@protoc_insertion_point(field:RobotSpecs.id)
    pub id: ::protobuf::MessageField<super::ssl_gc_common::RobotId>,
    // @@protoc_insertion_point(field:RobotSpecs.radius)
    pub radius: ::std::option::Option<f32>,
    // @@protoc_insertion_point(field:RobotSpecs.height)
    pub height: ::std::option::Option<f32>,
    // @@protoc_insertion_point(field:RobotSpecs.mass)
    pub mass: ::std::option::Option<f32>,
    // @@protoc_insertion_point(field:RobotSpecs.max_linear_kick_speed)
    pub max_linear_kick_speed: ::std::option::Option<f32>,
    // @@protoc_insertion_point(field:RobotSpecs.max_chip_kick_speed)
    pub max_chip_kick_speed: ::std::option::Option<f32>,
    // @@protoc_insertion_point(field:RobotSpecs.center_to_dribbler)
    pub center_to_dribbler: ::std::option::Option<f32>,
    // @@protoc_insertion_point(field:RobotSpecs.limits)
    pub limits: ::protobuf::MessageField<RobotLimits>,
    // @@protoc_insertion_point(field:RobotSpecs.wheel_angles)
    pub wheel_angles: ::protobuf::MessageField<RobotWheelAngles>,
    // @@protoc_insertion_point(field:RobotSpecs.custom)
    pub custom: ::protobuf::MessageField<::protobuf::well_known_types::any::Any>,
    // special fields
    // @@protoc_insertion_point(special_field:RobotSpecs.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a RobotSpecs {
    fn default() -> &'a RobotSpecs {
        <RobotSpecs as ::protobuf::Message>::default_instance()
    }
}

impl RobotSpecs {
    pub fn new() -> RobotSpecs {
        ::std::default::Default::default()
    }

    // optional float radius = 2;

    pub fn radius(&self) -> f32 {
        self.radius.unwrap_or(0.09000000357627869f32)
    }

    pub fn clear_radius(&mut self) {
        self.radius = ::std::option::Option::None;
    }

    pub fn has_radius(&self) -> bool {
        self.radius.is_some()
    }

    // Param is passed by value, moved
    pub fn set_radius(&mut self, v: f32) {
        self.radius = ::std::option::Option::Some(v);
    }

    // optional float height = 3;

    pub fn height(&self) -> f32 {
        self.height.unwrap_or(0.15000000596046448f32)
    }

    pub fn clear_height(&mut self) {
        self.height = ::std::option::Option::None;
    }

    pub fn has_height(&self) -> bool {
        self.height.is_some()
    }

    // Param is passed by value, moved
    pub fn set_height(&mut self, v: f32) {
        self.height = ::std::option::Option::Some(v);
    }

    // optional float mass = 4;

    pub fn mass(&self) -> f32 {
        self.mass.unwrap_or(0.)
    }

    pub fn clear_mass(&mut self) {
        self.mass = ::std::option::Option::None;
    }

    pub fn has_mass(&self) -> bool {
        self.mass.is_some()
    }

    // Param is passed by value, moved
    pub fn set_mass(&mut self, v: f32) {
        self.mass = ::std::option::Option::Some(v);
    }

    // optional float max_linear_kick_speed = 7;

    pub fn max_linear_kick_speed(&self) -> f32 {
        self.max_linear_kick_speed.unwrap_or(0.)
    }

    pub fn clear_max_linear_kick_speed(&mut self) {
        self.max_linear_kick_speed = ::std::option::Option::None;
    }

    pub fn has_max_linear_kick_speed(&self) -> bool {
        self.max_linear_kick_speed.is_some()
    }

    // Param is passed by value, moved
    pub fn set_max_linear_kick_speed(&mut self, v: f32) {
        self.max_linear_kick_speed = ::std::option::Option::Some(v);
    }

    // optional float max_chip_kick_speed = 8;

    pub fn max_chip_kick_speed(&self) -> f32 {
        self.max_chip_kick_speed.unwrap_or(0.)
    }

    pub fn clear_max_chip_kick_speed(&mut self) {
        self.max_chip_kick_speed = ::std::option::Option::None;
    }

    pub fn has_max_chip_kick_speed(&self) -> bool {
        self.max_chip_kick_speed.is_some()
    }

    // Param is passed by value, moved
    pub fn set_max_chip_kick_speed(&mut self, v: f32) {
        self.max_chip_kick_speed = ::std::option::Option::Some(v);
    }

    // optional float center_to_dribbler = 9;

    pub fn center_to_dribbler(&self) -> f32 {
        self.center_to_dribbler.unwrap_or(0.)
    }

    pub fn clear_center_to_dribbler(&mut self) {
        self.center_to_dribbler = ::std::option::Option::None;
    }

    pub fn has_center_to_dribbler(&self) -> bool {
        self.center_to_dribbler.is_some()
    }

    // Param is passed by value, moved
    pub fn set_center_to_dribbler(&mut self, v: f32) {
        self.center_to_dribbler = ::std::option::Option::Some(v);
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(10);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_message_field_accessor::<_, super::ssl_gc_common::RobotId>(
            "id",
            |m: &RobotSpecs| { &m.id },
            |m: &mut RobotSpecs| { &mut m.id },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_option_accessor::<_, _>(
            "radius",
            |m: &RobotSpecs| { &m.radius },
            |m: &mut RobotSpecs| { &mut m.radius },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_option_accessor::<_, _>(
            "height",
            |m: &RobotSpecs| { &m.height },
            |m: &mut RobotSpecs| { &mut m.height },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_option_accessor::<_, _>(
            "mass",
            |m: &RobotSpecs| { &m.mass },
            |m: &mut RobotSpecs| { &mut m.mass },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_option_accessor::<_, _>(
            "max_linear_kick_speed",
            |m: &RobotSpecs| { &m.max_linear_kick_speed },
            |m: &mut RobotSpecs| { &mut m.max_linear_kick_speed },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_option_accessor::<_, _>(
            "max_chip_kick_speed",
            |m: &RobotSpecs| { &m.max_chip_kick_speed },
            |m: &mut RobotSpecs| { &mut m.max_chip_kick_speed },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_option_accessor::<_, _>(
            "center_to_dribbler",
            |m: &RobotSpecs| { &m.center_to_dribbler },
            |m: &mut RobotSpecs| { &mut m.center_to_dribbler },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_message_field_accessor::<_, RobotLimits>(
            "limits",
            |m: &RobotSpecs| { &m.limits },
            |m: &mut RobotSpecs| { &mut m.limits },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_message_field_accessor::<_, RobotWheelAngles>(
            "wheel_angles",
            |m: &RobotSpecs| { &m.wheel_angles },
            |m: &mut RobotSpecs| { &mut m.wheel_angles },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_message_field_accessor::<_, ::protobuf::well_known_types::any::Any>(
            "custom",
            |m: &RobotSpecs| { &m.custom },
            |m: &mut RobotSpecs| { &mut m.custom },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<RobotSpecs>(
            "RobotSpecs",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for RobotSpecs {
    const NAME: &'static str = "RobotSpecs";

    fn is_initialized(&self) -> bool {
        if self.id.is_none() {
            return false;
        }
        for v in &self.id {
            if !v.is_initialized() {
                return false;
            }
        };
        for v in &self.limits {
            if !v.is_initialized() {
                return false;
            }
        };
        for v in &self.wheel_angles {
            if !v.is_initialized() {
                return false;
            }
        };
        for v in &self.custom {
            if !v.is_initialized() {
                return false;
            }
        };
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                10 => {
                    ::protobuf::rt::read_singular_message_into_field(is, &mut self.id)?;
                },
                21 => {
                    self.radius = ::std::option::Option::Some(is.read_float()?);
                },
                29 => {
                    self.height = ::std::option::Option::Some(is.read_float()?);
                },
                37 => {
                    self.mass = ::std::option::Option::Some(is.read_float()?);
                },
                61 => {
                    self.max_linear_kick_speed = ::std::option::Option::Some(is.read_float()?);
                },
                69 => {
                    self.max_chip_kick_speed = ::std::option::Option::Some(is.read_float()?);
                },
                77 => {
                    self.center_to_dribbler = ::std::option::Option::Some(is.read_float()?);
                },
                82 => {
                    ::protobuf::rt::read_singular_message_into_field(is, &mut self.limits)?;
                },
                106 => {
                    ::protobuf::rt::read_singular_message_into_field(is, &mut self.wheel_angles)?;
                },
                114 => {
                    ::protobuf::rt::read_singular_message_into_field(is, &mut self.custom)?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if let Some(v) = self.id.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        }
        if let Some(v) = self.radius {
            my_size += 1 + 4;
        }
        if let Some(v) = self.height {
            my_size += 1 + 4;
        }
        if let Some(v) = self.mass {
            my_size += 1 + 4;
        }
        if let Some(v) = self.max_linear_kick_speed {
            my_size += 1 + 4;
        }
        if let Some(v) = self.max_chip_kick_speed {
            my_size += 1 + 4;
        }
        if let Some(v) = self.center_to_dribbler {
            my_size += 1 + 4;
        }
        if let Some(v) = self.limits.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        }
        if let Some(v) = self.wheel_angles.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        }
        if let Some(v) = self.custom.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if let Some(v) = self.id.as_ref() {
            ::protobuf::rt::write_message_field_with_cached_size(1, v, os)?;
        }
        if let Some(v) = self.radius {
            os.write_float(2, v)?;
        }
        if let Some(v) = self.height {
            os.write_float(3, v)?;
        }
        if let Some(v) = self.mass {
            os.write_float(4, v)?;
        }
        if let Some(v) = self.max_linear_kick_speed {
            os.write_float(7, v)?;
        }
        if let Some(v) = self.max_chip_kick_speed {
            os.write_float(8, v)?;
        }
        if let Some(v) = self.center_to_dribbler {
            os.write_float(9, v)?;
        }
        if let Some(v) = self.limits.as_ref() {
            ::protobuf::rt::write_message_field_with_cached_size(10, v, os)?;
        }
        if let Some(v) = self.wheel_angles.as_ref() {
            ::protobuf::rt::write_message_field_with_cached_size(13, v, os)?;
        }
        if let Some(v) = self.custom.as_ref() {
            ::protobuf::rt::write_message_field_with_cached_size(14, v, os)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> RobotSpecs {
        RobotSpecs::new()
    }

    fn clear(&mut self) {
        self.id.clear();
        self.radius = ::std::option::Option::None;
        self.height = ::std::option::Option::None;
        self.mass = ::std::option::Option::None;
        self.max_linear_kick_speed = ::std::option::Option::None;
        self.max_chip_kick_speed = ::std::option::Option::None;
        self.center_to_dribbler = ::std::option::Option::None;
        self.limits.clear();
        self.wheel_angles.clear();
        self.custom.clear();
        self.special_fields.clear();
    }

    fn default_instance() -> &'static RobotSpecs {
        static instance: RobotSpecs = RobotSpecs {
            id: ::protobuf::MessageField::none(),
            radius: ::std::option::Option::None,
            height: ::std::option::Option::None,
            mass: ::std::option::Option::None,
            max_linear_kick_speed: ::std::option::Option::None,
            max_chip_kick_speed: ::std::option::Option::None,
            center_to_dribbler: ::std::option::Option::None,
            limits: ::protobuf::MessageField::none(),
            wheel_angles: ::protobuf::MessageField::none(),
            custom: ::protobuf::MessageField::none(),
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for RobotSpecs {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("RobotSpecs").unwrap()).clone()
    }
}

impl ::std::fmt::Display for RobotSpecs {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for RobotSpecs {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

// @@protoc_insertion_point(message:RealismConfig)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct RealismConfig {
    // message fields
    // @@protoc_insertion_point(field:RealismConfig.custom)
    pub custom: ::protobuf::MessageField<::protobuf::well_known_types::any::Any>,
    // special fields
    // @@protoc_insertion_point(special_field:RealismConfig.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a RealismConfig {
    fn default() -> &'a RealismConfig {
        <RealismConfig as ::protobuf::Message>::default_instance()
    }
}

impl RealismConfig {
    pub fn new() -> RealismConfig {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(1);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_message_field_accessor::<_, ::protobuf::well_known_types::any::Any>(
            "custom",
            |m: &RealismConfig| { &m.custom },
            |m: &mut RealismConfig| { &mut m.custom },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<RealismConfig>(
            "RealismConfig",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for RealismConfig {
    const NAME: &'static str = "RealismConfig";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                10 => {
                    ::protobuf::rt::read_singular_message_into_field(is, &mut self.custom)?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if let Some(v) = self.custom.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if let Some(v) = self.custom.as_ref() {
            ::protobuf::rt::write_message_field_with_cached_size(1, v, os)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> RealismConfig {
        RealismConfig::new()
    }

    fn clear(&mut self) {
        self.custom.clear();
        self.special_fields.clear();
    }

    fn default_instance() -> &'static RealismConfig {
        static instance: RealismConfig = RealismConfig {
            custom: ::protobuf::MessageField::none(),
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for RealismConfig {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("RealismConfig").unwrap()).clone()
    }
}

impl ::std::fmt::Display for RealismConfig {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for RealismConfig {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

// @@protoc_insertion_point(message:SimulatorConfig)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct SimulatorConfig {
    // message fields
    // @@protoc_insertion_point(field:SimulatorConfig.geometry)
    pub geometry: ::protobuf::MessageField<super::ssl_vision_geometry::SSL_GeometryData>,
    // @@protoc_insertion_point(field:SimulatorConfig.robot_specs)
    pub robot_specs: ::std::vec::Vec<RobotSpecs>,
    // @@protoc_insertion_point(field:SimulatorConfig.realism_config)
    pub realism_config: ::protobuf::MessageField<RealismConfig>,
    // @@protoc_insertion_point(field:SimulatorConfig.vision_port)
    pub vision_port: ::std::option::Option<u32>,
    // special fields
    // @@protoc_insertion_point(special_field:SimulatorConfig.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a SimulatorConfig {
    fn default() -> &'a SimulatorConfig {
        <SimulatorConfig as ::protobuf::Message>::default_instance()
    }
}

impl SimulatorConfig {
    pub fn new() -> SimulatorConfig {
        ::std::default::Default::default()
    }

    // optional uint32 vision_port = 4;

    pub fn vision_port(&self) -> u32 {
        self.vision_port.unwrap_or(0)
    }

    pub fn clear_vision_port(&mut self) {
        self.vision_port = ::std::option::Option::None;
    }

    pub fn has_vision_port(&self) -> bool {
        self.vision_port.is_some()
    }

    // Param is passed by value, moved
    pub fn set_vision_port(&mut self, v: u32) {
        self.vision_port = ::std::option::Option::Some(v);
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(4);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_message_field_accessor::<_, super::ssl_vision_geometry::SSL_GeometryData>(
            "geometry",
            |m: &SimulatorConfig| { &m.geometry },
            |m: &mut SimulatorConfig| { &mut m.geometry },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_vec_simpler_accessor::<_, _>(
            "robot_specs",
            |m: &SimulatorConfig| { &m.robot_specs },
            |m: &mut SimulatorConfig| { &mut m.robot_specs },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_message_field_accessor::<_, RealismConfig>(
            "realism_config",
            |m: &SimulatorConfig| { &m.realism_config },
            |m: &mut SimulatorConfig| { &mut m.realism_config },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_option_accessor::<_, _>(
            "vision_port",
            |m: &SimulatorConfig| { &m.vision_port },
            |m: &mut SimulatorConfig| { &mut m.vision_port },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<SimulatorConfig>(
            "SimulatorConfig",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for SimulatorConfig {
    const NAME: &'static str = "SimulatorConfig";

    fn is_initialized(&self) -> bool {
        for v in &self.geometry {
            if !v.is_initialized() {
                return false;
            }
        };
        for v in &self.robot_specs {
            if !v.is_initialized() {
                return false;
            }
        };
        for v in &self.realism_config {
            if !v.is_initialized() {
                return false;
            }
        };
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                10 => {
                    ::protobuf::rt::read_singular_message_into_field(is, &mut self.geometry)?;
                },
                18 => {
                    self.robot_specs.push(is.read_message()?);
                },
                26 => {
                    ::protobuf::rt::read_singular_message_into_field(is, &mut self.realism_config)?;
                },
                32 => {
                    self.vision_port = ::std::option::Option::Some(is.read_uint32()?);
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if let Some(v) = self.geometry.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        }
        for value in &self.robot_specs {
            let len = value.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        };
        if let Some(v) = self.realism_config.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        }
        if let Some(v) = self.vision_port {
            my_size += ::protobuf::rt::uint32_size(4, v);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if let Some(v) = self.geometry.as_ref() {
            ::protobuf::rt::write_message_field_with_cached_size(1, v, os)?;
        }
        for v in &self.robot_specs {
            ::protobuf::rt::write_message_field_with_cached_size(2, v, os)?;
        };
        if let Some(v) = self.realism_config.as_ref() {
            ::protobuf::rt::write_message_field_with_cached_size(3, v, os)?;
        }
        if let Some(v) = self.vision_port {
            os.write_uint32(4, v)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> SimulatorConfig {
        SimulatorConfig::new()
    }

    fn clear(&mut self) {
        self.geometry.clear();
        self.robot_specs.clear();
        self.realism_config.clear();
        self.vision_port = ::std::option::Option::None;
        self.special_fields.clear();
    }

    fn default_instance() -> &'static SimulatorConfig {
        static instance: SimulatorConfig = SimulatorConfig {
            geometry: ::protobuf::MessageField::none(),
            robot_specs: ::std::vec::Vec::new(),
            realism_config: ::protobuf::MessageField::none(),
            vision_port: ::std::option::Option::None,
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for SimulatorConfig {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("SimulatorConfig").unwrap()).clone()
    }
}

impl ::std::fmt::Display for SimulatorConfig {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for SimulatorConfig {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\x1bssl_simulation_config.proto\x1a\x13ssl_gc_common.proto\x1a\x19ssl_\
    vision_geometry.proto\x1a\x19google/protobuf/any.proto\"\xb7\x02\n\x0bRo\
    botLimits\x127\n\x18acc_speedup_absolute_max\x18\x01\x20\x01(\x02R\x15ac\
    cSpeedupAbsoluteMax\x125\n\x17acc_speedup_angular_max\x18\x02\x20\x01(\
    \x02R\x14accSpeedupAngularMax\x123\n\x16acc_brake_absolute_max\x18\x03\
    \x20\x01(\x02R\x13accBrakeAbsoluteMax\x121\n\x15acc_brake_angular_max\
    \x18\x04\x20\x01(\x02R\x12accBrakeAngularMax\x12(\n\x10vel_absolute_max\
    \x18\x05\x20\x01(\x02R\x0evelAbsoluteMax\x12&\n\x0fvel_angular_max\x18\
    \x06\x20\x01(\x02R\rvelAngularMax\"\x8e\x01\n\x10RobotWheelAngles\x12\
    \x1f\n\x0bfront_right\x18\x01\x20\x02(\x02R\nfrontRight\x12\x1d\n\nback_\
    right\x18\x02\x20\x02(\x02R\tbackRight\x12\x1b\n\tback_left\x18\x03\x20\
    \x02(\x02R\x08backLeft\x12\x1d\n\nfront_left\x18\x04\x20\x02(\x02R\tfron\
    tLeft\"\x94\x03\n\nRobotSpecs\x12\x18\n\x02id\x18\x01\x20\x02(\x0b2\x08.\
    RobotIdR\x02id\x12\x1e\n\x06radius\x18\x02\x20\x01(\x02:\x040.09R\x06rad\
    iusB\0\x12\x1e\n\x06height\x18\x03\x20\x01(\x02:\x040.15R\x06heightB\0\
    \x12\x12\n\x04mass\x18\x04\x20\x01(\x02R\x04mass\x121\n\x15max_linear_ki\
    ck_speed\x18\x07\x20\x01(\x02R\x12maxLinearKickSpeed\x12-\n\x13max_chip_\
    kick_speed\x18\x08\x20\x01(\x02R\x10maxChipKickSpeed\x12,\n\x12center_to\
    _dribbler\x18\t\x20\x01(\x02R\x10centerToDribbler\x12$\n\x06limits\x18\n\
    \x20\x01(\x0b2\x0c.RobotLimitsR\x06limits\x124\n\x0cwheel_angles\x18\r\
    \x20\x01(\x0b2\x11.RobotWheelAnglesR\x0bwheelAngles\x12,\n\x06custom\x18\
    \x0e\x20\x01(\x0b2\x14.google.protobuf.AnyR\x06custom\"=\n\rRealismConfi\
    g\x12,\n\x06custom\x18\x01\x20\x01(\x0b2\x14.google.protobuf.AnyR\x06cus\
    tom\"\xc6\x01\n\x0fSimulatorConfig\x12-\n\x08geometry\x18\x01\x20\x01(\
    \x0b2\x11.SSL_GeometryDataR\x08geometry\x12,\n\x0brobot_specs\x18\x02\
    \x20\x03(\x0b2\x0b.RobotSpecsR\nrobotSpecs\x125\n\x0erealism_config\x18\
    \x03\x20\x01(\x0b2\x0e.RealismConfigR\rrealismConfig\x12\x1f\n\x0bvision\
    _port\x18\x04\x20\x01(\rR\nvisionPortB8Z6github.com/RoboCup-SSL/ssl-simu\
    lation-protocol/pkg/simb\x06proto2\
";

/// `FileDescriptorProto` object which was a source for this generated file
fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    static file_descriptor_proto_lazy: ::protobuf::rt::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::Lazy::new();
    file_descriptor_proto_lazy.get(|| {
        ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
    })
}

/// `FileDescriptor` object which allows dynamic access to files
pub fn file_descriptor() -> &'static ::protobuf::reflect::FileDescriptor {
    static generated_file_descriptor_lazy: ::protobuf::rt::Lazy<::protobuf::reflect::GeneratedFileDescriptor> = ::protobuf::rt::Lazy::new();
    static file_descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::FileDescriptor> = ::protobuf::rt::Lazy::new();
    file_descriptor.get(|| {
        let generated_file_descriptor = generated_file_descriptor_lazy.get(|| {
            let mut deps = ::std::vec::Vec::with_capacity(3);
            deps.push(super::ssl_gc_common::file_descriptor().clone());
            deps.push(super::ssl_vision_geometry::file_descriptor().clone());
            deps.push(::protobuf::well_known_types::any::file_descriptor().clone());
            let mut messages = ::std::vec::Vec::with_capacity(5);
            messages.push(RobotLimits::generated_message_descriptor_data());
            messages.push(RobotWheelAngles::generated_message_descriptor_data());
            messages.push(RobotSpecs::generated_message_descriptor_data());
            messages.push(RealismConfig::generated_message_descriptor_data());
            messages.push(SimulatorConfig::generated_message_descriptor_data());
            let mut enums = ::std::vec::Vec::with_capacity(0);
            ::protobuf::reflect::GeneratedFileDescriptor::new_generated(
                file_descriptor_proto(),
                deps,
                messages,
                enums,
            )
        });
        ::protobuf::reflect::FileDescriptor::new_generated_2(generated_file_descriptor)
    })
}
