// This file is generated by rust-protobuf 3.7.2. Do not edit
// .proto file is parsed by pure
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_results)]
#![allow(unused_mut)]

//! Generated file from `ssl_simulation_synchronous.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_3_7_2;

// @@protoc_insertion_point(message:SimulationSyncRequest)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct SimulationSyncRequest {
    // message fields
    // @@protoc_insertion_point(field:SimulationSyncRequest.sim_step)
    pub sim_step: ::std::option::Option<f32>,
    // @@protoc_insertion_point(field:SimulationSyncRequest.simulator_command)
    pub simulator_command: ::protobuf::MessageField<super::ssl_simulation_control::SimulatorCommand>,
    // @@protoc_insertion_point(field:SimulationSyncRequest.robot_control)
    pub robot_control: ::protobuf::MessageField<super::ssl_simulation_robot_control::RobotControl>,
    // special fields
    // @@protoc_insertion_point(special_field:SimulationSyncRequest.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a SimulationSyncRequest {
    fn default() -> &'a SimulationSyncRequest {
        <SimulationSyncRequest as ::protobuf::Message>::default_instance()
    }
}

impl SimulationSyncRequest {
    pub fn new() -> SimulationSyncRequest {
        ::std::default::Default::default()
    }

    // optional float sim_step = 1;

    pub fn sim_step(&self) -> f32 {
        self.sim_step.unwrap_or(0.)
    }

    pub fn clear_sim_step(&mut self) {
        self.sim_step = ::std::option::Option::None;
    }

    pub fn has_sim_step(&self) -> bool {
        self.sim_step.is_some()
    }

    // Param is passed by value, moved
    pub fn set_sim_step(&mut self, v: f32) {
        self.sim_step = ::std::option::Option::Some(v);
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(3);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_option_accessor::<_, _>(
            "sim_step",
            |m: &SimulationSyncRequest| { &m.sim_step },
            |m: &mut SimulationSyncRequest| { &mut m.sim_step },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_message_field_accessor::<_, super::ssl_simulation_control::SimulatorCommand>(
            "simulator_command",
            |m: &SimulationSyncRequest| { &m.simulator_command },
            |m: &mut SimulationSyncRequest| { &mut m.simulator_command },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_message_field_accessor::<_, super::ssl_simulation_robot_control::RobotControl>(
            "robot_control",
            |m: &SimulationSyncRequest| { &m.robot_control },
            |m: &mut SimulationSyncRequest| { &mut m.robot_control },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<SimulationSyncRequest>(
            "SimulationSyncRequest",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for SimulationSyncRequest {
    const NAME: &'static str = "SimulationSyncRequest";

    fn is_initialized(&self) -> bool {
        for v in &self.simulator_command {
            if !v.is_initialized() {
                return false;
            }
        };
        for v in &self.robot_control {
            if !v.is_initialized() {
                return false;
            }
        };
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                13 => {
                    self.sim_step = ::std::option::Option::Some(is.read_float()?);
                },
                18 => {
                    ::protobuf::rt::read_singular_message_into_field(is, &mut self.simulator_command)?;
                },
                26 => {
                    ::protobuf::rt::read_singular_message_into_field(is, &mut self.robot_control)?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if let Some(v) = self.sim_step {
            my_size += 1 + 4;
        }
        if let Some(v) = self.simulator_command.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        }
        if let Some(v) = self.robot_control.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if let Some(v) = self.sim_step {
            os.write_float(1, v)?;
        }
        if let Some(v) = self.simulator_command.as_ref() {
            ::protobuf::rt::write_message_field_with_cached_size(2, v, os)?;
        }
        if let Some(v) = self.robot_control.as_ref() {
            ::protobuf::rt::write_message_field_with_cached_size(3, v, os)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> SimulationSyncRequest {
        SimulationSyncRequest::new()
    }

    fn clear(&mut self) {
        self.sim_step = ::std::option::Option::None;
        self.simulator_command.clear();
        self.robot_control.clear();
        self.special_fields.clear();
    }

    fn default_instance() -> &'static SimulationSyncRequest {
        static instance: SimulationSyncRequest = SimulationSyncRequest {
            sim_step: ::std::option::Option::None,
            simulator_command: ::protobuf::MessageField::none(),
            robot_control: ::protobuf::MessageField::none(),
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for SimulationSyncRequest {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("SimulationSyncRequest").unwrap()).clone()
    }
}

impl ::std::fmt::Display for SimulationSyncRequest {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for SimulationSyncRequest {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

// @@protoc_insertion_point(message:SimulationSyncResponse)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct SimulationSyncResponse {
    // message fields
    // @@protoc_insertion_point(field:SimulationSyncResponse.detection)
    pub detection: ::std::vec::Vec<super::ssl_vision_detection::SSL_DetectionFrame>,
    // @@protoc_insertion_point(field:SimulationSyncResponse.robot_control_response)
    pub robot_control_response: ::protobuf::MessageField<super::ssl_simulation_robot_feedback::RobotControlResponse>,
    // special fields
    // @@protoc_insertion_point(special_field:SimulationSyncResponse.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a SimulationSyncResponse {
    fn default() -> &'a SimulationSyncResponse {
        <SimulationSyncResponse as ::protobuf::Message>::default_instance()
    }
}

impl SimulationSyncResponse {
    pub fn new() -> SimulationSyncResponse {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(2);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_vec_simpler_accessor::<_, _>(
            "detection",
            |m: &SimulationSyncResponse| { &m.detection },
            |m: &mut SimulationSyncResponse| { &mut m.detection },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_message_field_accessor::<_, super::ssl_simulation_robot_feedback::RobotControlResponse>(
            "robot_control_response",
            |m: &SimulationSyncResponse| { &m.robot_control_response },
            |m: &mut SimulationSyncResponse| { &mut m.robot_control_response },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<SimulationSyncResponse>(
            "SimulationSyncResponse",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for SimulationSyncResponse {
    const NAME: &'static str = "SimulationSyncResponse";

    fn is_initialized(&self) -> bool {
        for v in &self.detection {
            if !v.is_initialized() {
                return false;
            }
        };
        for v in &self.robot_control_response {
            if !v.is_initialized() {
                return false;
            }
        };
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                10 => {
                    self.detection.push(is.read_message()?);
                },
                18 => {
                    ::protobuf::rt::read_singular_message_into_field(is, &mut self.robot_control_response)?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        for value in &self.detection {
            let len = value.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        };
        if let Some(v) = self.robot_control_response.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        for v in &self.detection {
            ::protobuf::rt::write_message_field_with_cached_size(1, v, os)?;
        };
        if let Some(v) = self.robot_control_response.as_ref() {
            ::protobuf::rt::write_message_field_with_cached_size(2, v, os)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> SimulationSyncResponse {
        SimulationSyncResponse::new()
    }

    fn clear(&mut self) {
        self.detection.clear();
        self.robot_control_response.clear();
        self.special_fields.clear();
    }

    fn default_instance() -> &'static SimulationSyncResponse {
        static instance: SimulationSyncResponse = SimulationSyncResponse {
            detection: ::std::vec::Vec::new(),
            robot_control_response: ::protobuf::MessageField::none(),
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for SimulationSyncResponse {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("SimulationSyncResponse").unwrap()).clone()
    }
}

impl ::std::fmt::Display for SimulationSyncResponse {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for SimulationSyncResponse {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\x20ssl_simulation_synchronous.proto\x1a\x1assl_vision_detection.proto\
    \x1a#ssl_simulation_robot_feedback.proto\x1a\"ssl_simulation_robot_contr\
    ol.proto\x1a\x1cssl_simulation_control.proto\"\xa6\x01\n\x15SimulationSy\
    ncRequest\x12\x19\n\x08sim_step\x18\x01\x20\x01(\x02R\x07simStep\x12>\n\
    \x11simulator_command\x18\x02\x20\x01(\x0b2\x11.SimulatorCommandR\x10sim\
    ulatorCommand\x122\n\rrobot_control\x18\x03\x20\x01(\x0b2\r.RobotControl\
    R\x0crobotControl\"\x98\x01\n\x16SimulationSyncResponse\x121\n\tdetectio\
    n\x18\x01\x20\x03(\x0b2\x13.SSL_DetectionFrameR\tdetection\x12K\n\x16rob\
    ot_control_response\x18\x02\x20\x01(\x0b2\x15.RobotControlResponseR\x14r\
    obotControlResponseB8Z6github.com/RoboCup-SSL/ssl-simulation-protocol/pk\
    g/simb\x06proto2\
";

/// `FileDescriptorProto` object which was a source for this generated file
fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    static file_descriptor_proto_lazy: ::protobuf::rt::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::Lazy::new();
    file_descriptor_proto_lazy.get(|| {
        ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
    })
}

/// `FileDescriptor` object which allows dynamic access to files
pub fn file_descriptor() -> &'static ::protobuf::reflect::FileDescriptor {
    static generated_file_descriptor_lazy: ::protobuf::rt::Lazy<::protobuf::reflect::GeneratedFileDescriptor> = ::protobuf::rt::Lazy::new();
    static file_descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::FileDescriptor> = ::protobuf::rt::Lazy::new();
    file_descriptor.get(|| {
        let generated_file_descriptor = generated_file_descriptor_lazy.get(|| {
            let mut deps = ::std::vec::Vec::with_capacity(4);
            deps.push(super::ssl_vision_detection::file_descriptor().clone());
            deps.push(super::ssl_simulation_robot_feedback::file_descriptor().clone());
            deps.push(super::ssl_simulation_robot_control::file_descriptor().clone());
            deps.push(super::ssl_simulation_control::file_descriptor().clone());
            let mut messages = ::std::vec::Vec::with_capacity(2);
            messages.push(SimulationSyncRequest::generated_message_descriptor_data());
            messages.push(SimulationSyncResponse::generated_message_descriptor_data());
            let mut enums = ::std::vec::Vec::with_capacity(0);
            ::protobuf::reflect::GeneratedFileDescriptor::new_generated(
                file_descriptor_proto(),
                deps,
                messages,
                enums,
            )
        });
        ::protobuf::reflect::FileDescriptor::new_generated_2(generated_file_descriptor)
    })
}
