// This file is generated by rust-protobuf 3.7.2. Do not edit
// .proto file is parsed by pure
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_results)]
#![allow(unused_mut)]

//! Generated file from `ssl_gc_rcon_autoref.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_3_7_2;

// @@protoc_insertion_point(message:AutoRefRegistration)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct AutoRefRegistration {
    // message fields
    // @@protoc_insertion_point(field:AutoRefRegistration.identifier)
    pub identifier: ::std::option::Option<::std::string::String>,
    // @@protoc_insertion_point(field:AutoRefRegistration.signature)
    pub signature: ::protobuf::MessageField<super::ssl_gc_rcon::Signature>,
    // special fields
    // @@protoc_insertion_point(special_field:AutoRefRegistration.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a AutoRefRegistration {
    fn default() -> &'a AutoRefRegistration {
        <AutoRefRegistration as ::protobuf::Message>::default_instance()
    }
}

impl AutoRefRegistration {
    pub fn new() -> AutoRefRegistration {
        ::std::default::Default::default()
    }

    // required string identifier = 1;

    pub fn identifier(&self) -> &str {
        match self.identifier.as_ref() {
            Some(v) => v,
            None => "",
        }
    }

    pub fn clear_identifier(&mut self) {
        self.identifier = ::std::option::Option::None;
    }

    pub fn has_identifier(&self) -> bool {
        self.identifier.is_some()
    }

    // Param is passed by value, moved
    pub fn set_identifier(&mut self, v: ::std::string::String) {
        self.identifier = ::std::option::Option::Some(v);
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_identifier(&mut self) -> &mut ::std::string::String {
        if self.identifier.is_none() {
            self.identifier = ::std::option::Option::Some(::std::string::String::new());
        }
        self.identifier.as_mut().unwrap()
    }

    // Take field
    pub fn take_identifier(&mut self) -> ::std::string::String {
        self.identifier.take().unwrap_or_else(|| ::std::string::String::new())
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(2);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_option_accessor::<_, _>(
            "identifier",
            |m: &AutoRefRegistration| { &m.identifier },
            |m: &mut AutoRefRegistration| { &mut m.identifier },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_message_field_accessor::<_, super::ssl_gc_rcon::Signature>(
            "signature",
            |m: &AutoRefRegistration| { &m.signature },
            |m: &mut AutoRefRegistration| { &mut m.signature },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<AutoRefRegistration>(
            "AutoRefRegistration",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for AutoRefRegistration {
    const NAME: &'static str = "AutoRefRegistration";

    fn is_initialized(&self) -> bool {
        if self.identifier.is_none() {
            return false;
        }
        for v in &self.signature {
            if !v.is_initialized() {
                return false;
            }
        };
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                10 => {
                    self.identifier = ::std::option::Option::Some(is.read_string()?);
                },
                18 => {
                    ::protobuf::rt::read_singular_message_into_field(is, &mut self.signature)?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if let Some(v) = self.identifier.as_ref() {
            my_size += ::protobuf::rt::string_size(1, &v);
        }
        if let Some(v) = self.signature.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if let Some(v) = self.identifier.as_ref() {
            os.write_string(1, v)?;
        }
        if let Some(v) = self.signature.as_ref() {
            ::protobuf::rt::write_message_field_with_cached_size(2, v, os)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> AutoRefRegistration {
        AutoRefRegistration::new()
    }

    fn clear(&mut self) {
        self.identifier = ::std::option::Option::None;
        self.signature.clear();
        self.special_fields.clear();
    }

    fn default_instance() -> &'static AutoRefRegistration {
        static instance: AutoRefRegistration = AutoRefRegistration {
            identifier: ::std::option::Option::None,
            signature: ::protobuf::MessageField::none(),
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for AutoRefRegistration {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("AutoRefRegistration").unwrap()).clone()
    }
}

impl ::std::fmt::Display for AutoRefRegistration {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for AutoRefRegistration {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

// @@protoc_insertion_point(message:AutoRefToController)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct AutoRefToController {
    // message fields
    // @@protoc_insertion_point(field:AutoRefToController.signature)
    pub signature: ::protobuf::MessageField<super::ssl_gc_rcon::Signature>,
    // @@protoc_insertion_point(field:AutoRefToController.game_event)
    pub game_event: ::protobuf::MessageField<super::ssl_gc_game_event::GameEvent>,
    // special fields
    // @@protoc_insertion_point(special_field:AutoRefToController.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a AutoRefToController {
    fn default() -> &'a AutoRefToController {
        <AutoRefToController as ::protobuf::Message>::default_instance()
    }
}

impl AutoRefToController {
    pub fn new() -> AutoRefToController {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(2);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_message_field_accessor::<_, super::ssl_gc_rcon::Signature>(
            "signature",
            |m: &AutoRefToController| { &m.signature },
            |m: &mut AutoRefToController| { &mut m.signature },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_message_field_accessor::<_, super::ssl_gc_game_event::GameEvent>(
            "game_event",
            |m: &AutoRefToController| { &m.game_event },
            |m: &mut AutoRefToController| { &mut m.game_event },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<AutoRefToController>(
            "AutoRefToController",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for AutoRefToController {
    const NAME: &'static str = "AutoRefToController";

    fn is_initialized(&self) -> bool {
        for v in &self.signature {
            if !v.is_initialized() {
                return false;
            }
        };
        for v in &self.game_event {
            if !v.is_initialized() {
                return false;
            }
        };
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                10 => {
                    ::protobuf::rt::read_singular_message_into_field(is, &mut self.signature)?;
                },
                18 => {
                    ::protobuf::rt::read_singular_message_into_field(is, &mut self.game_event)?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if let Some(v) = self.signature.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        }
        if let Some(v) = self.game_event.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if let Some(v) = self.signature.as_ref() {
            ::protobuf::rt::write_message_field_with_cached_size(1, v, os)?;
        }
        if let Some(v) = self.game_event.as_ref() {
            ::protobuf::rt::write_message_field_with_cached_size(2, v, os)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> AutoRefToController {
        AutoRefToController::new()
    }

    fn clear(&mut self) {
        self.signature.clear();
        self.game_event.clear();
        self.special_fields.clear();
    }

    fn default_instance() -> &'static AutoRefToController {
        static instance: AutoRefToController = AutoRefToController {
            signature: ::protobuf::MessageField::none(),
            game_event: ::protobuf::MessageField::none(),
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for AutoRefToController {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("AutoRefToController").unwrap()).clone()
    }
}

impl ::std::fmt::Display for AutoRefToController {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for AutoRefToController {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

// @@protoc_insertion_point(message:ControllerToAutoRef)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct ControllerToAutoRef {
    // message oneof groups
    pub msg: ::std::option::Option<controller_to_auto_ref::Msg>,
    // special fields
    // @@protoc_insertion_point(special_field:ControllerToAutoRef.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a ControllerToAutoRef {
    fn default() -> &'a ControllerToAutoRef {
        <ControllerToAutoRef as ::protobuf::Message>::default_instance()
    }
}

impl ControllerToAutoRef {
    pub fn new() -> ControllerToAutoRef {
        ::std::default::Default::default()
    }

    // optional .ControllerReply controller_reply = 1;

    pub fn controller_reply(&self) -> &super::ssl_gc_rcon::ControllerReply {
        match self.msg {
            ::std::option::Option::Some(controller_to_auto_ref::Msg::ControllerReply(ref v)) => v,
            _ => <super::ssl_gc_rcon::ControllerReply as ::protobuf::Message>::default_instance(),
        }
    }

    pub fn clear_controller_reply(&mut self) {
        self.msg = ::std::option::Option::None;
    }

    pub fn has_controller_reply(&self) -> bool {
        match self.msg {
            ::std::option::Option::Some(controller_to_auto_ref::Msg::ControllerReply(..)) => true,
            _ => false,
        }
    }

    // Param is passed by value, moved
    pub fn set_controller_reply(&mut self, v: super::ssl_gc_rcon::ControllerReply) {
        self.msg = ::std::option::Option::Some(controller_to_auto_ref::Msg::ControllerReply(v))
    }

    // Mutable pointer to the field.
    pub fn mut_controller_reply(&mut self) -> &mut super::ssl_gc_rcon::ControllerReply {
        if let ::std::option::Option::Some(controller_to_auto_ref::Msg::ControllerReply(_)) = self.msg {
        } else {
            self.msg = ::std::option::Option::Some(controller_to_auto_ref::Msg::ControllerReply(super::ssl_gc_rcon::ControllerReply::new()));
        }
        match self.msg {
            ::std::option::Option::Some(controller_to_auto_ref::Msg::ControllerReply(ref mut v)) => v,
            _ => panic!(),
        }
    }

    // Take field
    pub fn take_controller_reply(&mut self) -> super::ssl_gc_rcon::ControllerReply {
        if self.has_controller_reply() {
            match self.msg.take() {
                ::std::option::Option::Some(controller_to_auto_ref::Msg::ControllerReply(v)) => v,
                _ => panic!(),
            }
        } else {
            super::ssl_gc_rcon::ControllerReply::new()
        }
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(1);
        let mut oneofs = ::std::vec::Vec::with_capacity(1);
        fields.push(::protobuf::reflect::rt::v2::make_oneof_message_has_get_mut_set_accessor::<_, super::ssl_gc_rcon::ControllerReply>(
            "controller_reply",
            ControllerToAutoRef::has_controller_reply,
            ControllerToAutoRef::controller_reply,
            ControllerToAutoRef::mut_controller_reply,
            ControllerToAutoRef::set_controller_reply,
        ));
        oneofs.push(controller_to_auto_ref::Msg::generated_oneof_descriptor_data());
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<ControllerToAutoRef>(
            "ControllerToAutoRef",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for ControllerToAutoRef {
    const NAME: &'static str = "ControllerToAutoRef";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                10 => {
                    self.msg = ::std::option::Option::Some(controller_to_auto_ref::Msg::ControllerReply(is.read_message()?));
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if let ::std::option::Option::Some(ref v) = self.msg {
            match v {
                &controller_to_auto_ref::Msg::ControllerReply(ref v) => {
                    let len = v.compute_size();
                    my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
                },
            };
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if let ::std::option::Option::Some(ref v) = self.msg {
            match v {
                &controller_to_auto_ref::Msg::ControllerReply(ref v) => {
                    ::protobuf::rt::write_message_field_with_cached_size(1, v, os)?;
                },
            };
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> ControllerToAutoRef {
        ControllerToAutoRef::new()
    }

    fn clear(&mut self) {
        self.msg = ::std::option::Option::None;
        self.special_fields.clear();
    }

    fn default_instance() -> &'static ControllerToAutoRef {
        static instance: ControllerToAutoRef = ControllerToAutoRef {
            msg: ::std::option::Option::None,
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for ControllerToAutoRef {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("ControllerToAutoRef").unwrap()).clone()
    }
}

impl ::std::fmt::Display for ControllerToAutoRef {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for ControllerToAutoRef {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

/// Nested message and enums of message `ControllerToAutoRef`
pub mod controller_to_auto_ref {

    #[derive(Clone,PartialEq,Debug)]
    #[non_exhaustive]
    // @@protoc_insertion_point(oneof:ControllerToAutoRef.msg)
    pub enum Msg {
        // @@protoc_insertion_point(oneof_field:ControllerToAutoRef.controller_reply)
        ControllerReply(super::super::ssl_gc_rcon::ControllerReply),
    }

    impl ::protobuf::Oneof for Msg {
    }

    impl ::protobuf::OneofFull for Msg {
        fn descriptor() -> ::protobuf::reflect::OneofDescriptor {
            static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::OneofDescriptor> = ::protobuf::rt::Lazy::new();
            descriptor.get(|| <super::ControllerToAutoRef as ::protobuf::MessageFull>::descriptor().oneof_by_name("msg").unwrap()).clone()
        }
    }

    impl Msg {
        pub(in super) fn generated_oneof_descriptor_data() -> ::protobuf::reflect::GeneratedOneofDescriptorData {
            ::protobuf::reflect::GeneratedOneofDescriptorData::new::<Msg>("msg")
        }
    }
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\x19ssl_gc_rcon_autoref.proto\x1a\x17ssl_gc_game_event.proto\x1a\x11ss\
    l_gc_rcon.proto\"_\n\x13AutoRefRegistration\x12\x1e\n\nidentifier\x18\
    \x01\x20\x02(\tR\nidentifier\x12(\n\tsignature\x18\x02\x20\x01(\x0b2\n.S\
    ignatureR\tsignature\"v\n\x13AutoRefToController\x12(\n\tsignature\x18\
    \x01\x20\x01(\x0b2\n.SignatureR\tsignature\x12)\n\ngame_event\x18\x02\
    \x20\x01(\x0b2\n.GameEventR\tgameEventJ\x04\x08\x03\x10\x04J\x04\x08\x04\
    \x10\x05\"[\n\x13ControllerToAutoRef\x12=\n\x10controller_reply\x18\x01\
    \x20\x01(\x0b2\x10.ControllerReplyH\0R\x0fcontrollerReplyB\x05\n\x03msgb\
    \x06proto2\
";

/// `FileDescriptorProto` object which was a source for this generated file
fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    static file_descriptor_proto_lazy: ::protobuf::rt::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::Lazy::new();
    file_descriptor_proto_lazy.get(|| {
        ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
    })
}

/// `FileDescriptor` object which allows dynamic access to files
pub fn file_descriptor() -> &'static ::protobuf::reflect::FileDescriptor {
    static generated_file_descriptor_lazy: ::protobuf::rt::Lazy<::protobuf::reflect::GeneratedFileDescriptor> = ::protobuf::rt::Lazy::new();
    static file_descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::FileDescriptor> = ::protobuf::rt::Lazy::new();
    file_descriptor.get(|| {
        let generated_file_descriptor = generated_file_descriptor_lazy.get(|| {
            let mut deps = ::std::vec::Vec::with_capacity(2);
            deps.push(super::ssl_gc_game_event::file_descriptor().clone());
            deps.push(super::ssl_gc_rcon::file_descriptor().clone());
            let mut messages = ::std::vec::Vec::with_capacity(3);
            messages.push(AutoRefRegistration::generated_message_descriptor_data());
            messages.push(AutoRefToController::generated_message_descriptor_data());
            messages.push(ControllerToAutoRef::generated_message_descriptor_data());
            let mut enums = ::std::vec::Vec::with_capacity(0);
            ::protobuf::reflect::GeneratedFileDescriptor::new_generated(
                file_descriptor_proto(),
                deps,
                messages,
                enums,
            )
        });
        ::protobuf::reflect::FileDescriptor::new_generated_2(generated_file_descriptor)
    })
}
